### PR TITLE
fix: wrong German wordings [AR-3239][AR-3240]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3239" title="AR-3239" target="_blank">BugAR-3239</a>  Wrong wording in second line message when being added or removed from a conversation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
String copies for preview messages on the conversation items were wrongly mapped to inaccurate strings. Since the English string didn't differentiate between 1st and 3rd person of the singular indicative present form.

### Solutions

Check whether the form includes the self user or another user, and choose the right copy.

### Attachments (Optional)

| Before | After |
| ----------- | ------------ |
| Captura de pantalla 2023-03-24 a las 9 45 25 |  Captura de pantalla 2023-03-24 a las 10 17 11 |

-->

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1578/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1578/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1578/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6068847)(6068847)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6068847)(6068847)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]
Languages 🙄

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Pull request merged**
