### PR TITLE
fix: conversation screen top bar spacing [WPB-971]

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Current usage of space on the conversation screen top bar is not optimal and not much of the conversation title fits on the screen.

### Solutions

Decrease spacing between top bar elements, reduce buttons widths, title font size and avatar size.
To make it possible to narrow the buttons, `LocalMinimumInteractiveComponentEnforcement` is disabled for `WireButton` (it makes the clickable elements to have minimal dimensions required by system) and instead, new parameter `minClickableSize` is provided to be able to apply custom values to that. Also, `minWidth` and `minHeight` are grouped into `minSize` to keep consistency and all hardcoded button sizes are replaced with values defined in `WireDimensions`.

### Attachments (Optional)

| Before | After |
| ----------- | ------------ |
| conversation_topbar_before | conversation_topbar_after |

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [630](https://10.10.124.134/job/AR-build-pipeline/630/) **failed**.

**Comment by AndroidBob** [comment]
Build [633](https://10.10.124.134/job/AR-build-pipeline/633/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7513623)(7513623)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7513623)(7513623)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Comment by vitorhugods** [comment]
> To make it possible to narrow the buttons, `LocalMinimumInteractiveComponentEnforcement` is disabled for `WireButton` (it makes the clickable elements to have minimal dimensions required by system)

Doesn't it cause an accessibility issue?

**Review by alexandreferris — APPROVED** [review]

**Comment by saleniuk** [comment]
> > To make it possible to narrow the buttons, `LocalMinimumInteractiveComponentEnforcement` is disabled for `WireButton` (it makes the clickable elements to have minimal dimensions required by system)
> 
> Doesn't it cause an accessibility issue?

I think it shouldn’t, as long as we don't set too small `minClickableSize`. Reducing it from 48.dp to 40.dp only in width should be still acceptable, but true - it may be a potential problem, but I believe that no one will accidentally create a button that is not clickable, by default they are set to have reasonable sizes, the same as required by the system.

**Comment by AndroidBob** [comment]
Build [675](https://10.10.124.134/job/AR-build-pipeline/675/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7521953)(7521953)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7521953)(7521953)-staging-compat.apk)

**Pull request merged**
