### PR TITLE
fix: [RC] Add callback to handle deeplink only when Navigation Graph is done (AR-3290)

### PR DESCRIPTION
**Pull request by alexandreferris**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3290" title="AR-3290" target="_blank">BugAR-3290</a>  Playstore crash: com.wire.android.navigation.NavigationUtilsKt.navigateToItem
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

[AR-3290 - com.wire.android.navigation.NavigationUtilsKt.navigateToItem ](https://wearezeta.atlassian.net/browse/AR-3290)

### Issues

Sometimes while handling some screen through deeplinks (from notifications for example when you receive a message or an incoming call) the app would handle it before having the navigation graph fully built.

### Solutions

Added a callback to when navigation graph is fully built to only then handle deeplinks.

#### How to Test

Currently not very able to test unless you force the issue (fully commenting the creation of the navigation graph)

### Notes (Optional)

Also added a log on `NavigationUtils.NavController.navigateToItem(..)` to show which screen is being opened, in case this fix doesn't end up fixing the whole issue we will at least know from where the navigation is coming from.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1711/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6345760)(6345760)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6345760)(6345760)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]
Good catch 🕵️ ✅

**Review by gongracr — APPROVED** [review]
Beautiful stuff! 🦋

**Review by borichellow — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1711/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6346322)(6346322)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6346322)(6346322)-staging-compat.apk)

**Pull request merged**
