### PR TITLE
chore(ci): include build info in tests (WPB-4505)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4505" title="WPB-4505" target="_blank">BugWPB-4505</a>  integration-tests-android.zip and unit-tests-android.zip are missing information about build/revision
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We need to provide extra info for the evaluators of the test reports.

### Solutions

Append the git hash to the test report file names.

#### How to Test

Push and verify that reports `integration-tests-android.zip` and `unit-tests-android.zip` are generated with the git hash in its name.

ie: `integration-tests-android_GITHASH.zip`

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1257](https://10.10.124.134/job/AR-build-pipeline/1257/) **failed**.

**Review by vitorhugods — APPROVED** [review]

**Review by mythsunwind — APPROVED** [review]
👍

**Comment by yamilmedina** [comment]
Screenshot 2023-10-12 at 15 50 20

**Comment by AndroidBob** [comment]
Build [1266](https://10.10.124.134/job/AR-build-pipeline/1266/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7814971)(7814971)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7814971)(7814971)-staging-compat.apk)

**Pull request merged**
