### PR TITLE
chore: turn on constant bitrate calls with federation (FS-138)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-138" title="FS-138" target="_blank">StoryFS-138</a>  [Android] As the organizer of a conference call I like to place a conference call in a conversation with users who are part of different federated backends
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

N/A

### Solutions

Enabling the federation flag and constant bitrate flag for testing purpose

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/4/)

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/5/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/8/)

**Comment by AndroidBob** [comment]
Build Failure
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/9/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/12/)

**Comment by AndroidBob** [comment]
Build Success
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/13/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:18
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/18/)

**Comment by AndroidBob** [comment]
Build Success
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/21/)

**Comment by AndroidBob** [comment]
Build Success
ID:22
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3655/22/)

**Comment by marcoconti83** [comment]
Since federation support is now controlled by a run-time configuration and not by a compile-time value, this PR is now obsolete and I will close it.

**Pull request closed without merging**
