### PR TITLE
feat: Inform user about degraded conversation verification status (WPD-573)

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

Added the new `SystemMessage` for the case when the conversation's verification status degraded.

### Attachments (Optional)

**PS**: the typos are temporary as it's gonna be changed later.

Screenshot 2023-07-21 at 11 44 33
Screenshot 2023-07-21 at 11 44 18

----
#### Dependencies

Waitig for the Kalium PR:
- https://github.com/wireapp/kalium/pull/1893

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [595](https://10.10.124.134/job/AR-build-pipeline/595/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7096356)(7096356)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7096356)(7096356)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Review by vitorhugods — APPROVED** [review]

**Review by mchenani — APPROVED** [review]

**Comment by ohassine** [comment]
In the screenshots we are showing the same message with two different icons, is that correct ?

**Comment by borichellow** [comment]
> In the screenshots we are showing the same message with two different icons, is that correct ?

Currently, the Proteus message is not possible as the kalium part for that is not implemented yet, and these texts might be changed in the future to describe the exact reason for degrading verification (also not implemented yet).  
So i'd say these texts are not important so far :)

**Comment by AndroidBob** [comment]
Build [623](https://10.10.124.134/job/AR-build-pipeline/623/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7123921)(7123921)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7123921)(7123921)-staging-compat.apk)

**Pull request merged**
