### PR TITLE
fix: remove system agent from kalium user agent

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

user agent included info about the device model and os build, since such info are not needed it is wise to remove it.

### Solutions

remove it

----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1744/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6370705)(6370705)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6370705)(6370705)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
🤫🤫🤫🤫🤫

**Comment by vitorhugods** [comment]
I bet this is for privacy reasons, but could you please clarify this in the PR body, @MohamadJaara ?

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1744/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6372798)(6372798)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6372798)(6372798)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1744/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6373170)(6373170)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6373170)(6373170)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1744/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6404665)(6404665)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6404665)(6404665)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Pull request merged**
