### PR TITLE
fix: Not receiving notifications after logout login

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

### Issues

STR:
- be logged in with some user
- log out (soft/hard doesn't meter)
- login again with the same user
Result: 
after that user doesn't receive notifications while the app is in background 

### Causes (Optional)

The Observing notification jobs were not canceled on logout, so the app thought it's already observing the notifications for that user. 

### Solutions

Cancel Observing notification jobs on Logout

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1715/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6346366)(6346366)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6346366)(6346366)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by ohassine — APPROVED** [review]
LGTM 👌

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1715/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6346643)(6346643)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6346643)(6346643)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1715/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6346843)(6346843)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6346843)(6346843)-staging-compat.apk)

**Pull request merged**
