### PR TITLE
fix: Notifications: More aggressive cancelling of notifications (SQCORE-1199)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1199" title="SQCORE-1199" target="_blank">SubtaskSQCORE-1199</a>  [Android] Ensure notifications are cancelled
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/SQCORE-1199

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow
  - [x] contains a reference JIRA issue number
  - [x] answers the question: _If merged, this PR will: ..._

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
Too often notifications stay in the notifications tray or reappear there even after they are swiped away by the user. The only sure way to get rid of them is to go to the conversation they are from. But when you get a lot of notifications from many conversations, this could be tedious.

### Solutions

In this PR I fix the way the app notices when we open it and when we switch from the conversation list to a conversation and back. Thanks to this it's now possible to remove all notifications for the given user account (not only for one conversation) when the user goes to the conversation list. Also, I added a line where all the notifications from the user account are cancelled when the user logs out.

### Testing

Manually 

#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3632/1/)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3632/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3632/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3632/4/)

**Pull request merged**
