### PR TITLE
refactor: update participants list to new designs [WPB-986]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-986" title="WPB-986" target="_blank">StoryWPB-986</a>  [Conversation details] Improve participants tab UI
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

As a user, I want to be able to have an overview of all participants in a group directly, so that I can act accordingly, understand who is a group admin, know how many participants are there in total, etc.

### Causes (Optional)

Right now, first version of this screen was showing only part of the list - up to 4 members and 4 admins. Only after clicking on "show all participants" user was navigated to another screen where he/she could see the whole participants list. This was pointed out by users in their feedback.

### Solutions

Show full lists of admins and members directly in participants tab on conversation details screen, move "add participants" button to bottom of the screen. Updated `TabItem` to allow more possibilities when it comes to naming by using `UIText` instead of plain `String`. Added option to disable `animateItemPlacement` for items in `folderWithElements` because it was causing some issues when scrolling on this screen with collapsing top bar and bottom bar.

#### How to Test

Open conversation details and select "participants" tab.

### Attachments (Optional)

| Before | After |
| ----------- | ------------ |
| <video src="https://github.com/wireapp/wire-android/assets/30429749/ffde15fe-5d53-46d3-83cc-60db01421653"/> | <video src="https://github.com/wireapp/wire-android/assets/30429749/f4c182a4-83aa-4082-9318-f0fa752dc010"/> |

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4018](https://10.10.124.134/job/AR-build-pipeline/4018/) **failed**.

**Comment by AndroidBob** [comment]
Build [4025](https://10.10.124.134/job/AR-build-pipeline/4025/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9337434)(9337434)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9337434)(9337434)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4032](https://10.10.124.134/job/AR-build-pipeline/4032/) **failed**.

**Comment by AndroidBob** [comment]
Build [4033](https://10.10.124.134/job/AR-build-pipeline/4033/) **failed**.

**Comment by AndroidBob** [comment]
Build [4034](https://10.10.124.134/job/AR-build-pipeline/4034/) **failed**.

**Comment by AndroidBob** [comment]
Build [4036](https://10.10.124.134/job/AR-build-pipeline/4036/) **failed**.

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4200](https://10.10.124.134/job/AR-build-pipeline/4200/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9419287)(9419287)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9419287)(9419287)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Pull request merged**
