### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [696](https://10.10.124.134/job/AR-build-pipeline/696/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7553922)(7553922)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7553922)(7553922)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [726](https://10.10.124.134/job/AR-build-pipeline/726/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7556542)(7556542)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7556542)(7556542)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [740](https://10.10.124.134/job/AR-build-pipeline/740/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7557575)(7557575)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7557575)(7557575)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [752](https://10.10.124.134/job/AR-build-pipeline/752/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7562885)(7562885)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7562885)(7562885)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [763](https://10.10.124.134/job/AR-build-pipeline/763/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7564105)(7564105)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7564105)(7564105)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [786](https://10.10.124.134/job/AR-build-pipeline/786/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7572691)(7572691)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7572691)(7572691)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [793](https://10.10.124.134/job/AR-build-pipeline/793/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7573229)(7573229)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7573229)(7573229)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [796](https://10.10.124.134/job/AR-build-pipeline/796/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7573981)(7573981)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7573981)(7573981)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [802](https://10.10.124.134/job/AR-build-pipeline/802/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7579732)(7579732)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7579732)(7579732)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [809](https://10.10.124.134/job/AR-build-pipeline/809/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7580389)(7580389)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7580389)(7580389)-staging-compat.apk)

**Pull request merged**
