### PR TITLE
feat: message draft [WPB-1021]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-1021" title="WPB-1021" target="_blank">StoryWPB-1021</a>  Keep messages as draft
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Implemented message drafts saved when user types text with mentions and quoted message. 

### Attachments (Optional)

https://github.com/wireapp/wire-android/assets/13151239/d9d52059-801c-4f24-b9c7-eb0b7ccb97db

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3639](https://10.10.124.134/job/AR-build-pipeline/3639/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9171707)(9171707)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9171707)(9171707)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Review by alexandreferris — APPROVED** [review]
looking great 👌🏻

**Comment by AndroidBob** [comment]
Build [3673](https://10.10.124.134/job/AR-build-pipeline/3673/) **failed**.

**Comment by AndroidBob** [comment]
Build [3677](https://10.10.124.134/job/AR-build-pipeline/3677/) **failed**.

**Comment by AndroidBob** [comment]
Build [3680](https://10.10.124.134/job/AR-build-pipeline/3680/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9206275)(9206275)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9206275)(9206275)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3686](https://10.10.124.134/job/AR-build-pipeline/3686/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9213284)(9213284)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9213284)(9213284)-staging-compat.apk)

**Pull request merged**
