### PR TITLE
feat: Show a dialog when current client's certificate is revoked (WPB-6145)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6145" title="WPB-6145" target="_blank">TaskWPB-6145</a>  [Android] Show Your Device's Cert Revoked
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

Once we discover that the certificate of current client is revoked we need to display we dialog that recommends to the user to logout and login again to get a new certificate

### Dependencies (Optional)

Needs https://github.com/wireapp/kalium/pull/2384

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

### Attachments (Optional)

[Screen_recording_20240118_105707.webm](https://github.com/wireapp/wire-android/assets/18124919/6dd91133-e875-4acb-94fb-335478b8d27e)

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2639](https://10.10.124.134/job/AR-build-pipeline/2639/) **failed**.

**Comment by AndroidBob** [comment]
Build [2640](https://10.10.124.134/job/AR-build-pipeline/2640/) **failed**.

**Comment by AndroidBob** [comment]
Build [2642](https://10.10.124.134/job/AR-build-pipeline/2642/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8661858)(8661858)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8661858)(8661858)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
LGTM

**Review by alexandreferris — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2748](https://10.10.124.134/job/AR-build-pipeline/2748/) **failed**.

**Comment by AndroidBob** [comment]
Build [2761](https://10.10.124.134/job/AR-build-pipeline/2761/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8729836)(8729836)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8729836)(8729836)-staging-compat.apk)

**Pull request merged**
