### PR TITLE
chore: remove github packages repository WPB-5028

### PR DESCRIPTION
**Pull request by typfel**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5028" title="WPB-5028" target="_blank">StoryWPB-5028</a>  upload core-crypto-multiplatform to sonatype via automation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Remove Github Packages repository since all dependencies are now on maven central.

### Dependencies

Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/2143

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by vitorhugods — CHANGES_REQUESTED** [review]
I guess it can also be removed from the `README.md` :) 

Awesome, awesome job :) 

Great step!

**Review by alexandreferris — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1362](https://10.10.124.134/job/AR-build-pipeline/1362/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7857918)(7857918)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7857918)(7857918)-staging-compat.apk)

**Comment by typfel** [comment]
> I guess it can also be removed from the `README.md` :)
> 
> Awesome, awesome job :)
> 
> Great step!

Updated the README (in kalium)

**Comment by AndroidBob** [comment]
Build [1385](https://10.10.124.134/job/AR-build-pipeline/1385/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7860726)(7860726)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7860726)(7860726)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Pull request merged**
