### PR TITLE
checks if the searched person is a team member or is connected

### PR DESCRIPTION
**Pull request by makingthematrix**
In the search list, if the user clicks on a contact, we now check if this person is a team member, or a contacted user. Only then we open the conversation window. Otherwise we open the connection request window.
Also AN-5435 fix: The "guest" label right to the contact appears now only if the contact is not a team member, but is a contacted user, when using the team account. Uncontacted users do not have this label.
#### APK
[Download build #9209](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9209/artifact/build/artifact/wire-dev-PR1008-9209.apk)
[Download build #9221](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9221/artifact/build/artifact/wire-dev-PR1008-9221.apk)
[Download build #9224](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9224/artifact/build/artifact/wire-dev-PR1008-9224.apk)
[Download build #9227](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9227/artifact/build/artifact/wire-dev-PR1008-9227.apk)
[Download build #9228](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9228/artifact/build/artifact/wire-dev-PR1008-9228.apk)
[Download build #9231](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9231/artifact/build/artifact/wire-dev-PR1008-9231.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
I'm not sure, if we need to show `team name` when we are listing `team members`
device-2017-07-12-135902
Waiting for Design review

**Comment by Yorgos-V** [comment]
Some more details about the Guests behaviour.

Guests are considered the people that:
**1. You are connected with them, but they are not members of the team**
They should appear in the Start UI in the same alphabetical list with your team-mates. A "Guest" label should distinguish those contacts with the rest.

**2. They are participating in a team conversation**
They must be connected to at least one of the team members that participates in this conversation.
For the team members, they are labeled as guests. Their avatar should behave as usual (b/w if not connected and colour if connected with this person). 
The guests are not allowed to add or remove people in a team conversation. Their participants view is the same as a normal group conversation.
There will be no guest indication of any 1:1 conversation in the List UI.

**Comment by Yorgos-V** [comment]
The title of the contacts list should simply be "CONTACTS"

**Comment by red-avtovo** [comment]
1) I should be able to search for guest
2) I should see an alphabetically sorted list of all my team mates + guests with the label  ```CONTACTS``` as @Yorgos-V mentioned

**Comment by makingthematrix** [comment]
We have a bug in local user search which sometimes (but not always) prevents us from searching among guests. We will work on that as a separate ticket.

**Comment by makingthematrix** [comment]
Bug fixed in SE

**Comment by red-avtovo** [comment]
Perfect! 👍

**Pull request merged**
