### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3647](https://10.10.124.134/job/AR-build-pipeline/3647/) **failed**.

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3653](https://10.10.124.134/job/AR-build-pipeline/3653/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9186850)(9186850)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9186850)(9186850)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3658](https://10.10.124.134/job/AR-build-pipeline/3658/) **failed**.

**Comment by AndroidBob** [comment]
Build [3676](https://10.10.124.134/job/AR-build-pipeline/3676/) **failed**.

**Comment by AndroidBob** [comment]
Build [3701](https://10.10.124.134/job/AR-build-pipeline/3701/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9214039)(9214039)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9214039)(9214039)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3730](https://10.10.124.134/job/AR-build-pipeline/3730/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9239913)(9239913)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9239913)(9239913)-staging-compat.apk)

**Pull request closed without merging**
