### PR TITLE
fix: animation not smooth when expanding a system message

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Animation not smooth when expanding a system message

### Causes (Optional)

Jumping state change

### Solutions

Replace `CrossFade` to use `animateContentSize` with custom animationSpec

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Remove more than 4 participants from a group to see that show all button

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

https://user-images.githubusercontent.com/18124919/217764730-c9f629d0-be52-45b6-b4a9-665212b9e621.mp4

https://user-images.githubusercontent.com/18124919/217764767-d2d78751-13c9-4316-adfa-07daef7f7740.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1442/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5696665)(5696665)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5696665)(5696665)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]
🦄🙌

**Review by saleniuk — APPROVED** [review]
✨

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1442/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5696911)(5696911)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5696911)(5696911)-staging-compat.apk)

**Pull request merged**
