### PR TITLE
feat: Display Read Receipts

### PR DESCRIPTION
**Pull request by alexandreferris**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

[AR-2682 - UI for Read Receipts list, in Message Details screen, only for SELF user](https://wearezeta.atlassian.net/browse/AR-2682)

### Issues

Read receipts were not being shown.

### Causes (Optional)

It was not implemented.

### Solutions

Add usage of retrieving read receipts usecase.

### Dependencies (Optional)

Needs releases with:

[ ] [feat: Retrieve Read Receipts #1164 - Kalium](https://github.com/wireapp/kalium/pull/1164)

#### How to Test

Currently the unique way to test is to change code and add dummy participants as the implementation to save the read messages is not done yet.

### Notes

When this is reviewed, we need to update kalium reference to latest develop correctly and only then merge this ticket.

### Attachments (Optional)

<br>

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1200/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5092085)(5092085)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5092085)(5092085)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1200/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5092904)(5092904)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5092904)(5092904)-dev-release.apk)

**Review by vitorhugods — APPROVED** [review]
👨🏼‍🍳🤌🏻

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1200/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5094229)(5094229)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5094229)(5094229)-dev-release.apk)

**Pull request merged**
