### PR TITLE
fix: Refresh search result in onResume (AR-2303)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2303" title="AR-2303" target="_blank">BugAR-2303</a>  Cancelling connection request from New conversation list does not update the request state
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

SerachUser result was not updating when user returns from some other screen (OtherUserProfile e.g.)

### Causes (Optional)

there was no refreshing for such case

### Solutions

Add refreshing in case when user comes back to the SearchResult screen from some other.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-940/1/) **failed**.

**Review by trOnk12 — APPROVED** [review]
personally I think doing it on Kalium would be better, but this works too 🥇

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-940/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4358357)(4358357)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4358357)(4358357)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-940/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4358447)(4358447)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4358447)(4358447)-dev-release.apk)

**Pull request merged**
