### PR TITLE
fix(rc): attachment options not appearing on android 8 [AR-3033]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3033" title="AR-3033" target="_blank">BugAR-3033</a>  Applause: [SG S7 Edge/Android 8.0] Chat - Button to send files, etc. does not respond at all
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Copy of https://github.com/wireapp/wire-android-reloaded/pull/1612

Attachment options does not appear after clicking on the "+" button, only the button being highlighted.

### Causes (Optional)

On some Android versions, `WindowInsets.isImeVisible` returns always `true` for some reasons. 

### Solutions

Raise the version that uses the "old" version of checking the keyboard visibility and height from up to Android 7 to up to Android 8.1.

#### How to Test

Open the conversation on Android 8 and try to open the attachment options.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1613/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6129582)(6129582)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6129582)(6129582)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]
Good catch

**Review by alexandreferris — APPROVED** [review]
Great finding! Tested on my Android 8 where I had this issue and can confirm its fixed now 🙌🏻

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1613/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6162643)(6162643)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6162643)(6162643)-staging-compat.apk)

**Pull request merged**
