### PR TITLE
fix: group navigation crashes [AR-2589] [AR-2588]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2589" title="AR-2589" target="_blank">BugAR-2589</a>  app crashing on some devices after group was deleted or when trying to add a member to a group conversation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

There were two another instances of `java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels after the NavBackStackEntry is destroyed` found in the app during the navigation after actions related to groups: after adding another members or after deleting the group.

### Causes (Optional)

There was a race condition with navigating home after deleting the group, in some cases unnecessary recompositions was being executed, maybe because we have `AnimatedNavHost` (comment from that one: "AnimatedContent can contain an entry that is no longer part of visible entries since it was cleared from the back stack").

### Solutions

These changes were made, some of them are actual fixes, others are in hope that they would also improve the reliability of navigation:
- removed unnecessary `NavHost` from `SearchPeopleContent` and replaced with simple `Crossfade`
- fixed race condition with navigating back/home after group deletion when there is no group data anymore
- moved injecting `ViewModel` directly in `NavigationItem` to the child `Composable`
- some state parameter classes marked as `@Stable`
- some collection parameters changed to be immutable ones
- removed unused `scrollPositionProvider` from `SearchBarState`
- revised `Clickable` and `WireButton` to update click lambda not only when `blockUntilSynced` changes

#### How to Test

Try to delete a group or add a member, on some devices that can result in a crash.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4728947)(4728947)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4728947)(4728947)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4730603)(4730603)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4730603)(4730603)-dev-release.apk)

**Review by trOnk12 — APPROVED** [review]
well done and thanks for higlighting NavHost problems during the collective <3

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1105/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4737333)(4737333)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4737333)(4737333)-dev-release.apk)

**Pull request merged**
