### PR TITLE
fix: Update conversation data in context menu when it was changed (AR-2491)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2491" title="AR-2491" target="_blank">BugAR-2491</a>  Handle incremental update users events
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

Conversation name was not updating in context menu (while it's opened) when the name was changed

### Causes (Optional)

The whole conversation data was fetching once and wasn't observed for that menu.

### Solutions

- Make ConversationData Observable (changes in `kalium`)
- add the ability to update that data in bottomSheet menus 

### Dependencies (Optional)

Waiting for [kalium changes](https://github.com/wireapp/kalium/pull/1136) be merged

### Attachments (Optional)

https://user-images.githubusercontent.com/6539347/202487336-41da8dac-9ab7-4174-8cb0-daf60239ba6e.mp4

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4980775)(4980775)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4980775)(4980775)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5006995)(5006995)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5006995)(5006995)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5007438)(5007438)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5007438)(5007438)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
🪁

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5013408)(5013408)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5013408)(5013408)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1167/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5014111)(5014111)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5014111)(5014111)-dev-release.apk)

**Pull request merged**
