### PR TITLE
fix: Ongoing calls shouldn't get triggered after some time

### PR DESCRIPTION
**Pull request by JPonte**
Bump SE to: https://github.com/wireapp/wire-android-sync-engine/pull/441
fixes: https://github.com/wireapp/android-project/issues/280
#### APK
[Download build #11888](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11888/artifact/build/artifact/wire-dev-PR1846-11888.apk)
[Download build #11948](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11948/artifact/build/artifact/wire-dev-PR1846-11948.apk)
[Download build #11953](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11953/artifact/build/artifact/wire-dev-PR1846-11953.apk)
[Download build #11976](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11976/artifact/build/artifact/wire-dev-PR1846-11976.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
Bug 1:
Rejected group call never happens on the phone. Even if it is a new one

**Comment by red-avtovo** [comment]
Bug 1:
Rejected group call never happens on the phone. Even if it is a new one

**Comment by JPonte** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by red-avtovo** [comment]
lgtm

**Pull request merged**
