### PR TITLE
ci: support multi app builds on Jenkins

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

atm Jenkins support bulking only one app

### Solutions

- have dev flavor for PRs
- have staging and dev flavor for each build being created when a merge to develop happened

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/7/) **failed**.

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/12/) **failed**.

**Comment by AndroidBob** [comment]
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/13/) **failed**.

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/16/) **failed**.

**Comment by AndroidBob** [comment]
Build [25](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/25/) **failed**.

**Comment by AndroidBob** [comment]
Build [28](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/28/) **failed**.

**Comment by AndroidBob** [comment]
Build [29](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/29/) **failed**.

**Comment by AndroidBob** [comment]
Build [30](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/30/) **failed**.

**Comment by AndroidBob** [comment]
Build [31](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/31/) **failed**.

**Comment by AndroidBob** [comment]
Build [34](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/34/) **failed**.

**Comment by AndroidBob** [comment]
Build [36](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/36/) **failed**.

**Comment by AndroidBob** [comment]
Build [37](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/37/) **failed**.

**Comment by AndroidBob** [comment]
Build [38](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/38/) **failed**.

**Comment by AndroidBob** [comment]
Build [39](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/39/) **failed**.

**Comment by AndroidBob** [comment]
Build [40](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/40/) **failed**.

**Comment by AndroidBob** [comment]
Build [41](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/41/) **failed**.

**Comment by AndroidBob** [comment]
Build [42](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/42/) **failed**.

**Comment by AndroidBob** [comment]
Build [43](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/43/) **succeeded**.

StagingCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6301955)(6301955)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6301955)(6301955)-staging-compat.apk)
DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6301955)(6301955)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6301955)(6301955)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [45](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/45/) **succeeded**.

StagingCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6302159)(6302159)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6302159)(6302159)-staging-compat.apk)
DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6302159)(6302159)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6302159)(6302159)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [46](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/46/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6302878)(6302878)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6302878)(6302878)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [47](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/47/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6354934)(6354934)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6354934)(6354934)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [48](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/48/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6363503)(6363503)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6363503)(6363503)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [49](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/49/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6458483)(6458483)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6458483)(6458483)-dev-compat.apk)

**Review by vitorhugods — COMMENTED** [review]
I feel like this scale more easily if instead of just changing one job to build two artifacts, we could run two jobs (one for each artifact).

For example, using Jenkins' Pipeline:

```groovy
stage ('Trigger builds') {
    parallel {
        stage('Build Dev') {
            build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'dev']]
        }
        stage('Build Staging') {
            build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'staging']]
        }
    }
}
```

And in Jenkins we define the `BuildReloaded` job to do what we need.

This way we can re-use jobs or parts of it.

Even do it dynamically I guess:

```groovy
stage ('Trigger builds') {
    parallel {
        // Define flavorList based on branch name, etc.
        for(flavor in flavorList) {
            stage("Build $flavor") {
                build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: flavor]]
            }
        }
    }
}
```


This way we could make the same "build" job.

But leaving the logic to figure out the parameters outside of it.
On `main` it does one thing. On PRs it does another. On tags it does another.

**Comment by MohamadJaara** [comment]
> I feel like this scale more easily if instead of just changing one job to build two artifacts, we could run two jobs (one for each artifact).
> 
> For example, using Jenkins' Pipeline:
> 
> ```groovy
> stage ('Trigger builds') {
>     parallel {
>         stage('Build Dev') {
>             build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'dev']]
>         }
>         stage('Build Staging') {
>             build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'staging']]
>         }
>     }
> }
> ```
> 
> And in Jenkins we define the `BuildReloaded` job to do what we need.
> 
> This way we can re-use jobs or parts of it.
> 
> Even do it dynamically I guess:
> 
> ```groovy
> stage ('Trigger builds') {
>     parallel {
>         // Define flavorList based on branch name, etc.
>         for(flavor in flavorList) {
>             stage("Build $flavor") {
>                 build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: flavor]]
>             }
>         }
>     }
> }
> ```
> 
> This way we could make the same "build" job.
> 
> But leaving the logic to figure out the parameters outside of it. On `main` it does one thing. On PRs it does another. On tags it does another.

that was my first approach is to detect the builds needed and dynamically start parallel stages to build assemble the needed apps, the issue with this is Gradle did not like  having 2 assemble commands running at the same time.

**Comment by vitorhugods** [comment]
> 



> > I feel like this scale more easily if instead of just changing one job to build two artifacts, we could run two jobs (one for each artifact).
> > For example, using Jenkins' Pipeline:
> > ```groovy
> > stage ('Trigger builds') {
> >     parallel {
> >         stage('Build Dev') {
> >             build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'dev']]
> >         }
> >         stage('Build Staging') {
> >             build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: 'staging']]
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And in Jenkins we define the `BuildReloaded` job to do what we need.
> > This way we can re-use jobs or parts of it.
> > Even do it dynamically I guess:
> > ```groovy
> > stage ('Trigger builds') {
> >     parallel {
> >         // Define flavorList based on branch name, etc.
> >         for(flavor in flavorList) {
> >             stage("Build $flavor") {
> >                 build job: 'BuildReloaded', parameters: [[$class: 'StringParameterValue', name: 'flavor', value: flavor]]
> >             }
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way we could make the same "build" job.
> > But leaving the logic to figure out the parameters outside of it. On `main` it does one thing. On PRs it does another. On tags it does another.
> 
> that was my first approach is to detect the builds needed and dynamically start parallel stages to build assemble the needed apps, the issue with this is Gradle did not like having 2 assemble commands running at the same time.

That's the thing. By triggering actual _jobs_ in parallel, they run each on their own Jenkins workspace.
I'm not talking about running `./gradlew` commands in parallel. But actually delegating the build to another Jenkins job, or jobs.

**Comment by AndroidBob** [comment]
Build [50](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/50/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6674766)(6674766)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6674766)(6674766)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [51](https://10.10.124.134/job/wire-android-reloaded/job/PR-1689/51/) **succeeded**.

DevCompat produced the following APK's:
- [com.wire.android-vv4.2.0(6725906)(6725906)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.2.0(6725906)(6725906)-dev-compat.apk)

**Pull request closed without merging**
