### PR TITLE
fix: RC Doubled notification for attachment message

### PR DESCRIPTION
**Pull request by borichellow**
The same PR like https://github.com/wireapp/wire-android-reloaded/pull/1285 but for release candidate

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1309/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5438419)(5438419)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5438419)(5438419)-dev-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1309/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1309/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5524557)(5524557)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5524557)(5524557)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1309/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5524658)(5524658)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5524658)(5524658)-dev-compat.apk)

**Pull request merged**
