### PR TITLE
Added pull request template

### PR DESCRIPTION
**Pull request by vytis**
### Issues

Sometimes new pull requests could use more context. This helps new people to have more visibility on what is happening and also captures more information when looking through git blame.

### Solutions

Added a template that will be filled in to all newly opened PRs.

## Notes

An identical PR was opened for sync engine - https://github.com/wireapp/wire-android-sync-engine/pull/500
#### APK
[Download build #12420](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12420/artifact/build/artifact/wire-dev-PR2027-12420.apk)
[Download build #12421](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12421/artifact/build/artifact/wire-dev-PR2027-12421.apk)

### CODE REVIEW

**Comment by vytis** [comment]
@marcoconti83 what do you think should be in testing section? What parts of the app are affected by this and should be tested? or what tests were added?

**Comment by marcoconti83** [comment]
There are large parts of the app that, with the current architecture, are practically un-testable. Until we get around reworking those parts, it would be very relevant to know if the pull request includes no tests on purpose (so how was it tested then? manually?) or if the author forgot to include/perform the tests. In the second case I would point this out in the review. 

See for example https://github.com/wireapp/wire-android/pull/2000 https://github.com/wireapp/wire-android/pull/1992 https://github.com/wireapp/wire-android/pull/1989

**Comment by vytis** [comment]
@marcoconti83 updated

**Comment by marcoconti83** [comment]
Thanks @vytis !

**Pull request merged**
