### PR TITLE
refactor: Remove old code dealing with v2 assets (FS-293)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-293" title="FS-293" target="_blank">StoryFS-293</a>  [Android] As a user, I like to share pictures with members from federated backends
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/FS-293

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow
  - [x] contains a reference JIRA issue number
  - [x] answers the question: _If merged, this PR will: ..._

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

As a preparation for work on federated assets, this PR removes the old code for v2 assets.

### Solutions

Everything should work as before.

### Testing

Unit tests 

#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/5/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/7/)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/11/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/13/)

**Comment by AndroidBob** [comment]
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/12/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3639/14/)

**Pull request merged**
