### PR TITLE
feat(AppLock): Adjust appLock to be handled correctly with other features (WPB-4691)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4691" title="WPB-4691" target="_blank">StoryWPB-4691</a>  Notifications when App lock is on
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

When app is locked, the unlock screen will be displayed when:
- we interact with a notification(click on it, reply to a message, answer a call)
- we try to join a group using guest links
- use deep links
- share something from different app to Wire

For this, I moved app lock feature to be in a separate activity, this way it will be displayed on top of WireActivity screen without interfering with app navigation.

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Lock the app and different things like calling join conversation using deep links etc..

### Attachments (Optional)

In this recording, We show how the app behaves when clicking on reply from notification:
When app is locked we will show unlock screen and user will be redirected to conversation to reply
When it's not locked, user can reply directly from notification

https://github.com/wireapp/wire-android-reloaded/assets/18124919/d1ed5ed4-a1c5-4539-9ac2-6776818f8740

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1484](https://10.10.124.134/job/AR-build-pipeline/1484/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7910485)(7910485)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7910485)(7910485)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1504](https://10.10.124.134/job/AR-build-pipeline/1504/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7917959)(7917959)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7917959)(7917959)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1601](https://10.10.124.134/job/AR-build-pipeline/1601/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7979150)(7979150)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7979150)(7979150)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1609](https://10.10.124.134/job/AR-build-pipeline/1609/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7986725)(7986725)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7986725)(7986725)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1618](https://10.10.124.134/job/AR-build-pipeline/1618/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7987537)(7987537)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7987537)(7987537)-staging-compat.apk)

**Pull request merged**
