### PR TITLE
fix: The conversation list stops being updated

### PR DESCRIPTION
**Pull request by makingthematrix**
### What's new in this PR?

Changes to how signals are handles in `ConversationListManagerFragment` and `ConversationListFragment`

### Issues

https://wearezeta.atlassian.net/browse/AN-6503

### Causes

After recent changes the subscriptions to signals were destroyed too early and never renewed. This PR fixes that.

### Testing

Go to the main fragment. Switch a few times between the list and folders view. Add a new conversation. Switch again.
The bug caused that the new conversation never appears, the name of the user in the header disappears after switching, and sometimes the whole conversation list disappears as well.

#### APK
[Download build #343](http://10.10.124.11:8080/job/Pull%20Request%20Builder/343/artifact/build/artifact/wire-dev-PR2412-343.apk)

### CODE REVIEW

**Comment by makingthematrix** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Comment by gizemb** [comment]
build again

**Comment by gizemb** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Comment by marcoconti83** [comment]
build again

**Pull request merged**
