### PR TITLE
[AN-5837] Clear signin controller when going to the insert password stage

### PR DESCRIPTION
**Pull request by JPonte**
#### APK
[Download build #9953](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9953/artifact/build/artifact/wire-dev-PR1327-9953.apk)
[Download build #9955](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9955/artifact/build/artifact/wire-dev-PR1327-9955.apk)
[Download build #10007](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10007/artifact/build/artifact/wire-dev-PR1327-10007.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by someoneEsle** [comment]
Bug 1
Try to log in with invalid email/password
Log in with legit phone number
Type the code
Now the email field is prefilled correctly, but the password is also there (it's what you typed in step 1)

**Comment by someoneEsle** [comment]
build again

**Pull request merged**
