### PR TITLE
feat: initial sync loading screen [AR-2561]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2561" title="AR-2561" target="_blank">StoryAR-2561</a>  Add loading screen while conversations are synching
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When we first login into the app, the sync can take some more time, also there are empty placeholder shown instead of real conversations so in order to avoid that and show user that the app needs some time to sync all data, we should show one-time loading screen.

### Solutions

Add `InitialSyncScreen` which is shown after login or account creation and observes the sync state changes.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Fresh install the app and log in.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1160/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1160/3/) **failed**.

**Review by borichellow — APPROVED** [review]
looks cool, nice one! 🤟👍

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1160/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4957368)(4957368)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4957368)(4957368)-dev-release.apk)

**Pull request merged**
