### PR TITLE
fix: disable back press when app lock team enforced (WPB-5644)

### PR DESCRIPTION
**Pull request by alexandreferris**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5644" title="WPB-5644" target="_blank">BugWPB-5644</a>  [Android] Back button bypasses applock screen when it is forced
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When AppLock is enforced by team, it was able to press back button (either hardware or app button) and navigate back in the screen and use the app normally until next closing/opening app and being prompted with setting app lock password.

### Solutions

When AppLock is enforced by team, hide back button on app and disable back button on screen.
Functionalities remain the same when it is not enforced by team but user wants to set AppLock.

#### How to Test

- Open App
- Receive AppLock enforced by team dialog
- on Set AppLock password screen
- make sure back button is hidden (top left) + hardware back button has no effect.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2028](https://10.10.124.134/job/AR-build-pipeline/2028/) **failed**.

**Review by MohamadJaara — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2037](https://10.10.124.134/job/AR-build-pipeline/2037/) **failed**.

**Comment by AndroidBob** [comment]
Build [2057](https://10.10.124.134/job/AR-build-pipeline/2057/) **failed**.

**Comment by AndroidBob** [comment]
Build [2058](https://10.10.124.134/job/AR-build-pipeline/2058/) **failed**.

**Comment by AndroidBob** [comment]
Build [2073](https://10.10.124.134/job/AR-build-pipeline/2073/) **failed**.

**Pull request merged**
