### PR TITLE
feat: Notifications: A missed call notification (SQCORE-1180)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1180" title="SQCORE-1180" target="_blank">SubtaskSQCORE-1180</a>  [Android] The missed call notification
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/SQCORE-1180

This is a corner case. When the user misses a call, we should display a notification about it.
But all other notifications come to us from the backend - messages, pings, likes, user connection
requests, etc. This one is local. We should create it as a response to a callback from AVS saying
that the call was missed. But because there is no event, and only that callback, we need another
way of making the notifications system aware that such a notification should be created.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/6/)

**Comment by AndroidBob** [comment]
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/7/)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/9/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3614/10/)

**Pull request merged**
