### PR TITLE
feat: welcome to new android (AR-2118)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2118" title="AR-2118" target="_blank">StoryAR-2118</a>  Welcome to New Android - information to users when they just installed it
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

After run a migration, we want to display for old users a brief information (only once) about what's new in the new version.

### Causes (Optional)

Displays a dialog only once after run the migration process.

### Solutions

Creates a flag, that will be read on first open, to identify if we need to display the info dialog or not to a migrated users.
For example, new users will not have this info.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Install the Scala app, then install on top the new version and see the dialog displayed.

### Attachments (Optional)

https://user-images.githubusercontent.com/5806454/203037969-eb44e254-abb3-4c97-95db-be21da38d42d.mov

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1173/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5006316)(5006316)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5006316)(5006316)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM 🚀

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1173/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5006509)(5006509)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5006509)(5006509)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1173/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5006946)(5006946)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5006946)(5006946)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1173/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5007552)(5007552)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5007552)(5007552)-dev-release.apk)

**Pull request merged**
