### PR TITLE
chore: New Crowdin updates (AN-7152)

### PR DESCRIPTION
**Pull request by AndroidBob**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AN-7152" title="AN-7152" target="_blank">StoryAN-7152</a>  Crowdin Translations
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/AN-7152

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/7/)

**Review by makingthematrix — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/8/)

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/9/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3622/12/)

**Pull request merged**
