### PR TITLE
fix: Localised DateFormat in device info

### PR DESCRIPTION
**Pull request by AndroidBob**
Cherry pick from the original PR: 
- #2783

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

# What's new in this PR?

### Issues

Devices screen - Time and date format not respecting locale

### Causes (Optional)

Was not implemented

### Solutions

implement it

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3546](https://10.10.124.134/job/AR-build-pipeline/3546/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9126964)(9126964)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9126964)(9126964)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3558](https://10.10.124.134/job/AR-build-pipeline/3558/) **failed**.

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3566](https://10.10.124.134/job/AR-build-pipeline/3566/) **failed**.

**Comment by AndroidBob** [comment]
Build [3571](https://10.10.124.134/job/AR-build-pipeline/3571/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9130666)(9130666)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9130666)(9130666)-staging-compat.apk)

**Pull request merged**
