### PR TITLE
fix: DEV open conversation on notification tap

### PR DESCRIPTION
**Pull request by borichellow**
Copy of PR https://github.com/wireapp/wire-android-reloaded/pull/1419

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1420/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1420/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1420/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1420/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5648774)(5648774)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5648774)(5648774)-staging-compat.apk)

**Pull request merged**
