### PR TITLE
[AN-4928] Unify the tools menus in conversation and collection

### PR DESCRIPTION
**Pull request by JPonte**
#### APK
[Download build #8328](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8328/artifact/build/artifact/wire-dev-PR527-8328.apk)
[Download build #8373](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8373/artifact/build/artifact/wire-dev-PR527-8373.apk)
[Download build #8377](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8377/artifact/build/artifact/wire-dev-PR527-8377.apk)
[Download build #8379](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8379/artifact/build/artifact/wire-dev-PR527-8379.apk)
[Download build #8398](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8398/artifact/build/artifact/wire-dev-PR527-8398.apk)

### CODE REVIEW

**Comment by xuanzhaopeng** [comment]
No pr could download

**Comment by JPonte** [comment]
build again

**Comment by xuanzhaopeng** [comment]
@JPonte , in spec: 
> Combine Delete into on item that depending on the sender of the asset asks whether to delete for yourself or for everyone, in the case of a remote sender, if you are the sender there should just be Delete that deletes for youself
the feature not only in collection, but also in Conversation

**Comment by red-avtovo** [comment]
Everything works, according to spec

**Pull request merged**
