### PR TITLE
Mentions

### PR DESCRIPTION
**Pull request by JPonte**
A simple suggestions list on the conversation cursor
#### APK
[Download build #11671](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11671/artifact/build/artifact/wire-dev-PR1787-11671.apk)
[Download build #11673](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11673/artifact/build/artifact/wire-dev-PR1787-11673.apk)
[Download build #11680](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11680/artifact/build/artifact/wire-dev-PR1787-11680.apk)
[Download build #11681](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11681/artifact/build/artifact/wire-dev-PR1787-11681.apk)
[Download build #11695](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11695/artifact/build/artifact/wire-dev-PR1787-11695.apk)
[Download build #11698](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11698/artifact/build/artifact/wire-dev-PR1787-11698.apk)
[Download build #11699](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11699/artifact/build/artifact/wire-dev-PR1787-11699.apk)
[Download build #11700](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11700/artifact/build/artifact/wire-dev-PR1787-11700.apk)
[Download build #11701](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11701/artifact/build/artifact/wire-dev-PR1787-11701.apk)
[Download build #11702](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11702/artifact/build/artifact/wire-dev-PR1787-11702.apk)
[Download build #11703](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11703/artifact/build/artifact/wire-dev-PR1787-11703.apk)
[Download build #11704](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11704/artifact/build/artifact/wire-dev-PR1787-11704.apk)
[Download build #11705](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11705/artifact/build/artifact/wire-dev-PR1787-11705.apk)
[Download build #11706](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11706/artifact/build/artifact/wire-dev-PR1787-11706.apk)
[Download build #11708](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11708/artifact/build/artifact/wire-dev-PR1787-11708.apk)
[Download build #11713](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11713/artifact/build/artifact/wire-dev-PR1787-11713.apk)
[Download build #11718](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11718/artifact/build/artifact/wire-dev-PR1787-11718.apk)
[Download build #11719](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11719/artifact/build/artifact/wire-dev-PR1787-11719.apk)
[Download build #11721](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11721/artifact/build/artifact/wire-dev-PR1787-11721.apk)
[Download build #11726](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11726/artifact/build/artifact/wire-dev-PR1787-11726.apk)
[Download build #11727](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11727/artifact/build/artifact/wire-dev-PR1787-11727.apk)
[Download build #11729](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11729/artifact/build/artifact/wire-dev-PR1787-11729.apk)
[Download build #11730](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11730/artifact/build/artifact/wire-dev-PR1787-11730.apk)
[Download build #11731](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11731/artifact/build/artifact/wire-dev-PR1787-11731.apk)
[Download build #11732](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11732/artifact/build/artifact/wire-dev-PR1787-11732.apk)
[Download build #11733](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11733/artifact/build/artifact/wire-dev-PR1787-11733.apk)
[Download build #11735](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11735/artifact/build/artifact/wire-dev-PR1787-11735.apk)
[Download build #11736](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11736/artifact/build/artifact/wire-dev-PR1787-11736.apk)
[Download build #11737](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11737/artifact/build/artifact/wire-dev-PR1787-11737.apk)
[Download build #11738](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11738/artifact/build/artifact/wire-dev-PR1787-11738.apk)
[Download build #11739](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11739/artifact/build/artifact/wire-dev-PR1787-11739.apk)
[Download build #11740](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11740/artifact/build/artifact/wire-dev-PR1787-11740.apk)
[Download build #11742](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11742/artifact/build/artifact/wire-dev-PR1787-11742.apk)
[Download build #11743](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11743/artifact/build/artifact/wire-dev-PR1787-11743.apk)
[Download build #11744](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11744/artifact/build/artifact/wire-dev-PR1787-11744.apk)
[Download build #11746](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11746/artifact/build/artifact/wire-dev-PR1787-11746.apk)
[Download build #11747](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11747/artifact/build/artifact/wire-dev-PR1787-11747.apk)
[Download build #11748](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11748/artifact/build/artifact/wire-dev-PR1787-11748.apk)
[Download build #11749](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11749/artifact/build/artifact/wire-dev-PR1787-11749.apk)
[Download build #11750](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11750/artifact/build/artifact/wire-dev-PR1787-11750.apk)
[Download build #11757](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11757/artifact/build/artifact/wire-dev-PR1787-11757.apk)
[Download build #11759](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11759/artifact/build/artifact/wire-dev-PR1787-11759.apk)
[Download build #11760](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11760/artifact/build/artifact/wire-dev-PR1787-11760.apk)
[Download build #11761](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11761/artifact/build/artifact/wire-dev-PR1787-11761.apk)
[Download build #11762](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11762/artifact/build/artifact/wire-dev-PR1787-11762.apk)
[Download build #11763](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11763/artifact/build/artifact/wire-dev-PR1787-11763.apk)
[Download build #11765](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11765/artifact/build/artifact/wire-dev-PR1787-11765.apk)
[Download build #11766](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11766/artifact/build/artifact/wire-dev-PR1787-11766.apk)
[Download build #11768](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11768/artifact/build/artifact/wire-dev-PR1787-11768.apk)
[Download build #11772](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11772/artifact/build/artifact/wire-dev-PR1787-11772.apk)
[Download build #11774](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11774/artifact/build/artifact/wire-dev-PR1787-11774.apk)
[Download build #11777](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11777/artifact/build/artifact/wire-dev-PR1787-11777.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Can't mention someone whose name starts with @

**Comment by someoneEsle** [comment]
- [ ] Bug 2
I should not see suggestions list if I type @ after a symbol

**Comment by someoneEsle** [comment]
- [ ] Bug 4
Mention someone (don't send). Drag the text cursor to the middle of the @mention. The cursor on my S8 switches like crazy between the beginning of the word and the middle of the word

**Comment by someoneEsle** [comment]
- [ ] Bug 5
Mention someone (don't send). Lock the screen, unlock the screen. The mention is gone

**Comment by someoneEsle** [comment]
- [ ] Bug 6
Type:
"@mention a b c"
where @mention is the mention of one of the participants. Now double tap on "c" as to select it (blue background, the options to share/copy should come up). Now try to expand this blue selection to the left towards the mention. Once the mention is selected, the rest of the string will lose the selection.

(I can show you this in person if this explanation is not clear enough)

**Comment by someoneEsle** [comment]
- [ ] Bug 7
Type a mention (don't send). Copy it, paste it. The new pasted mention is highlighted, however when I tap it I see the suggestions list and I have to confirm it

**Comment by someoneEsle** [comment]
- [ ] Bug 8
Long tapping a mention should not open the mentioned user's profile

- [ ] Bug 9
Tap a mention. The user's profile opens. Now tap back. You should go back to the conversation view.

**Comment by someoneEsle** [comment]
- [ ] Bug 10
If I write 2 mentions, the first one will have the @ in bold

**Comment by someoneEsle** [comment]
- [ ] Bug 11
Not sure why/how to reproduce, but very often I don't see any suggestions when I type "@", and I have to kill the app for it to work

**Comment by someoneEsle** [comment]
- [ ] Bug 12
Type "@mention a b c". Select @mention, being careful to *not* select "a b c". Now tap copy. Paste. "a b c" are somehow pasted as well

**Comment by someoneEsle** [comment]
- [ ] Bug 13
I do not find "Müller" when searching for "mueller". C722985

**Comment by someoneEsle** [comment]
- [ ] Bug 13
When I type @**LastName I can match the last name of the user I'm trying to mention, but when I type @**uniqueusername I can't. To be honest I think we shouldn't match in either case, but anyway it should be consistent (maybe ask design what the behavior should be).

**Comment by someoneEsle** [comment]
- [ ] Bug 14
Ephemeral mentions are not handled in notifications (they look no different than a regular ephemeral message)

**Comment by someoneEsle** [comment]
- [ ] Bug 17
I should not see any suggestion if I type @ in a group where I'm the only participant

**Comment by someoneEsle** [comment]
- [ ] note to self: test dark theme and backup

**Comment by someoneEsle** [comment]
- [ ] Bug 18
Type a mention. Write a long message afterwards. Send. There is a very big space between the lines of the message you sent.

**Comment by someoneEsle** [comment]
- [ ] Bug 19
I should not be able to mention wireless guests

**Comment by jennifergoertzen** [comment]
Moved M1.2 to In Progress: List should be in reverse alphabetical order. Most relevant results should appear at the bottom of the list.

**Comment by someoneEsle** [comment]
- [ ] Bug 20
There is group chat G with A, B, C. I am A. B mentions C. B removes C from the group chat. I tap C's mention. An empty profile opens

**Comment by jennifergoertzen** [comment]
Moved 1.2.1 to In Progress: Temporary guests appearing the suggestions popup should have an indication that they are guests (time remaining and guest icon).

**Comment by someoneEsle** [comment]
- [ ] Bug 20
Sometimes tapping a mention closes the app. Not sure why yet.

**Comment by someoneEsle** [comment]
- [ ] Bug 21
Receive a mention and a normal message in a conversation. Subtitle says "1 mention, 2 new messages" but it should say "1 mention, 1 new message"

**Comment by jennifergoertzen** [comment]
Can we centre the @ button in the action bar? Right now it appears lower than all other icons.

**Comment by someoneEsle** [comment]
- [ ] Bug 22
Receive an ephemeral mention in a group. Subtitle in the conversations list says "<SenderName>: Someone mentioned you". <SenderName> should not be there.

**Comment by someoneEsle** [comment]
- [ ] Bug 23
Receive a message in a 1:1 team conversation. Right now the subtitle in the conversations list says "<senderName>: <messageContent>", but <senderName> should not be there.

**Comment by someoneEsle** [comment]
- [ ] Bug 25
(not introduced with this PR so not blocking it, but worth looking into since you've changed some of this code)
Long tapping on a message does not work if you have the keyboard open (it just closes the keyboard but doesn't open the menu)

**Comment by someoneEsle** [comment]
- [ ] Bug 26
Type "www.wire.com/", add a space, add "@mention", then delete the space between the link and the mention. Send. Now you should be able to tap both the mention and the link, and they should behave accordingly (the link shouldn't take you to a website that is the combination of the link and the mention, and tapping the mention should open the profile of the person).

**Comment by someoneEsle** [comment]
- [ ] Bug 27
Mentions to myself in dark theme are not highlighted properly. The background color is barely visible

**Comment by someoneEsle** [comment]
- [ ] Bug 28
The subtitles in the conversations list should follow this order: Mentions, missed calls, pings, messages. Currently we display messages before missed calls, which is not correct. Also, we should display the glyph of the most important event (unless the conversation is muted), not the glyph of the most recent event.

**Comment by someoneEsle** [comment]
- [ ] Bug 29
When I receive two messages from any unmuted conversation, the subtitle in the conversations list should display the last message (plus the sender, if it's a group conversation). It should only say "2 new messages" if the conversation is muted

**Comment by someoneEsle** [comment]
- [ ] Bug 30
Alphabetical order in the suggestions list should not be case sensitive

**Comment by jennifergoertzen** [comment]
Moving M1.7 back because mentions aren't highlighted in notifications.

**Pull request merged**
