### PR TITLE
Notifications: Display the messages as notifications on the device's screen (SQCORE-1141)

### PR DESCRIPTION
**Pull request by makingthematrix**
https://wearezeta.atlassian.net/browse/SQCORE-1141

The list of notification types we should display comes from [here](https://docs.google.com/spreadsheets/d/1k_0kcSwtTKgAjgvccpY9k3MihHaO1meQVaZbWDxs6Gk/edit#gid=0).

[x] Preparation work for displaying notifications
[x] A text notification
[x] An asset 
[x] A video
[x] A ping
[x] A mention
[x] A link
[x] A location
[x] A reply
[x] A like
[x] An ephemeral message
[x] A composite message
[x] A call 
[x] A connection request
[x] The acceptance of my connection request
[x] A deletion of a group conversation
[x] A renaming of a group conversation

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/4/)

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/5/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/6/)

**Comment by AndroidBob** [comment]
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/7/)

**Comment by AndroidBob** [comment]
Build Failure
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/8/)

**Comment by AndroidBob** [comment]
Build Failure
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/9/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/12/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/13/)

**Comment by AndroidBob** [comment]
Build Failure
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/14/)

**Comment by AndroidBob** [comment]
Build Failure
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/15/)

**Comment by AndroidBob** [comment]
Build Failure
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/17/)

**Review by mdimjasevic — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3606/2/)

**Pull request merged**
