### PR TITLE
feat: Show conversation Proteus verification status

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

### Issues

When the conversation is "Proteus verified" user should know about it: corresponding icon next to the conversation name and systemMessage in a conversation + systemMessage when the conversation becomes Degraded (was verified in past but not anymore).

Needs releases with:

- wireapp/kalium/pull/2157

#### How to Test

1. 
- open some users profile
- go to Devices tab
- verify all the devices of the user
- go to the conversation with that user
expected result: 
there should be a system message informing that conversation is Verified now + blue shield icon is next to the user name 
- go to the Conversations List screen 
expected: 
blue shield icon is next to the user name and second line in conversation item is SystemMessage

2. 
- open some group conversation
- verify all the devices of all the users in that group (see the prev. test)
- go to that conversation
expected result: 
there should be a system message informing that conversation is Verified now + blue is next to the conversation name
- go to the Conversations List screen 
expected: 
blue shield icon is next to the conversation name and second line in conversation item is SystemMessage

3. 
- do all from test-2
- un-verify at least 1 device of 1 user
- go to that conversation
expected result: 
there should be a system message informing that conversation is NOT Verified anymore + NO blue is next to the conversation name
- go to the Conversations List screen 
expected: 
NO blue shield is next to the conversation name and second line in conversation item is SystemMessage

### Attachments (Optional)

Screenshot 2023-10-27 at 11 40 09

Screenshot 2023-10-27 at 11 40 21

Screenshot 2023-10-19 at 17 59 17

Screenshot 2023-10-19 at 17 59 53

Screenshot 2023-10-19 at 17 59 35

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1435](https://10.10.124.134/job/AR-build-pipeline/1435/) **failed**.

**Comment by AndroidBob** [comment]
Build [1439](https://10.10.124.134/job/AR-build-pipeline/1439/) **failed**.

**Comment by AndroidBob** [comment]
Build [1440](https://10.10.124.134/job/AR-build-pipeline/1440/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7883220)(7883220)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7883220)(7883220)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
LGTM

**Comment by AndroidBob** [comment]
Build [1470](https://10.10.124.134/job/AR-build-pipeline/1470/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7909885)(7909885)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7909885)(7909885)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]
Great work! Just waiting on the resolving of the merging conflict 😄

**Comment by AndroidBob** [comment]
Build [1542](https://10.10.124.134/job/AR-build-pipeline/1542/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7934721)(7934721)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7934721)(7934721)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1555](https://10.10.124.134/job/AR-build-pipeline/1555/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7943178)(7943178)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7943178)(7943178)-staging-compat.apk)

**Pull request merged**
