### PR TITLE
feat: support material you icons

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Our current blue icon does not follow the guidelines provided by the Design team.

### Solutions

- Follow the design;
- Support Material You launcher icons.

### Dependencies

Because of some res naming conflict, it requires the changes on this Kalium branch, that delete drawables with the same name:

Needs releases with:

- https://github.com/wireapp/kalium/pull/965

### Testing

N/A

#### How to Test

Install the app and see it in your launcher. If you have Material You, select a different colour palette.

### Attachments

Find the Wire app icon on the very bottom. Third icon on top of the Search Bar.

| No Material You Icons | Material You Palette#1 | Material You Palette#2 |
|----------------|------------------|-----------------------|
|Screenshot_20220923-152325 | Screenshot_20220923-152304 | Screenshot_20220923-161858
 |

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1028/1/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1028/2/) **failed**.

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1028/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1028/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1028/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4501379)(4501379)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4501379)(4501379)-dev-release.apk)

**Pull request merged**
