### PR TITLE
feat: App soft lock when E2EI is required (WPB-5876)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5876" title="WPB-5876" target="_blank">TaskWPB-5876</a>  [Android] App Soft Lock when the Grace Period has passed
  </td></table>
  <br />
 

# What's new in this PR?

When the Grace Period for registering the E2EI has passed we need to "block" the app for the user.
- show the un-removable dialog that allows user only register the E2EI (was already implemented)
- block all the message notifications and incoming calls 

### Solutions

Update `NotificationManager` to keep observing and saving the messages and all the event into the DB, but do not notify user about it.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2443](https://10.10.124.134/job/AR-build-pipeline/2443/) **failed**.

**Review by mchenani — APPROVED** [review]
🔥

**Comment by AndroidBob** [comment]
Build [2458](https://10.10.124.134/job/AR-build-pipeline/2458/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8540365)(8540365)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8540365)(8540365)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2476](https://10.10.124.134/job/AR-build-pipeline/2476/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8575593)(8575593)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8575593)(8575593)-staging-compat.apk)

**Pull request merged**
