### PR TITLE
fix: show connection request with unavailable name [WPB-6247]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6247" title="WPB-6247" target="_blank">BugWPB-6247</a>  [Android] Incoming connection request from offline backend not displayed when backend is available again
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Connection requests with incomplete user data shows empty text in user name

### Solutions

When user has incomplete data show `name not available` username text

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

| Before | After |
| ----------- | ------------ |
| before  | after  |

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Review by MohamadJaara — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3167](https://10.10.124.134/job/AR-build-pipeline/3167/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8911234)(8911234)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8911234)(8911234)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3177](https://10.10.124.134/job/AR-build-pipeline/3177/) **failed**.

**Comment by AndroidBob** [comment]
Build [3183](https://10.10.124.134/job/AR-build-pipeline/3183/) **failed**.

**Comment by AndroidBob** [comment]
Build [3184](https://10.10.124.134/job/AR-build-pipeline/3184/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8912825)(8912825)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8912825)(8912825)-staging-compat.apk)

**Pull request merged**
