### PR TITLE
fix: animate progress bar

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When creating/restoring backups and playing audio, the progress bar looks pretty bland

### Solutions

Add some animations there making it much neater
 
#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

- Restore/Create a backup
- Or play an audio

####  Before:

https://user-images.githubusercontent.com/18124919/234280512-250b018a-9ac0-4662-bf58-7c563ea33a0d.mp4

https://user-images.githubusercontent.com/18124919/234280539-d681924f-831d-4442-bbf4-17225cdc21ab.mp4

####  After

https://user-images.githubusercontent.com/18124919/234280847-11217579-d0ef-4d75-a98e-ee775c045e5f.mp4

https://user-images.githubusercontent.com/18124919/234281590-a2e4198c-594e-44d3-b36e-eddcd1ac08b9.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1712/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1712/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1712/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6347804)(6347804)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6347804)(6347804)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
🚀

**Review by alexandreferris — APPROVED** [review]

**Review by vitorhugods — APPROVED** [review]
Let's go! This PR is fire 🔥🔥🔥

**Review by trOnk12 — APPROVED** [review]
looking sexy

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1712/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6353216)(6353216)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6353216)(6353216)-staging-compat.apk)

**Pull request merged**
