### PR TITLE
ci: set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by tmspzz**

### CODE REVIEW

**Comment by gongracr** [comment]
Not sure if this PR is still valid or not as I'm not a pro at all on these azure pipelines. Maybe @vitorhugods or @typfel can chip in? otherwise should we close this PR?

**Comment by vitorhugods** [comment]
> Not sure if this PR is still valid or not as I'm not a pro at all on these azure pipelines. Maybe @vitorhugods or @typfel can chip in? otherwise should we close this PR?

I think Tommaso was just exploring/trying this out for now? He would definitely give us more info by following the PR template if this was ready for review 😄

I will fetch the latest changes from `develop` so Tommaso can see the current set-up.

TL;DR: @yamilmedina did some work to parallelise UI and Unit tests here on `wire-android-reloaded`. I've done some other work to avoid building native iOS libs and parallelise JVM, JS, Android and iOS tests on `Kalium`.

Build time is currently limited by Jenkins in this Repo, which doesn't take too long (about 18mins), considering that it generates a minified APK in the end. And at least we're also running the same tests in Actions, so we get faster the first OK answers way before the 18mins mark.

On Kalium, the longest checks (iOS and Android emulator tests) are taking about 12mins. So it isn't too bad either.

**Comment by AndroidBob** [comment]
Build [33](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/33/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2983923)(2983923)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2983923)(2983923)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [34](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/34/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984235)(2984235)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984235)(2984235)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [35](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/35/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984338)(2984338)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984338)(2984338)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [36](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/36/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984560)(2984560)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984560)(2984560)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [37](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/37/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984563)(2984563)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984563)(2984563)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [38](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/38/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984678)(2984678)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984678)(2984678)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [39](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/39/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984745)(2984745)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984745)(2984745)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [40](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/40/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984792)(2984792)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984792)(2984792)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [41](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/41/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2984859)(2984859)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2984859)(2984859)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [43](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/43/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2985370)(2985370)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2985370)(2985370)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [44](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/44/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2985551)(2985551)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2985551)(2985551)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [45](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/45/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2985867)(2985867)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2985867)(2985867)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [46](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/46/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2986101)(2986101)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2986101)(2986101)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [47](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/47/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(2986815)(2986815)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(2986815)(2986815)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [48](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/48/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3009554)(3009554)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3009554)(3009554)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [49](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/49/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3009774)(3009774)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3009774)(3009774)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [50](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/50/) **failed**.

**Comment by AndroidBob** [comment]
Build [51](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/51/) **failed**.

**Comment by AndroidBob** [comment]
Build [52](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/52/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3018788)(3018788)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3018788)(3018788)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [54](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/54/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3019928)(3019928)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3019928)(3019928)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [57](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/57/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3021400)(3021400)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3021400)(3021400)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [58](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/58/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3023049)(3023049)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3023049)(3023049)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [59](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/59/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3026511)(3026511)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3026511)(3026511)-dev-release.apk)

**Comment by typfel** [comment]
Is Android Bob supposed to keep making new builds in this PR?

**Comment by vitorhugods** [comment]
> Is Android Bob supposed to keep making new builds in this PR?

It seems this behaviour is old AF, but adding the comments when the build is complete made it clearer.

My understanding is that everytime the target branch is updated, Jenkins will try to check if it is mergeable ahead-of-time.

I want to fix this because we have a limited number of 4 runners, and this is very wasteful, and leads to duplication of builds.

I think we just need to fiddle a bit with the pipeline settings in order to fix this.

**Comment by AndroidBob** [comment]
Build [62](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/62/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3027175)(3027175)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3027175)(3027175)-dev-release.apk)

**Comment by vitorhugods** [comment]
I changed the Jenkins settings and if I understood things right, it should only build when the PR is updated. It doesn't matter if the target branch is updated or not.

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-433/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5457137)(5457137)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5457137)(5457137)-dev-release.apk)

**Pull request closed without merging**
