### PR TITLE
chore: MLS M4 build

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Latest AR made compatible with the MLS M4 release

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5094025)(5094025)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5094025)(5094025)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5257916)(5257916)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5257916)(5257916)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5438335)(5438335)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5438335)(5438335)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5631587)(5631587)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5631587)(5631587)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5637734)(5637734)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5637734)(5637734)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5638418)(5638418)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5638418)(5638418)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5673422)(5673422)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5673422)(5673422)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5733146)(5733146)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5733146)(5733146)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5733404)(5733404)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5733404)(5733404)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5802916)(5802916)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5802916)(5802916)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5854893)(5854893)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5854893)(5854893)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1202/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5862158)(5862158)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv4.0.0(5862158)(5862158)-dev-compat.apk)

**Comment by vitorhugods** [comment]
@typfel Does this PR still make sense?

**Comment by typfel** [comment]
No I will close it but I want to keep the branch for now

**Pull request closed without merging**
