### PR TITLE
[AN-5241] [AN-5556] images restart downloading when switching network

### PR DESCRIPTION
**Pull request by makingthematrix**
Requires https://github.com/wireapp/wire-android-sync-engine/pull/218 to be merged in SE
#### APK
[Download build #9348](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9348/artifact/build/artifact/wire-dev-PR1081-9348.apk)
[Download build #9354](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9354/artifact/build/artifact/wire-dev-PR1081-9354.apk)
[Download build #9364](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9364/artifact/build/artifact/wire-dev-PR1081-9364.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Build again

**Comment by someoneEsle** [comment]
Bug:
- user has setting on "download on wifi only"
- user is on 4g
- user gets an image
- placeholder is shown
- user changes the setting to "download always"
- download of the picture is not triggered

Aside from this it looks good :)

**Comment by makingthematrix** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Comment by red-avtovo** [comment]
Unable to login, using build from this PR

**Pull request merged**
