### PR TITLE
[AN-5134][AN-5639] Calling fixes

### PR DESCRIPTION
**Pull request by deanrobertcook**
https://wearezeta.atlassian.net/browse/AN-5134
https://wearezeta.atlassian.net/browse/AN-5639
#### APK
[Download build #9488](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9488/artifact/build/artifact/wire-dev-PR1131-9488.apk)
[Download build #9490](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9490/artifact/build/artifact/wire-dev-PR1131-9490.apk)
[Download build #9494](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9494/artifact/build/artifact/wire-dev-PR1131-9494.apk)
[Download build #9499](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9499/artifact/build/artifact/wire-dev-PR1131-9499.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
Bug 1
Still unable to turn off loudspeaker

**Comment by deanrobertcook** [comment]
Final fix for loudspeaker depends on https://github.com/wireapp/wire-android-sync-engine/pull/247

**Comment by someoneEsle** [comment]
This looks good, but I'll wait until it builds to remove the QA label -- maybe you change something in the sync engine in the meantime, and I want to make sure that we merge the exact same thing I tested.

**Comment by makingthematrix** [comment]
build again

**Comment by someoneEsle** [comment]
you can merge

**Pull request merged**
