### PR TITLE
Make blacklist URI optional

### PR DESCRIPTION
**Pull request by CalumMcCall**
### Issues

If the blacklist URL was missing from a custom config, the client would throw a JSON parse exception and fail to connect to the custom backend. The desire is to have the blacklist be ignored if not present.

### Causes

The crash was caused by the type of the blacklist URL not being optional, which results in the JSON parsing failing.

### Solutions

The blacklist url has now been changed so it's an `Option` throughout the codebase. If there is no blacklist given, then an empty `VersionBlacklist` is used, which allows any version.

### Testing

Testing was done manually using a custom backend url mentioned in the [JIRA ticket](https://wearezeta.atlassian.net/browse/AN-7035)

#### APK
[Download build #2353](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2353/artifact/build/artifact/wire-dev-PR2935-2353.apk)

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by marcoconti83** [comment]
Ok to build

**Comment by marcoconti83** [comment]
@makingthematrix or @gizemb , I might not be a recognized admin anymore, can you say "OK to build" so that Jenkins will pick it up? Thanks :)

**Comment by makingthematrix** [comment]
OK to build

**Comment by makingthematrix** [comment]
build again

**Comment by CalumMcCall** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Pull request merged**
