### PR TITLE
ci(fdroid): commited docker-compose / dockerfile content (SQPIT-783)

### PR DESCRIPTION
**Pull request by Gardosen**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQPIT-783" title="SQPIT-783" target="_blank">TaskSQPIT-783</a>  implement a docker/docker-compose setup into wire-androi
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

this pr adds a dockerfile setup and a docker-compose file to the project plus and update to the README.MD explaining how to use it and how to also build custom clients using a custom repository

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/3/)

**Review by makingthematrix — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/8/)

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/12/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/15/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3613/17/)

**Pull request merged**
