### PR TITLE
Delete phone from account preferences (if email is set)

### PR DESCRIPTION
**Pull request by hakonbo**
#### APK
[Download build #8861](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8861/artifact/build/artifact/wire-dev-PR855-8861.apk)
[Download build #8865](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8865/artifact/build/artifact/wire-dev-PR855-8865.apk)
[Download build #8866](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8866/artifact/build/artifact/wire-dev-PR855-8866.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
@mykola-mokhnach care to take a look?

**Comment by mykola-mokhnach** [comment]
Of course - there is a build now ;)

**Comment by mykola-mokhnach** [comment]
This all works, but I think it is a bad idea to let user to delete email if he has more than one device

**Comment by hakonbo** [comment]
Commented out possibility to remove email for now.

**Comment by hakonbo** [comment]
build again

**Comment by mykola-mokhnach** [comment]
LGTM

**Pull request merged**
