### PR TITLE
fix: update last read message on conversation opening [WPB-7208]

### PR DESCRIPTION
**Pull request by AndroidBob**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-7208" title="WPB-7208" target="_blank">BugWPB-7208</a>  [Android] Conversations not being marked as read until I send a message
  </td></table>
  <br />
 

Cherry pick from the original PR: 
- #2819

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like 
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When user opens conversation screen messages are not being marked as read until user will scroll.

### Solutions

Additional LauncherEffect to be triggered at start to mark latest message as read

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3765](https://10.10.124.134/job/AR-build-pipeline/3765/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9249002)(9249002)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9249002)(9249002)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3785](https://10.10.124.134/job/AR-build-pipeline/3785/) **failed**.

**Comment by AndroidBob** [comment]
Build [3805](https://10.10.124.134/job/AR-build-pipeline/3805/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9260225)(9260225)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9260225)(9260225)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3834](https://10.10.124.134/job/AR-build-pipeline/3834/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9266382)(9266382)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9266382)(9266382)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3880](https://10.10.124.134/job/AR-build-pipeline/3880/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9276517)(9276517)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9276517)(9276517)-staging-compat.apk)

**Pull request merged**
