### PR TITLE
Fix white screen bug.

### PR DESCRIPTION
**Pull request by yeryomenkom**
Fixes https://github.com/wireapp/android-project/issues/255

Notes for tester:
Scenario for test is described by @red-avtovo inside the issue.
#### APK
[Download build #11741](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11741/artifact/build/artifact/wire-dev-PR1802-11741.apk)
[Download build #11756](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11756/artifact/build/artifact/wire-dev-PR1802-11756.apk)
[Download build #11758](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11758/artifact/build/artifact/wire-dev-PR1802-11758.apk)
[Download build #11770](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11770/artifact/build/artifact/wire-dev-PR1802-11770.apk)

### CODE REVIEW

**Comment by yeryomenkom** [comment]
build again

**Comment by yeryomenkom** [comment]
build again

**Comment by red-avtovo** [comment]
Issue Resolved

**Comment by red-avtovo** [comment]
Works flawlessly

**Comment by JPonte** [comment]
Will be in the next SE release.

**Pull request closed without merging**
