### PR TITLE
feat: conversation creation with offline backends (WPB-263)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-263" title="WPB-263" target="_blank">TaskWPB-263</a>  [Android] Implement UX on clients for conversation creation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Supports the creation of conversations and members from remote backends, as of now, we don't display information to the users about participants that couldn't be added.

### Solutions

Gives the feedback to the user about participants that couldn't be added while creating a conversation, because the users might be down.

### Dependencies (Optional)

Needs to be merged after:

- https://github.com/wireapp/kalium/pull/1774

### Testing

WIP

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/5806454/230e4949-7908-4c52-a607-31c4b59a6510

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1842/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6709108)(6709108)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6709108)(6709108)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1842/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1842/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6716296)(6716296)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6716296)(6716296)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1842/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6716681)(6716681)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6716681)(6716681)-staging-compat.apk)

**Pull request merged**
