### PR TITLE
fix bug with UTF-16 encoding for chinese characters

### PR DESCRIPTION
**Pull request by kongpf8848**
fix bug for UTF-16 encoding mentions info before send message

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by BradleyWire** [comment]
Can you please update the description to share more details about the bug? The following template will help guide you: 

**Describe the bug**:

**To Reproduce**:

**Expected behavior**: 

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 
- Last Wire version that did not exhibit the issue (if applicable): 
- Android OS version used to run Wire: 
- Is this a custom firmware or a stock one: 
- Mobile phone model/manufacturer: 
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): 

**Additional context**

Thank you for your help in correcting this issue!

**Comment by makingthematrix** [comment]
The change doesn't look right. `text` should never be `null` anyway. And there was a reason why we checked if the first two bytes are `0`, although it looks like a hack... What's the way to reproduce the problem? Is it enough if I try to send a mention where a part of the text is in Chinese characters?

**Comment by kongpf8848** [comment]
> Can you please update the description to share more details about the bug? The following template will help guide you:
> 
> **Describe the bug**:
> 
> **To Reproduce**:
> 
> **Expected behavior**:
> 
> **Screenshots**
> 
> **Smartphone (please complete the following information):**
> 
> * Wire version that exhibits the issue:
> * Last Wire version that did not exhibit the issue (if applicable):
> * Android OS version used to run Wire:
> * Is this a custom firmware or a stock one:
> * Mobile phone model/manufacturer:
> * Mobile network type (EDGE/LTE/Wi-Fi/Offline):
> 
> **Additional context**:
> 
> Thank you for your help in correcting this issue!
Wire 2020-10-13 at 10-21-09

Wire Version：3.55.939
Android OS Version：Android 9
Mobile：Samsung Galaxy S8/Samsung
Network：LTE

**Comment by kongpf8848** [comment]
> hack
1.  I think for not empty string after UTF-16 encoding, first two bytes either 0xFFFE(UTF-16LE) or  0xFEFF(UTF-16BE),after encode, every byte has value possible large than 0 or small than 0,so use lastIndexWhere(_ > 0) for last Index is not correct in some case(eg, for chinese characters).
2. you can send a mention where a part of the text is in chinese characters to reproduce this problem.

**Review by gizemb — CHANGES_REQUESTED** [review]
Could you please add a test case about this fix? I think adding another scenario to`Adjust mentions` feature in `MessageDataSpec` would suffice. This way, we could also see more clearly what was the problem and whether it's really fixed.

**Comment by gizemb** [comment]
@kongpf8848 any chance you could add a test case? note that in case of an update you'd have to rebase this branch to `develop` since we've made some changes there for the build pipeline.

**Comment by gizemb** [comment]
hi @kongpf8848 , I see that your forked branch isn't available anymore. we want to get this PR merged. would you be willing to help us by adding some tests?

**Comment by gizemb** [comment]
I'm closing this PR as we couldn't get a response from the author for quite some time. I duplicated it in #3356 and will make sure the author's contributions are mentioned in release notes.

**Pull request closed without merging**
