### PR TITLE
fix: personal user settings group read receipt (AR-3168)

### PR DESCRIPTION
**Pull request by alexandreferris**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3168" title="AR-3168" target="_blank">BugAR-3168</a>  PlayTest 21.02 - Read receipts -> Personal user should't change read receipt settings
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Personal users without a team could toggle read receipt settings in a group conversation (if they were the owner).

### Causes (Optional)

Logic was missing some things.

### Solutions

Add logic for when we should enable the toggle.
Logic is as follow:

Account contains:
- [NO TEAM][CONVERSATION NO TEAM] = toggle disabled
- [NO TEAM][CONVERSATION HAS TEAM] = toggle based if user is group admin
- [TEAM] = toggle based if user is group admin

#### How to Test

User needs to create a group from personal account with no team and also join another group where owner of group has a team and to become the admin of the group as well, then logic should follow.

### CODE REVIEW

**Comment by vitorhugods** [comment]
> @alexandreferris looks like you are rolling back kalium to a previous commitish.
> 
> This means that the PR's target branch (develop) is using a newer version of Kalium, and the changes in this PR will rollback Kalium to an older version.
> develop 	This PR
> [21ca3887fe3c06d2260bfe2c45c2320a8cb7f47f](https://github.com/wireapp/kalium/tree/21ca3887fe3c06d2260bfe2c45c2320a8cb7f47f) 	[88503403b983ee2d5f3df4ecd4072f869f015018](https://github.com/wireapp/kalium/tree/88503403b983ee2d5f3df4ecd4072f869f015018)
> 
> Is this intentional?

Dear bot, you're drunk.
I'm sorry you were made like this by me and my colleagues.

Not sure why, but manually looking at it, it looks fine.

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1593/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1593/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6104373)(6104373)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6104373)(6104373)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1593/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6105260)(6105260)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6105260)(6105260)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]
LGTM 👌

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1593/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6128434)(6128434)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6128434)(6128434)-staging-compat.apk)

**Pull request merged**
