### PR TITLE
Reoarganize gradle scripts

### PR DESCRIPTION
**Pull request by mejdoo**
## What's new in this PR?

Gradle scripts are placed in deferent folders. I moved them to a single place`/scripts`

#### APK
[Download build #2891](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2891/artifact/build/artifact/wire-dev-PR3064-2891.apk)

### CODE REVIEW

**Review by BradleyWire — APPROVED** [review]

**Review by android10 — APPROVED** [review]
:+1:

**Comment by mejdoo** [comment]
build again

**Comment by mejdoo** [comment]
build again

**Comment by mejdoo** [comment]
build again

**Pull request merged**
