### PR TITLE
chore: upgrade CC to 1.0.0.rc14

### PR DESCRIPTION
**Pull request by typfel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Upgrade to CC 1.0.0.rc14, see linked PR for details.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by mchenani — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1191](https://10.10.124.134/job/AR-build-pipeline/1191/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7788502)(7788502)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7788502)(7788502)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1208](https://10.10.124.134/job/AR-build-pipeline/1208/) **failed**.

**Review by vitorhugods — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1421](https://10.10.124.134/job/AR-build-pipeline/1421/) **failed**.

**Comment by yamilmedina** [comment]
> @typfel looks like you are rolling back kalium to a previous commitish.
> 
> This means that the PR's target branch (release/candidate) is using a newer version of Kalium, and the changes in this PR will rollback Kalium to an older version.
> 
> release/candidate	This PR
> [8e05b70d76349c0494ec96064c1daefda083a132](https://github.com/wireapp/kalium/tree/8e05b70d76349c0494ec96064c1daefda083a132)	[2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e](https://github.com/wireapp/kalium/tree/2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e)
> Is this intentional?

False positive, 2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e it's the latest on Kalium RC

**Comment by typfel** [comment]
> > @typfel looks like you are rolling back kalium to a previous commitish.
> > This means that the PR's target branch (release/candidate) is using a newer version of Kalium, and the changes in this PR will rollback Kalium to an older version.
> > release/candidate	This PR
> > [8e05b70d76349c0494ec96064c1daefda083a132](https://github.com/wireapp/kalium/tree/8e05b70d76349c0494ec96064c1daefda083a132)	[2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e](https://github.com/wireapp/kalium/tree/2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e)
> > Is this intentional?
> 
> False positive, 2d2f00f47f7eb2c7b50b74859ea8ad91ac7a520e it's the latest on Kalium RC

But this PR is outdated anyway we went with the 1.0.0-pre6 schema fix release.

**Comment by AndroidBob** [comment]
Build [1422](https://10.10.124.134/job/AR-build-pipeline/1422/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7874023)(7874023)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7874023)(7874023)-staging-compat.apk)

**Pull request closed without merging**
