### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4943](https://10.10.124.134/job/AR-build-pipeline/4943/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9749633)(9749633)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9749633)(9749633)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4955](https://10.10.124.134/job/AR-build-pipeline/4955/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9750703)(9750703)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9750703)(9750703)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4976](https://10.10.124.134/job/AR-build-pipeline/4976/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9757520)(9757520)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9757520)(9757520)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5011](https://10.10.124.134/job/AR-build-pipeline/5011/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9785036)(9785036)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9785036)(9785036)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5030](https://10.10.124.134/job/AR-build-pipeline/5030/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9791873)(9791873)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9791873)(9791873)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5046](https://10.10.124.134/job/AR-build-pipeline/5046/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9792996)(9792996)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9792996)(9792996)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [5051](https://10.10.124.134/job/AR-build-pipeline/5051/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9793494)(9793494)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9793494)(9793494)-staging-compat.apk)

**Pull request merged**
