### PR TITLE
fix: crash about persistent websocket being started from background [WPB-6551]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6551" title="WPB-6551" target="_blank">BugWPB-6551</a>  [Android] Crash caused by Foreground services not allowed
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Sometimes `startForeground` for `PersistentWebSocketService` results in `ForegroundServiceStartNotAllowedException`.

### Causes (Optional)

This exception means that `startForeground` was executed when it's not allowed to, there are multiple restrictions on when foreground service can be started - more here: https://developer.android.com/develop/background-work/services/foreground-services#background-start-restriction-exemptions
For us, we are allowed to start foreground service from Activity when the app is in the foreground and when the device is booted or app is updated (probably within 20 seconds) and we use `StartServiceReceiver` for that. The problem is probably that we `collect` in a coroutine, so it's just left hanging and receiving new values even in the background.

### Solutions

When `StartServiceReceiver` is called, get the list of persistent websocket statuses only once to make sure that we open the service within the permitted time frame. This persistent websocket flag can be changed only in settings by the user when the app is in the foreground so no need to observe for changes in this receiver - if changed then the service will be started from `WireActivityViewModel`.
The logic of deciding whether the service should be started or not is extracted to dedicated use case and tested.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

There's no specific reproduction path, from the logs it looks like it could happen when the app was updated in the background and the sync was started so that the user's values in database are updated and `persistentWebSocketStatusListFlow` emits new list.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3355](https://10.10.124.134/job/AR-build-pipeline/3355/) **failed**.

**Comment by AndroidBob** [comment]
Build [3356](https://10.10.124.134/job/AR-build-pipeline/3356/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.1(9014834)(9014834)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.1(9014834)(9014834)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3364](https://10.10.124.134/job/AR-build-pipeline/3364/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.1(9015771)(9015771)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.1(9015771)(9015771)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
🙇🏼‍♂️

**Comment by AndroidBob** [comment]
Build [3366](https://10.10.124.134/job/AR-build-pipeline/3366/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.1(9016184)(9016184)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.1(9016184)(9016184)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]
👌🏻

**Pull request merged**
