### PR TITLE
feat: Clients need to know if the backend support federated endpoints or not (FS-421)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-421" title="FS-421" target="_blank">TaskFS-421</a>  [Android] Clients need to know if the backend support federated endpoints or not
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/FS-421

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow
  - [x] contains a reference JIRA issue number
  - [x] answers the question: _If merged, this PR will: ..._

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Negotiate which backend API version to use when communicating with the backend. This is done in two steps:
- retrieving the available versions from the backend
- checking that there is a version in common from those supported by the client. If not, display a popup asking the user to update.

In addition to the API version, the backend also advertise if the backend is configured to support federation of backends. If this is not true, then the client should not use fully qualified domains, especially when interacting with AVS.

### Testing

- Unit tests for parsing the version information and finding the common version
- Manually tested for displaying the popup

#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/4/)

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/8/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/11/)

**Comment by AndroidBob** [comment]
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/12/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/13/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/15/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/16/)

**Comment by AndroidBob** [comment]
Build Failure
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/17/)

**Comment by AndroidBob** [comment]
Build Failure
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:20
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/20/)

**Comment by AndroidBob** [comment]
Build Failure
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/21/)

**Comment by marcoconti83** [comment]
I'm updating the PR description as I took over this topic

**Comment by AndroidBob** [comment]
Build Failure
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/23/)

**Review by johnxnguyen — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:24
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3665/24/)

**Review by vitorhugods — APPROVED** [review]

**Pull request merged**
