### PR TITLE
fix: run UI logic on the main thread [WPB-9458]

### PR DESCRIPTION
**Pull request by MohamadJaara**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-9458" title="WPB-9458" target="_blank">BugWPB-9458</a>  [Android] crash in wire activity
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

wire activity crashes when clearing view model

### Solutions

we suspect that it have to do with changes in https://github.com/wireapp/wire-android/blob/1d959e15d83e58464c4cb4319c8a811708f0bec8/app/src/main/kotlin/com/wire/android/ui/WireActivity.kt#L466-L485 so reverting the changes should do the trick

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by borichellow — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]

**Review by ohassine — CHANGES_REQUESTED** [review]
Why reverting all the commit and not just removing the default dispatcher from here ?
```
 lifecycleScope.launch(Dispatchers.Default) { 
         lockCodeTimeManager.get().observeAppLock() 
             // Listen to one flow in a lifecycle-aware manner using flowWithLifecycle 
             .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED) 
             .first().let { 
```

**Comment by MohamadJaara** [comment]
> Why reverting all the commit and not just removing the default dispatcher from here ?
> 
> ```
>  lifecycleScope.launch(Dispatchers.Default) { 
>          lockCodeTimeManager.get().observeAppLock() 
>              // Listen to one flow in a lifecycle-aware manner using flowWithLifecycle 
>              .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED) 
>              .first().let { 
> ```

the changes does more or less nothing for example   `observePersistentConnectionStatus` starts with `viewModelScope.launch` which which bring the function back to the main thread.

**Comment by ohassine** [comment]
> > Why reverting all the commit and not just removing the default dispatcher from here ?
> > ```
> >  lifecycleScope.launch(Dispatchers.Default) { 
> >          lockCodeTimeManager.get().observeAppLock() 
> >              // Listen to one flow in a lifecycle-aware manner using flowWithLifecycle 
> >              .flowWithLifecycle(lifecycle, Lifecycle.State.STARTED) 
> >              .first().let { 
> > ```
> 
> the changes does more or less nothing for example `observePersistentConnectionStatus` starts with `viewModelScope.launch` which which bring the function back to the main thread.

No the child coroutine works on same dispatcher as the parent if we don't specify it on launch

**Comment by AndroidBob** [comment]
Build [5084](https://10.10.124.134/job/AR-build-pipeline/5084/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.1(9802271)(9802271)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.1(9802271)(9802271)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Pull request merged**
