### PR TITLE
	[AN-4611] Fixed issue with tap image

### PR DESCRIPTION
**Pull request by JPonte**
Ticket: https://wearezeta.atlassian.net/browse/AN-4611
#### APK

[Download build #7791](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7791/artifact/build/artifact/wire-dev-PR268-7791.apk)
[Download build #7795](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7795/artifact/build/artifact/wire-dev-PR268-7795.apk)
[Download build #7797](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7797/artifact/build/artifact/wire-dev-PR268-7797.apk)
[Download build #7798](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7798/artifact/build/artifact/wire-dev-PR268-7798.apk)
[Download build #7799](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7799/artifact/build/artifact/wire-dev-PR268-7799.apk)
[Download build #7800](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7800/artifact/build/artifact/wire-dev-PR268-7800.apk)

[Download build #7823](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7823/artifact/build/artifact/wire-dev-PR268-7823.apk)
[Download build #7835](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7835/artifact/build/artifact/wire-dev-PR268-7835.apk)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
It does not work as expected in build #7791 for me. Double tap on image does not make Like hearth to appear underneath the image (though this works properly for text messages). Also, Sending... label is never changed to Delivered/Sent for images (but this works properly for text messages too).

**Comment by mykola-mokhnach** [comment]
1. Post two images into a conversation
2. Tap the first image to see the toolbox and button
3. Tap the second image

AR:
Sketch/fullscreen buttons are visible for both images

ER:
Sketch/fullscreen buttons should be hidden together with message toolbox

**Comment by mykola-mokhnach** [comment]
1. Post an ephemeral image into a conversation 
2. Tap the image to see buttons
3. Wait until the image expires

AR:
Sketch/fullscreen buttons are visible on the expired image placeholder

ER:
Sketch/fullscreen buttons should be hidden when the corresponding image expires

**Comment by mykola-mokhnach** [comment]
Incorrect margin is set if smaller picture is added to a conversation:
screen

**Comment by vova-lohika** [comment]
Fine now 👍

**Pull request merged**
