### PR TITLE
chore: Assign sub-system tags

### PR DESCRIPTION
**Pull request by VictorWissink**
### Issue

BSI needs a documentation that contains security-relevant test cases which are mapped to security functions (SF), interfaces (TSFI) and sub-systems. (@s) Additionally we need to deliver a document for them which contains all test cases containing purpose, procedure, expected result and actual result.

### Solutions

We previously annotated unit/integration test cases with a comment specifying the Security Function + interfaces, but the sub-system value was still missing. This PR adds the sub system value.

### Notes

See https://github.com/wireapp/bsi-mapping/ for the scripts that do the parsing and creation of the documents.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/1/)

**Review by makingthematrix — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3616/6/)

**Comment by VictorWissink** [comment]
Since I'm not authorized to merge this pull request, could you merge it @makingthematrix ? 😅

**Review by mythsunwind — APPROVED** [review]

**Pull request merged**
