### PR TITLE
chore: turn on federation (FS-138)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-138" title="FS-138" target="_blank">StoryFS-138</a>  [Android] As the organizer of a conference call I like to place a conference call in a conversation with users who are part of different federated backends
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

N/A

### Solutions

Enabling the federation flag for testing purpose

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/5/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/8/)

**Comment by AndroidBob** [comment]
Build Failure
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/11/)

**Comment by AndroidBob** [comment]
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/12/)

**Comment by AndroidBob** [comment]
Build Success
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/13/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/14/)

**Comment by AndroidBob** [comment]
Build Failure
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/15/)

**Comment by AndroidBob** [comment]
Build Failure
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/16/)

**Comment by AndroidBob** [comment]
Build Failure
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:20
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/20/)

**Comment by AndroidBob** [comment]
Build Success
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/21/)

**Comment by AndroidBob** [comment]
Build Success
ID:22
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/22/)

**Comment by AndroidBob** [comment]
Build Success
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/23/)

**Comment by AndroidBob** [comment]
Build Success
ID:24
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/24/)

**Comment by AndroidBob** [comment]
Build Failure
ID:25
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/25/)

**Comment by AndroidBob** [comment]
Build Success
ID:26
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/26/)

**Comment by AndroidBob** [comment]
Build Success
ID:27
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/27/)

**Comment by AndroidBob** [comment]
Build Success
ID:28
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/28/)

**Comment by AndroidBob** [comment]
Build Success
ID:29
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/29/)

**Comment by AndroidBob** [comment]
Build Success
ID:30
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/30/)

**Comment by AndroidBob** [comment]
Build Success
ID:31
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/31/)

**Comment by AndroidBob** [comment]
Build Success
ID:32
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/32/)

**Comment by AndroidBob** [comment]
Build Success
ID:33
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3648/33/)

**Comment by marcoconti83** [comment]
This PR has been made obsolete by https://github.com/wireapp/wire-android/pull/3665

**Pull request closed without merging**
