### PR TITLE
test: Trust additional CAs (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by borichellow**
Small changes to trust additional CAs, that is needed for testing and has to be removed after testing!

### CODE REVIEW

**Review by MohamadJaara — CHANGES_REQUESTED** [review]
Please do not mere those changes, if you need something for testing purposes then keep the changes separated in a different branch

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1310/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5438646)(5438646)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5438646)(5438646)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1310/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5454727)(5454727)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5454727)(5454727)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1310/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5457643)(5457643)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5457643)(5457643)-dev-compat.apk)

**Pull request closed without merging**
