### PR TITLE
fix: empty space in message details item [AR-2773]

### PR DESCRIPTION
**Pull request by MohammedMokresh**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2773" title="AR-2773" target="_blank">BugAR-2773</a>  empty space in ui when tapping on a user on message details
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
Extra padding in the message details item

### Solutions
remove the padding

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1271/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5342094)(5342094)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5342094)(5342094)-dev-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Review by saleniuk — COMMENTED** [review]
Actually, these rows should have a padding x16 from the left, so just removing this x8 makes it to be closer to the left edge than on designs, so this x8 padding needs to be moved to the inside, maybe applied to the leadingIcon?

**Review by saleniuk — CHANGES_REQUESTED** [review]
Actually, these rows should have a padding x16 from the left, so just removing this x8 makes it to be closer to the left edge than on designs, so this x8 padding needs to be moved to the inside, maybe applied to the leadingIcon?

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1271/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5342991)(5342991)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5342991)(5342991)-dev-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Pull request merged**
