### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2826](https://10.10.124.134/job/AR-build-pipeline/2826/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8775615)(8775615)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8775615)(8775615)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2854](https://10.10.124.134/job/AR-build-pipeline/2854/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8791415)(8791415)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8791415)(8791415)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2855](https://10.10.124.134/job/AR-build-pipeline/2855/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8791910)(8791910)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8791910)(8791910)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2876](https://10.10.124.134/job/AR-build-pipeline/2876/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8818628)(8818628)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8818628)(8818628)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2891](https://10.10.124.134/job/AR-build-pipeline/2891/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8824860)(8824860)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8824860)(8824860)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2919](https://10.10.124.134/job/AR-build-pipeline/2919/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8826263)(8826263)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8826263)(8826263)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2934](https://10.10.124.134/job/AR-build-pipeline/2934/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8826899)(8826899)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8826899)(8826899)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2945](https://10.10.124.134/job/AR-build-pipeline/2945/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8834403)(8834403)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8834403)(8834403)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2958](https://10.10.124.134/job/AR-build-pipeline/2958/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8835699)(8835699)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8835699)(8835699)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2971](https://10.10.124.134/job/AR-build-pipeline/2971/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8836406)(8836406)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8836406)(8836406)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2976](https://10.10.124.134/job/AR-build-pipeline/2976/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8840945)(8840945)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8840945)(8840945)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2982](https://10.10.124.134/job/AR-build-pipeline/2982/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8841763)(8841763)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8841763)(8841763)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3003](https://10.10.124.134/job/AR-build-pipeline/3003/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8844377)(8844377)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8844377)(8844377)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3014](https://10.10.124.134/job/AR-build-pipeline/3014/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8844973)(8844973)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8844973)(8844973)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3034](https://10.10.124.134/job/AR-build-pipeline/3034/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8852274)(8852274)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8852274)(8852274)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3044](https://10.10.124.134/job/AR-build-pipeline/3044/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8853362)(8853362)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8853362)(8853362)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3048](https://10.10.124.134/job/AR-build-pipeline/3048/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8876080)(8876080)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8876080)(8876080)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3054](https://10.10.124.134/job/AR-build-pipeline/3054/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8877307)(8877307)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8877307)(8877307)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3068](https://10.10.124.134/job/AR-build-pipeline/3068/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8878608)(8878608)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8878608)(8878608)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3084](https://10.10.124.134/job/AR-build-pipeline/3084/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8885456)(8885456)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8885456)(8885456)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3092](https://10.10.124.134/job/AR-build-pipeline/3092/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8885910)(8885910)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8885910)(8885910)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3117](https://10.10.124.134/job/AR-build-pipeline/3117/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8887733)(8887733)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8887733)(8887733)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3144](https://10.10.124.134/job/AR-build-pipeline/3144/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8894563)(8894563)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8894563)(8894563)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3191](https://10.10.124.134/job/AR-build-pipeline/3191/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8913238)(8913238)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8913238)(8913238)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3194](https://10.10.124.134/job/AR-build-pipeline/3194/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8921160)(8921160)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8921160)(8921160)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3202](https://10.10.124.134/job/AR-build-pipeline/3202/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8936398)(8936398)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8936398)(8936398)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3208](https://10.10.124.134/job/AR-build-pipeline/3208/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8937065)(8937065)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8937065)(8937065)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3217](https://10.10.124.134/job/AR-build-pipeline/3217/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8937438)(8937438)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8937438)(8937438)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3220](https://10.10.124.134/job/AR-build-pipeline/3220/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8937898)(8937898)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8937898)(8937898)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3234](https://10.10.124.134/job/AR-build-pipeline/3234/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8948815)(8948815)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8948815)(8948815)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3251](https://10.10.124.134/job/AR-build-pipeline/3251/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8956705)(8956705)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8956705)(8956705)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3262](https://10.10.124.134/job/AR-build-pipeline/3262/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8964222)(8964222)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8964222)(8964222)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3282](https://10.10.124.134/job/AR-build-pipeline/3282/) **failed**.

**Comment by AndroidBob** [comment]
Build [3288](https://10.10.124.134/job/AR-build-pipeline/3288/) **failed**.

**Comment by AndroidBob** [comment]
Build [3306](https://10.10.124.134/job/AR-build-pipeline/3306/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8972713)(8972713)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8972713)(8972713)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3314](https://10.10.124.134/job/AR-build-pipeline/3314/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8973483)(8973483)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8973483)(8973483)-staging-compat.apk)

**Pull request closed without merging**
