### PR TITLE
fix: make mentions color style more readable on light/dark themes [AR-3011][AR-2922]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3011" title="AR-3011" target="_blank">TaskAR-3011</a>  Blue colour of mentions in dark mode is different than blue of links
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Added some UI changes to be more compliant with designs and easier to be spotted and read.

Note: Needs release with:
- https://github.com/wireapp/kalium/pull/1594

### Attachments (Optional)
| Before | After |
| ----------- | ------------ |
| Captura de pantalla 2023-03-24 a las 17 40 35  | Captura de pantalla 2023-03-24 a las 17 40 23  |
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1582/1/) **failed**.

**Review by saleniuk — APPROVED** [review]

**Comment by ohassine** [comment]
Text shouldn't be selected for all users not only self user ?

**Review by ohassine — APPROVED** [review]
✨

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1582/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1582/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6103773)(6103773)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6103773)(6103773)-staging-compat.apk)

**Pull request merged**
