### PR TITLE
chore: upgrade kotlin to 1.9.23

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Other than Kotlin being a bit behind (1.9.0, considering 1.9.22 is available), some other libraries are lagging behind.
Kotlin 2.0 is around the corner and we should try to keep up to catch breaking changes and deal with them earlier.

### Solutions

Update as much as we can and reasonably can on `develop` before getting too close to a `4.7.0` release. So when we finally make the jump to `2.0` (whenever that might be), it won't be as much of a hassle.

> [!IMPORTANT]
> No Compose/Material updates to avoid breaking UI changes.
> The only change was the compose compiler, to keep it compatible with Kotlin 1.9.22. The compiler itself does not change UI looks.

### Testing

Ran tests and the Android app locally. Everything alright.

### Dependencies

This PR depends on:
- https://github.com/wireapp/kalium/pull/2586

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3481](https://10.10.124.134/job/AR-build-pipeline/3481/) **failed**.

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3492](https://10.10.124.134/job/AR-build-pipeline/3492/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9076772)(9076772)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9076772)(9076772)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3904](https://10.10.124.134/job/AR-build-pipeline/3904/) **failed**.

**Comment by AndroidBob** [comment]
Build [3905](https://10.10.124.134/job/AR-build-pipeline/3905/) **failed**.

**Comment by AndroidBob** [comment]
Build [3906](https://10.10.124.134/job/AR-build-pipeline/3906/) **failed**.

**Comment by AndroidBob** [comment]
Build [3908](https://10.10.124.134/job/AR-build-pipeline/3908/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9310040)(9310040)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9310040)(9310040)-staging-compat.apk)

**Pull request merged**
