### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1713](https://10.10.124.134/job/AR-build-pipeline/1713/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8055492)(8055492)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8055492)(8055492)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1720](https://10.10.124.134/job/AR-build-pipeline/1720/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8056377)(8056377)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8056377)(8056377)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1724](https://10.10.124.134/job/AR-build-pipeline/1724/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8057391)(8057391)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8057391)(8057391)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1733](https://10.10.124.134/job/AR-build-pipeline/1733/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8063875)(8063875)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8063875)(8063875)-staging-compat.apk)

**Pull request closed without merging**
