### PR TITLE
feat: show legal hold disabled dialog [WPB-4870]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4870" title="WPB-4870" target="_blank">StoryWPB-4870</a>  [Android] Disabling legal hold for a team member 
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Implemented the view model with logic to show proper dialog informing the user about legal hold being disabled for him.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/2299

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Disable legal hold for the currently logged in user and then this dialog should pop up.

### Attachments (Optional)

https://github.com/wireapp/wire-android/assets/30429749/f1e12e08-3355-4b94-af2d-f11bbc43ac8a

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2215](https://10.10.124.134/job/AR-build-pipeline/2215/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8308613)(8308613)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8308613)(8308613)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2236](https://10.10.124.134/job/AR-build-pipeline/2236/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8334757)(8334757)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8334757)(8334757)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Review by mchenani — APPROVED** [review]
✌️

**Comment by AndroidBob** [comment]
Build [2254](https://10.10.124.134/job/AR-build-pipeline/2254/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8343097)(8343097)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8343097)(8343097)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2255](https://10.10.124.134/job/AR-build-pipeline/2255/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8343472)(8343472)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8343472)(8343472)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2270](https://10.10.124.134/job/AR-build-pipeline/2270/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8350273)(8350273)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8350273)(8350273)-staging-compat.apk)

**Pull request merged**
