### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5587585)(5587585)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv0.0.1(5587585)(5587585)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5612077)(5612077)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv0.0.1(5612077)(5612077)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5612978)(5612978)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv0.0.1(5612978)(5612978)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5621191)(5621191)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv0.0.1(5621191)(5621191)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5628501)(5628501)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv0.0.1(5628501)(5628501)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1400/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5629328)(5629328)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5629328)(5629328)-staging-compat.apk)

**Pull request merged**
