### PR TITLE
Cleanup : Move sync engine modules below the root folder

### PR DESCRIPTION
**Pull request by mejdoo**
## What's new in this PR?

There are 2 modules below `android-wire-sync-engine` folder: `zmessaging` and `macrosupport` . For visibility, I moved them below the root folder.

#### APK
[Download build #2897](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2897/artifact/build/artifact/wire-dev-PR3067-2897.apk)
[Download build #2901](http://10.10.124.11:8080/job/Pull%20Request%20Builder/2901/artifact/build/artifact/wire-dev-PR3067-2901.apk)

### CODE REVIEW

**Review by gizemb — COMMENTED** [review]
In Jenkins, we have steps referencing this module name
http://10.10.124.11:8080/job/Wire.Pull.Request.Builder/configure
```
# Run SE tests, with deflake step

./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest || \
	./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest -PwireDeflakeTests=1
```
they need to be updated as well, without affecting other PRs of course :)

**Comment by mejdoo** [comment]
> In Jenkins, we have steps referencing this module name
> http://10.10.124.11:8080/job/Wire.Pull.Request.Builder/configure
> 
> ```
> # Run SE tests, with deflake step
> 
> ./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest || \
> 	./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest -PwireDeflakeTests=1
> ```
> 
> they need to be updated as well, without affecting other PRs of course :)

That means after merging this one, right?

**Review by android10 — APPROVED** [review]
:+1: I approve this one but I'm with @gizemb that be should be careful with the CI dependencies. I'm also pretty sure @Gardosen can help with this too.

**Review by gizemb — APPROVED** [review]

**Comment by gizemb** [comment]
> > In Jenkins, we have steps referencing this module name
> > http://10.10.124.11:8080/job/Wire.Pull.Request.Builder/configure
> > ```
> > # Run SE tests, with deflake step
> > 
> > ./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest || \
> > 	./gradlew --no-daemon :wire-android-sync-engine:zmessaging:testDebugUnitTest -PwireDeflakeTests=1
> > ```
> > 
> > 
> > they need to be updated as well, without affecting other PRs of course :)
> 
> That means after merging this one, right?

Nope, it's a PR job (Wire.Pull.Request.Builder), so it should be updated in Jenkins while this PR is in review (i.e. _before_ merge). Then we should re-trigger a build for PR job, which will check this PR with correct gradle tasks. If that build passes, we can merge this PR eventually. If there are other PRs open, they should rebase themselves to develop so that the correct PR job will be executed for them too.

**Comment by mejdoo** [comment]
build again

**Comment by mejdoo** [comment]
build again

**Review by android10 — APPROVED** [review]
:+1:

**Comment by mejdoo** [comment]
build again

**Comment by mejdoo** [comment]
build again

**Pull request merged**
