### PR TITLE
Fix exit animation on GuestOptionsFragment

### PR DESCRIPTION
**Pull request by makingthematrix**

### CODE REVIEW

**Comment by someoneEsle** [comment]
build again

**Comment by someoneEsle** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Open group info page, tap "..." to open the menu. Tap back button. Wire goes back to conversation view instead of group info page

**Comment by makingthematrix** [comment]
Bug #1 was not created by this PR. It is fixed in another PR: https://github.com/wireapp/wire-android/pull/1448

**Pull request merged**
