### PR TITLE
[AN-4408] Shows contacts permission dialog

### PR DESCRIPTION
**Pull request by JPonte**
Ticket: https://wearezeta.atlassian.net/browse/AN-4408
#### APK
[Download build #7814](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7814/artifact/build/artifact/wire-dev-PR281-7814.apk)
[Download build #7838](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7838/artifact/build/artifact/wire-dev-PR281-7838.apk)
[Download build #7839](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7839/artifact/build/artifact/wire-dev-PR281-7839.apk)
[Download build #7844](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7844/artifact/build/artifact/wire-dev-PR281-7844.apk)

### CODE REVIEW

**Comment by vova-lohika** [comment]
During login on test build #7814 I don't see contact sharing request at all.

**Comment by JPonte** [comment]
@vova-lohika indeed I misunderstood the place where it should appear. I set it only when the user opens the contacts list, seemed to make more sense. Shouldn't it only ask when it needs it?

**Comment by vova-lohika** [comment]
Seems there was issue on my phone with cache. Reinstalled PR build and get share contacts request after login. It is fine.
Cases which are not working and should be fixed:
• If user dismiss sharing contacts after login - this request should appear each time on opening search  (until user grant sharing permission or until user disable in Settings > Options > Share Contacts toggle).
* Also if user enable Share Contacts - we should ask for this permission and start asking for this permission on opening search if it is not granted yet)

**Comment by vova-lohika** [comment]
Looks fine, I see only one issue - after first login no permission asked on opening search page. I have to open and close Settings > Options screen to get this fixed.

**Pull request merged**
