### PR TITLE
chore: cherry pick from rc to develop

### PR DESCRIPTION
**Pull request by Garzas**
Develop PR: https://github.com/wireapp/wire-android-reloaded/pull/1947

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Review by vitorhugods — APPROVED** [review]
I wonder if this one will trigger itself after merging 😅

**Comment by Garzas** [comment]
> I wonder if this one will trigger itself after merging 😅

No, because it doesn't have branch name containing `/rc-` 😄

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1951/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.4(7062994)(7062994)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.4(7062994)(7062994)-staging-compat.apk)

**Comment by vitorhugods** [comment]
> > I wonder if this one will trigger itself after merging 😅
> 
> No, because it doesn't have branch name containing `/rc-` 😄

Actually. I hadn't noticed it.
Opened a discussion in the `develop` PR.

**Review by vitorhugods — CHANGES_REQUESTED** [review]
Just speeding down as we discuss this `/rc-` prefix.

**Review by vitorhugods — APPROVED** [review]
👨🏻‍🍳🤌🏻

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1951/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.4(7071596)(7071596)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.4(7071596)(7071596)-staging-compat.apk)

**Pull request merged**
