### PR TITLE
fix: enable dark theme (AR-1306)

### PR DESCRIPTION
**Pull request by vitorhugods**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1306" title="AR-1306" target="_blank">StoryAR-1306</a>  Dark mode test session
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Dark mode was disabled and left to be dealt with in the future.
We had some hard-coded colors here and there, or just weren't forcing some UI elements to use our theme's colours.

### Solutions

Give the dark theme a chance. I've sit with @WolfiWire today and we went through the app fixing whatever was wrong with the dark mode.

In general, no big changes were needed. The main pain in the ass were some calling buttons, that were COMPLETELY a vector, instead of just adding an icon inside of a round button.

#### How to Test

Manually tested

### Attachments
Screenshot_1671556085
Screenshot_1671556094
Screenshot_1671556124
Screenshot_1671556101
Screenshot_1671555937
Screenshot_1671555950
Screenshot_1671555964

----
#### PR Post Merge Checklist for internal contributors

- [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1251/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1251/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5259103)(5259103)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5259103)(5259103)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1251/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5261397)(5261397)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5261397)(5261397)-dev-compat.apk)

**Review by ohassine — APPROVED** [review]
Looks amazing ✨🚀

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1251/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5264365)(5264365)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5264365)(5264365)-dev-compat.apk)

**Pull request merged**
