### PR TITLE
feat: migrate other users data from scala app [AR-2689]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2689" title="AR-2689" target="_blank">SubtaskAR-2689</a>  Migrate other users data
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When migrating from old app version, we get all conversations and messages but not info about members of these conversations and creators of messages, sometimes the old app can still have some useful information about for instance removed members and we won't get info about them during sync anymore.

### Solutions

Implement `MigrateUsersUseCase` which adds missing users data, if such user has been fetched during the sync then just ignore. Updated `ScalaUserDAO` to include more data, `MigrationMapper` to add migration to kalium data objects and added the step to the `MigrationManager`.

Needs releases with:

- https://github.com/wireapp/kalium/pull/1129

#### How to Test

Install and log in to the scala app and update to the AR version, the app should perform the migration successfully and the data of all users, even the ones that are not conversation members anymore (can be checked by looking at user names of messages sent by ones that are no longer in the group and not connected with you).

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1157/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1157/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1157/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4947232)(4947232)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4947232)(4947232)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
🪁

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1157/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1157/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4954967)(4954967)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4954967)(4954967)-dev-release.apk)

**Pull request merged**
