### PR TITLE
[AN-4738] Send on enter with BT keyboard

### PR DESCRIPTION
**Pull request by hakonbo**
#### APK
[Download build #8020](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8020/artifact/build/artifact/wire-dev-PR363-8020.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
build again

**Comment by xuanzhaopeng** [comment]
Test it on bt keyboard, works fine when I switch to "Disable Send button",  and enter in BT keyboard works.

BUT, Text sketch will never works when I use BT keyboard. I add bug label, let @bjoernherbig to decide whether it should be fixed inside of this PR.

**Comment by bufke** [comment]
Should that apk download link work publicly? I'm happy to test it out.

**Comment by hakonbo** [comment]
@xuanzhaopeng We'll sketch out of it for now.
@bufke Thanks, but our build server and artefacts are internal only for the time being. This should make it into our next public release though.

**Pull request merged**
