### PR TITLE
Move options menu to scala

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### Note to self:
I could move the OptionsMenuFragment to the RootFragment or MainActivity so that we then only need one instance of it (would also remove some controller logic)

#### @someoneEsle 
Now should work as of Friday evening - even prevents you from blocking team members or leaving 1:1 conversations (blocking guests is still possible - but there's a bug in the conv list I think)

#### APK
[Download build #10028](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10028/artifact/build/artifact/wire-dev-PR1354-10028.apk)
[Download build #10029](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10029/artifact/build/artifact/wire-dev-PR1354-10029.apk)
[Download build #10031](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10031/artifact/build/artifact/wire-dev-PR1354-10031.apk)
[Download build #10032](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10032/artifact/build/artifact/wire-dev-PR1354-10032.apk)
[Download build #10058](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10058/artifact/build/artifact/wire-dev-PR1354-10058.apk)
[Download build #10064](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10064/artifact/build/artifact/wire-dev-PR1354-10064.apk)
  
[Download build #10066](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10066/artifact/build/artifact/wire-dev-PR1354-10066.apk)
[Download build #10067](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10067/artifact/build/artifact/wire-dev-PR1354-10067.apk)
[Download build #10147](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10147/artifact/build/artifact/wire-dev-PR1354-10147.apk)
[Download build #10148](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10148/artifact/build/artifact/wire-dev-PR1354-10148.apk)
[Download build #10149](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10149/artifact/build/artifact/wire-dev-PR1354-10149.apk)
[Download build #10152](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10152/artifact/build/artifact/wire-dev-PR1354-10152.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Bug 1
Open conversation with A. Go back to conversations list. Long tap conversations with B. Select picture. Now you see conversation with A opens right before you go full screen on the camera view (this is the first part of the bug). Take a picture. In the preview, the top bar shows A instead of B, as if you were sending to A. However, confirming sends correctly to B.

**Comment by someoneEsle** [comment]
Bug 2
Open conversation with A. go back. Long tap on B. Call. Call goes to A.

**Comment by someoneEsle** [comment]
Problem 3
I think that switching accounts is much slower than it should be. On the same phone in internal it is way faster, and I don't remember having this issue this morning while testing Maciek's pr (which is also a dev build). I think it may have something to do with opening the menu many times (?)

**Comment by deanrobertcook** [comment]
@someoneEsle bug 1 and 2 are fixed, I think bug 3 may be a memory leak that exists in master. After more testing I wasn't able to see that the options menu was causing any issues.

**Pull request merged**
