### PR TITLE
chore(dev): add tracking compose screens in datadog

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently on datadog we don't have the info about the screens on the Real User Monitoring, only Activities are logged automatically, but we have only a single activity so it doesn't give us any valuable information.

### Solutions

Unfortunately, datadog doesn't provide any fully automated solution to track views or actions for the compose, so in order to have that info we need to attach a dedicated `NavigationViewTrackingEffect` to each `NavHostController` and this PR does that. 
In order to be able to track more user actions like clicks or scrolls, we would need to attach `trackClick` to every single click and `TrackInteractionEffect` to every `InteractionSource` for scrolls, swipes, etc. We can do that in another PR if needed.

### Attachments
image

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1475/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1475/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5802014)(5802014)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5802014)(5802014)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1475/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5803677)(5803677)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5803677)(5803677)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
Great work 🚀

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1475/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5810264)(5810264)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5810264)(5810264)-staging-compat.apk)

**Pull request merged**
