### PR TITLE
feat: location replies (WPB-5480)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5480" title="WPB-5480" target="_blank">StoryWPB-5480</a>  [Android] Replies to Location - UI reply and display replies to location messages
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Location replies needs development so users can reply and visualize location replies.

### Causes (Optional)

Not implemented.

### Solutions

Implement the quoted/replies messages of location.

### Depends on

- https://github.com/wireapp/kalium/pull/2314

### Attachments

https://github.com/wireapp/wire-android/assets/5806454/21f911c9-9cc9-4f77-8cb9-0fe996cffac6

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2325](https://10.10.124.134/job/AR-build-pipeline/2325/) **failed**.

**Comment by AndroidBob** [comment]
Build [2336](https://10.10.124.134/job/AR-build-pipeline/2336/) **failed**.

**Comment by AndroidBob** [comment]
Build [2346](https://10.10.124.134/job/AR-build-pipeline/2346/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8394974)(8394974)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8394974)(8394974)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2351](https://10.10.124.134/job/AR-build-pipeline/2351/) **failed**.

**Pull request merged**
