### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3570](https://10.10.124.134/job/AR-build-pipeline/3570/) **failed**.

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3584](https://10.10.124.134/job/AR-build-pipeline/3584/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9131160)(9131160)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9131160)(9131160)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3586](https://10.10.124.134/job/AR-build-pipeline/3586/) **failed**.

**Comment by AndroidBob** [comment]
Build [3607](https://10.10.124.134/job/AR-build-pipeline/3607/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9146345)(9146345)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9146345)(9146345)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3612](https://10.10.124.134/job/AR-build-pipeline/3612/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9146955)(9146955)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9146955)(9146955)-staging-compat.apk)

**Pull request merged**
