### PR TITLE
feat: Reimplement push notification handling to make it more responsive (SQCORE-1133) (#3580)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1133" title="SQCORE-1133" target="_blank">StorySQCORE-1133</a>  [Android] Reimplement push notification handling to make it more responsive
  </td></table>
  <br />
 

* Create a new service which uses Work Manager to receive notifications (SQCORE-1136) (#3580)
* Set new token in Google API when onNewToken is called in the service
* Create a worker and send it a work request in response to a notification
* Check if the message is for a valid account
* Check if the app is killed or in background
* Fetch notifications from the backend (SQCORE-1137) (#3583)
* Making it possible to write unit tests for FCMPushHandler
* Refactoring of PushNotificationEncoded for performance and use in unit tests
* Preparing ground for unit tests for FCMPushHandler
* Notifications: Put messages (encrypted) in the Wire app database (SQCORE-1138) (#3590)
* Put messages (encrypted) in the Wire app database (SQCORE-1138) (#3590)
* Decrypt messages (SQCORE-1139) (#3595)
* Decode decrypted rows (SQCORE-1139) (#3597)
* Display the messages as notifications on the device's screen (SQCORE-1141) (#3606)
* Process the new messages when the app comes to the front + refactoring (SQCORE-1142) (#3609)
* Process the events after opening the app + refactoring
* Remove redundant and obsolete code (SQCORE-1143) (#3610)
* Cancelling notifications
* Refactoring to make initialization lighter when it's triggered by a notification (SQCORE-1146) (#3611)
* A missed call notification (SQCORE-1180)
* NotificationParser refactoring
* fixing unit tests
* feat: Show notifications when websockets are always on (SQCORE-1192)
* feat: Fix notifications sounds (SQCORE-1182)
* rewriting how notification channels are created to fix problems on Huawei
* a few tweaks to notifications visibility
* feat: Notifications: Refactor NotificationManagerWrapper (SQCORE-1199) (#3624)
* Remove NotificationData id - not used anymore
* Splitting NotificationManagerWrapper.scala into a number of smaller files
* fix: Ensure notifications are being cancelled (SQCORE-1199)
* feat: Show notifications when the app is open but on a different conversation (SQCORE-1197)
* feat: Make sure the new system works with  Federation (SQCORE-1181)
* fix: More aggressive cancelling of notifications (SQCORE-1199)
* fix: Notice changes in the availability status
* fix: Repeated missed calls notifications and calling screens

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/4/)

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/6/)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/7/)

**Comment by AndroidBob** [comment]
Build Failure
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/8/)

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/12/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/13/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/15/)

**Comment by AndroidBob** [comment]
Build Failure
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:18
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/18/)

**Comment by AndroidBob** [comment]
Build Success
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/21/)

**Comment by AndroidBob** [comment]
Build Failure
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/23/)

**Comment by AndroidBob** [comment]
Build Success
ID:24
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/24/)

**Comment by AndroidBob** [comment]
Build Failure
ID:26
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/26/)

**Comment by AndroidBob** [comment]
Build Success
ID:27
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/27/)

**Comment by AndroidBob** [comment]
Build Failure
ID:28
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/28/)

**Comment by AndroidBob** [comment]
Build Failure
ID:29
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/29/)

**Comment by AndroidBob** [comment]
Build Success
ID:30
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/30/)

**Comment by AndroidBob** [comment]
Build Success
ID:31
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/31/)

**Comment by AndroidBob** [comment]
Build Success
ID:32
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/32/)

**Comment by AndroidBob** [comment]
Build Failure
ID:34
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/34/)

**Comment by AndroidBob** [comment]
Build Success
ID:35
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/35/)

**Comment by AndroidBob** [comment]
Build Success
ID:37
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3617/37/)

**Pull request merged**
