### PR TITLE
fix: show connection request with unavailable name [WPB-6247]

### PR DESCRIPTION
**Pull request by AndroidBob**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6247" title="WPB-6247" target="_blank">BugWPB-6247</a>  [Android] Incoming connection request from offline backend not displayed when backend is available again
  </td></table>
  <br />
 

Cherry pick from the original PR: 
- #2716

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like 
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Connection requests with incomplete user data shows empty text in user name

### Solutions

When user has incomplete data show  username text

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

| Before | After |
| ----------- | ------------ |
| before  | after  |

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3186](https://10.10.124.134/job/AR-build-pipeline/3186/) **failed**.

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3205](https://10.10.124.134/job/AR-build-pipeline/3205/) **failed**.

**Comment by AndroidBob** [comment]
Build [3226](https://10.10.124.134/job/AR-build-pipeline/3226/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8940475)(8940475)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8940475)(8940475)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3318](https://10.10.124.134/job/AR-build-pipeline/3318/) **failed**.

**Pull request merged**
