### PR TITLE
fix: Fetch MLS status on every conversation opening [WPB-8610]

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-8610" title="WPB-8610" target="_blank">BugWPB-8610</a>  [Android] Every time when we open a conversation, we need to verify the conversation state
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

Every time when we open a conversation, we need to verify the conversation state

### Causes (Optional)

Was not implemented

### Solutions

Implement it, by using new kalim UseCase

### Dependencies (Optional)

waiting for kalium PR https://github.com/wireapp/kalium/pull/2701

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4127](https://10.10.124.134/job/AR-build-pipeline/4127/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.3(9387649)(9387649)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.3(9387649)(9387649)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by mchenani — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4171](https://10.10.124.134/job/AR-build-pipeline/4171/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.3(9396063)(9396063)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.3(9396063)(9396063)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4205](https://10.10.124.134/job/AR-build-pipeline/4205/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.3(9420238)(9420238)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.3(9420238)(9420238)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4208](https://10.10.124.134/job/AR-build-pipeline/4208/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.3(9420691)(9420691)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.3(9420691)(9420691)-staging-compat.apk)

**Pull request merged**
