### PR TITLE
fix: jank on scrolling [WPB-6726]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6726" title="WPB-6726" target="_blank">BugWPB-6726</a>  Image upload and download state updates makes app freeze
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

- Image upload and download state updates makes app freeze
- MostRecentMessage triggers that all conversation messages are loading without scrolling

### Causes (Optional)

- janky scrolling and app crash on freeze

### Solutions

- move update message transfer status to persistent map in view model
- change behaviour of mostRecentMessage to listen item count, not single item
- add loading placeholder with some height to not start loading all message items
- increase `INITIAL_LOAD_SIZE = 60` for better image loading on scroll

https://github.com/wireapp/wire-android/assets/13151239/37577b33-0019-4987-a8a4-233e5fb5eac5

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3242](https://10.10.124.134/job/AR-build-pipeline/3242/) **failed**.

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3302](https://10.10.124.134/job/AR-build-pipeline/3302/) **failed**.

**Comment by AndroidBob** [comment]
Build [3315](https://10.10.124.134/job/AR-build-pipeline/3315/) **failed**.

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3330](https://10.10.124.134/job/AR-build-pipeline/3330/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8996507)(8996507)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8996507)(8996507)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3331](https://10.10.124.134/job/AR-build-pipeline/3331/) **failed**.

**Pull request merged**
