### PR TITLE
ci: fix kalium reference check job syntax

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Action that checks if the the Kalium reference went backwards is failing to run

### Causes

grafik

YAML syntax sucks.

We need to replace tabs with spaces.

### Solutions

Fix identation. Maybe use [Kotlin to create GitHub actions](https://github.com/krzema12/github-actions-kotlin-dsl) in the future.

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/5/) **failed**.

**Comment by vitorhugods** [comment]
@tmspzz I tried playing around with it but to be honest I can't quite understand the `awk` commands.

But one interesting thing is that even by changing the condition:
`
if: ${{ steps.validate_kalium.outputs.is_kalium_rollback == 0 }}
`

to 

`
if: ${{ steps.validate_kalium.outputs.is_kalium_rollback == 1 }}
`

The `Leave a comment` step didn't run.

So the result of `is_kalium_rollback` is not 0 nor 1.

According to the git manual:

```
    --is-ancestor

    Check if the first is an ancestor of the second , and exit with status 0 if true,
or with status 1 if not. Errors are signaled by a non-zero status that is not 1.
```

**Errors are signaled by a non-zero status that is not 1.**

So I think something else is failing in there.

I will try not to deviate from tasks right now, but I think merging this PR would not be benefitial to us, as it would give us a false-positive that we didn't rollback Kalium.

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/7/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4238843)(4238843)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4238843)(4238843)-dev-release.apk)

**Review by MohamadJaara — DISMISSED** [review]

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4245479)(4245479)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4245479)(4245479)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4279901)(4279901)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4279901)(4279901)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4351524)(4351524)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4351524)(4351524)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4399361)(4399361)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4399361)(4399361)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/13/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4444255)(4444255)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4444255)(4444255)-dev-release.apk)

**Comment by gongracr** [comment]
Does this PR make sense anymore? can we remove it if not?

**Comment by vitorhugods** [comment]
> Does this PR make sense anymore? can we remove it if not?

The CI job is still wrong, and this PR was an attempt to fix it.

I left it open to remind ourselves that it needs fixing.

I'll spend some time on this Soon™ to fix it properly.

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/16/) **failed**.

**Comment by AndroidBob** [comment]
Build [17](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/17/) **failed**.

**Comment by AndroidBob** [comment]
Build [18](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/18/) **failed**.

**Comment by AndroidBob** [comment]
Build [21](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/21/) **failed**.

**Comment by AndroidBob** [comment]
Build [26](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/26/) **failed**.

**Comment by AndroidBob** [comment]
Build [31](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/31/) **failed**.

**Comment by AndroidBob** [comment]
Build [32](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/32/) **failed**.

**Comment by vitorhugods** [comment]
@tmspzz @MohamadJaara Sorry for the spam if you got notified about CI builds 😅, but I finally got it working!

HappinessGIF

**Comment by AndroidBob** [comment]
Build [34](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/34/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5431795)(5431795)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5431795)(5431795)-dev-compat.apk)

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [35](https://10.10.124.134/job/wire-android-reloaded/job/PR-890/35/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5432085)(5432085)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5432085)(5432085)-dev-compat.apk)

**Pull request merged**
