### PR TITLE
[AN-4801][AN-4800][AN-4804] Collections improvements

### PR DESCRIPTION
**Pull request by JPonte**
#### APK
[Download build #8348](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8348/artifact/build/artifact/wire-dev-PR537-8348.apk)
[Download build #8358](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8358/artifact/build/artifact/wire-dev-PR537-8358.apk)
[Download build #8367](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8367/artifact/build/artifact/wire-dev-PR537-8367.apk)
[Download build #8371](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8371/artifact/build/artifact/wire-dev-PR537-8371.apk)
[Download build #8374](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8374/artifact/build/artifact/wire-dev-PR537-8374.apk)
[Download build #8375](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8375/artifact/build/artifact/wire-dev-PR537-8375.apk)
[Download build #8378](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8378/artifact/build/artifact/wire-dev-PR537-8378.apk)

### CODE REVIEW

**Comment by xuanzhaopeng** [comment]
1) Tracking file on tap on file container within collection page
2) Multiple tap on file placeholder content area(Right part), will raise NPE crash, thanks @JPonte

**Comment by hakonbo** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by xuanzhaopeng** [comment]
Security issue : I can share a contact who is only a outgoing connect person

**Comment by xuanzhaopeng** [comment]
Security issue: It sends shared file to unselected contacts , by unknown reason

I long tap image and share, but in contacts selection page, I tap on "Send" button without selecting any contacts, but it still send my shared image to some "cached" users. (Some guy I shared files before).

**Pull request merged**
