### PR TITLE
Update play services version and corresponding SE

### PR DESCRIPTION
**Pull request by deanrobertcook**
@red-avtovo  please let me know when you're testing this. We need to check different play services versions and their behaviours - I'll keep an eye on the logs while we're doing so.
#### APK
[Download build #9030](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9030/artifact/build/artifact/wire-dev-PR935-9030.apk)
[Download build #9033](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9033/artifact/build/artifact/wire-dev-PR935-9033.apk)
[Download build #9040](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9040/artifact/build/artifact/wire-dev-PR935-9040.apk)
[Download build #9041](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9041/artifact/build/artifact/wire-dev-PR935-9041.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by red-avtovo** [comment]
Unable to see a popup, that asks for GPS update

**Comment by red-avtovo** [comment]
👍

**Pull request merged**
