### PR TITLE
chore: remove .debug suffix form dev builds [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

app package name have a .debug suffix which is effecting automation written for testing scala app migration 

this change ill only effect dev build

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1169/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4974247)(4974247)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4974247)(4974247)-dev-release.apk)

**Review by vitorhugods — APPROVED** [review]
> this change ill only effect dev build

It affects the _debug_ builds of all flavours.

Personally, I had the `.internal.debug` when developing locally, and `.internal` for the internal test releases.
But this won't be possible anymore and I'll switch to use `.dev` and `.internal` instead.

Which is fine from my side.

I just wanted to bring full clarity here.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1169/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4980272)(4980272)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4980272)(4980272)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1169/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5014081)(5014081)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(5014081)(5014081)-dev-release.apk)

**Pull request closed without merging**
