### PR TITLE
fix: Profile avatar not updating (WPB-5494)

### PR DESCRIPTION
**Pull request by alexandreferris**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5494" title="WPB-5494" target="_blank">BugWPB-5494</a>  [Android] Changing profile picture doesn't reflect on user profile
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When updating user profile avatar, it doesn't reflect directly on the screen

### Causes (Optional)

When updating user profile avatar, it updates the database and dataStore but we are not properly listening to it.

### Solutions

On the already existing callback when a profile avatar is changed, we return the avatar asset id and force new change.

#### Test Coverage (Optional)

- [X] I have added automated test to this contribution

#### How to Test

- Go to self user profile
- Change picture
- On user profile screen new picture is visible

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2167](https://10.10.124.134/job/AR-build-pipeline/2167/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8289508)(8289508)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8289508)(8289508)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]
🍨

**Comment by AndroidBob** [comment]
Build [2173](https://10.10.124.134/job/AR-build-pipeline/2173/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8290343)(8290343)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8290343)(8290343)-staging-compat.apk)

**Review by MohamadJaara — COMMENTED** [review]
cann't the same be achieved by observing the changes to the DB  ?

**Comment by alexandreferris** [comment]
> cann't the same be achieved by observing the changes to the DB ?

Thought directly on what we have on `fetchSelfUser()` but as it already doesn't update itself (probably because its on `WhileSubscribed`) I thought on not re-using or changing `fetchSelfUser` as I will be using only one value (avatar) and not the rest, thus just receiving what was picked previously and updating/refreshing it, but happy to change if you have an idea

**Review by MohamadJaara — APPROVED** [review]

**Pull request merged**
