### PR TITLE
refactor(dev): split click blocking flag into two - block when syncing and when connecting [AR-2693]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2693" title="AR-2693" target="_blank">BugAR-2693</a>  Can't send the message in offline mode
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Current implementation allows us to only block buttons and clicks until the app is fully synchonized.
If the message send fails, we schedule a worker to retry sending after some time or when the connection is back. At the current stage, we don't want to deal with such complex logic and just mark every message as failed to send when there's an error.

### Solutions

Expand the click blocking mechanism to add another parameter to allow buttons and clicks to be disabled when there is no connection or when the app is syncing (current flag is being split into these two cases). 
Additionally, it updates the kalium reference to use changes related to disabling resending pending messages for all messages and just mark messages as failed if the error occurs during the send, even if it's because of no network. In the near future, we will implement the manual retry mechanism for the user to send such message again.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/1591

#### How to Test

Disable the network and try to send a message.

### Attachments (Optional)

https://user-images.githubusercontent.com/30429749/227153263-79bd69bc-6e86-46f6-93d0-397a5da8acf1.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1573/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1573/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6059750)(6059750)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6059750)(6059750)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1573/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6067982)(6067982)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6067982)(6067982)-staging-compat.apk)

**Review by gongracr — APPROVED** [review]
Well done Mr. Michal, aka, the UI Wizard 👨‍🎨 ✨

**Comment by gongracr** [comment]
And just for clarification, we didn't disable any pending messages resend, you just disabled the ability to send messages and other actions if there is no connectivity. 
But if the message or other action actually takes place and makes an API request to the backend resulting in an error, the message will try to be resend via the message sender "under the hood" mechanism that is still in place right?

**Comment by saleniuk** [comment]
> And just for clarification, we didn't disable any pending messages resend, you just disabled the ability to send messages and other actions if there is no connectivity. But if the message or other action actually takes place and makes an API request to the backend resulting in an error, the message will try to be resend via the message sender "under the hood" mechanism that is still in place right?

I actually disabled it in the corresponding kalium PR: https://github.com/wireapp/kalium/pull/1591
That's why I also mentioned it in this PR as it updates the kalium reference to this one. In the kalium PR I removed usage of `sendPendingMessage` in favour of `sendMessage` and persisting the failed message state if there was an error. 😉

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1573/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6096501)(6096501)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6096501)(6096501)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1573/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6105466)(6105466)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6105466)(6105466)-staging-compat.apk)

**Pull request merged**
