### PR TITLE
Notifications: Remove redundant and obsolete code (SQCORE-1143)

### PR DESCRIPTION
**Pull request by makingthematrix**
https://wearezeta.atlassian.net/browse/SQCORE-1143

Cutting out the old notifications classes, DB entities, etc.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3610/1/)

**Review by mdimjasevic — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3610/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3610/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3610/2/)

**Pull request merged**
