### PR TITLE
[AN-5522][AN-5552][AN-5609][AN-5592] Notifications and Calling

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### Notifications:
 - notifications for different accounts will now be placed in their own tray - click on the tray should take you to that account
 - notifications for **other** accounts will appear even when the app is open
 - quick reply (should also work inside the app)
 - quick call from notifications
 - swiping away notifications prevents them from coming back
 - reading notifications on another device prevents sounds from playing (for 1 minute)
 - sounds/vibrations
 - calling notifications should now be displayed properly. There should always be one in the system tray if there is an active call. There are also two types: incoming and ongoing with appropriate commands

#### Calling: 
 - calling between multiple accounts (calling in general)
 - after hanging up a call while receiving another incoming call (either from this account or another), the user should be shown this new call immediately - except for group calls that have been going on for longer than 30 seconds, then they should no longer be considered incoming.
 

#### APK
[Download build #9387](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9387/artifact/build/artifact/wire-dev-PR1093-9387.apk)
[Download build #9391](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9391/artifact/build/artifact/wire-dev-PR1093-9391.apk)
[Download build #9396](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9396/artifact/build/artifact/wire-dev-PR1093-9396.apk)
[Download build #9406](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9406/artifact/build/artifact/wire-dev-PR1093-9406.apk)
[Download build #9407](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9407/artifact/build/artifact/wire-dev-PR1093-9407.apk)
[Download build #9414](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9414/artifact/build/artifact/wire-dev-PR1093-9414.apk)
[Download build #9418](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9418/artifact/build/artifact/wire-dev-PR1093-9418.apk)
[Download build #9419](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9419/artifact/build/artifact/wire-dev-PR1093-9419.apk)
[Download build #9420](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9420/artifact/build/artifact/wire-dev-PR1093-9420.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
build again

**Comment by someoneEsle** [comment]
Overall, the app built from this PR is very slow and buggy (sometimes not very responsive when performing simple tasks such as opening a conversation). Some main functionalities appear to be broken so I kept the tests very simple for now -- all the devices I used to test were logged in with only one account. I think most of these issues are intertwined, so that fixing some will fix all of them.

Bug 1
- logged in with only 1 account -- a personal one
- app is in foreground
- receive message "abc" from A
- open conversation with A. (optional) reply to their message
- minimize the app
- a notification from A containing message "abc" is shown

Bug 2
- when I answer a video call, I should be prompted to grant camera access if I have never done that (this may be unrelated to this PR)

Bug 3
Many messages/notifications get lost when the app slows down. I am pretty sure this is related to bug 1.

Bug 4
Typing indicator is broken. Users appear to be typing even when the app is not open

Bug 5
I cannot reproduce, but this has happened when opening a conversation. None of the messages in that conversation had ever been edited at any point.
wire 2017-09-04 at 16 30 54

Bug 6
Notifications when the app isn't in foreground are usually not delivered


By the way, the console in Android Studio is set to "error", but its output goes so fast that it's showing a warning "too much output to process". I am not using the app, it is not in foreground nor in background, and it is not receiving notifications. But it is still keeping the console very busy.

I will stop here for now. :)

**Comment by someoneEsle** [comment]
Bug 7
- account is logged in with personal account P and team account T
- focus is on team account
- I receive messages "P1" and "P2" from personal account. Notifications are displayed correctly
- I receive message "T1" from team account. Notification for message "P2" is shown

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
Bug 8
- I received "T1" and "P1" from team and personal accounts respectively
- I use quick reply for "T1"
- notification for "P1" is wiped too

**Comment by someoneEsle** [comment]
Bug 9
- focus on personal account
- receive "T1" from teams account
- tap quick reply
- tap open wire
- user is taken to personal account instead of team one

**Comment by someoneEsle** [comment]
Bug 10
- A calls B, A picks up the phone. They are now in a call
- C calls a group chat with A in it
- While the call to the group chat is still in "ringing phase", A hangs up their current phone. Now A sees the incoming call from the group, but there are no buttons to accept the call

**Pull request merged**
