### PR TITLE
[AN-4584, AN-4586] Removes invisible message footer status in RTL and incorrect ellipsizing of footer status and

### PR DESCRIPTION
**Pull request by shumengye**
#### Description

Checked that this doesn't interfere with like chatheads

#### Ticket
https://wearezeta.atlassian.net/browse/AN-4584
#### APK
[Download build #7714](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7714/artifact/build/artifact/wire-dev-PR239-7714.apk)
[Download build #7717](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7717/artifact/build/artifact/wire-dev-PR239-7717.apk)
[Download build #7719](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7719/artifact/build/artifact/wire-dev-PR239-7719.apk)
[Download build #7728](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7728/artifact/build/artifact/wire-dev-PR239-7728.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
Can you quickly check that this looks alright for RTL languages as well, please?

**Comment by hakonbo** [comment]
build again

**Comment by mykola-mokhnach** [comment]
This looks good with LTR locales, but I cannot check it with RTL stuff - Arabic is not included to the list of supported OS languages on my test phone :(

**Comment by vova-lohika** [comment]
fine on العربية

**Pull request merged**
