### PR TITLE
Refactor build scripts and bump plugin versions

### PR DESCRIPTION
**Pull request by CalumMcCall**
#### APK
[Download build #11553](http://192.168.10.18:8080/job/Pull%20Request%20Builder/11553/artifact/build/artifact/wire-dev-PR1727-11553.apk)
[Download build #11554](http://192.168.10.18:8080/job/Pull%20Request%20Builder/11554/artifact/build/artifact/wire-dev-PR1727-11554.apk)

### CODE REVIEW

**Comment by CalumMcCall** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Pull request merged**
