### PR TITLE
feat: Dialog informin conversation was degraded (WPB-1771)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-1771" title="WPB-1771" target="_blank">StoryWPB-1771</a>  [Proteus] Add dialog to confirm sending a message in a degraded conversation 
  </td></table>
  <br />
 

# What's new in this PR?

When the conversation's verification was degraded and user wants to send a message or start a call, app should show "Are you sure" dialog.

### Attachments (Optional)

Screenshot 2023-11-15 at 14 31 09

Screenshot 2023-11-15 at 14 31 26

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1847](https://10.10.124.134/job/AR-build-pipeline/1847/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1855](https://10.10.124.134/job/AR-build-pipeline/1855/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8109443)(8109443)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8109443)(8109443)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
🛡️👀

**Comment by AndroidBob** [comment]
Build [1873](https://10.10.124.134/job/AR-build-pipeline/1873/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8124675)(8124675)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8124675)(8124675)-staging-compat.apk)

**Pull request merged**
