### PR TITLE
fix: add migration errors, fallback mechanism, manual trigger and other missing fixes on develop

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This PR contains changes from all 6 migration related PRs already approved and merged to release/candidate:
https://github.com/wireapp/wire-android-reloaded/pull/1474
https://github.com/wireapp/wire-android-reloaded/pull/1482
https://github.com/wireapp/wire-android-reloaded/pull/1486
https://github.com/wireapp/wire-android-reloaded/pull/1485
https://github.com/wireapp/wire-android-reloaded/pull/1499
https://github.com/wireapp/wire-android-reloaded/pull/1503
https://github.com/wireapp/wire-android-reloaded/pull/1508

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1507/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1507/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5861193)(5861193)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5861193)(5861193)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1507/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5861476)(5861476)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5861476)(5861476)-staging-compat.apk)

**Review by tmspzz — APPROVED** [review]

**Review by MohamadJaara — CHANGES_REQUESTED** [review]
one PR is missing i will add it and merge

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1507/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5862002)(5862002)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5862002)(5862002)-staging-compat.apk)

**Pull request merged**
