### PR TITLE
Linear group creation flow

### PR DESCRIPTION
**Pull request by deanrobertcook**
Currently, the buttons for creating a group and adding to the conversation are disabled
#### APK
[Download build #10210](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10210/artifact/build/artifact/wire-dev-PR1412-10210.apk)
[Download build #10211](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10211/artifact/build/artifact/wire-dev-PR1412-10211.apk)
[Download build #10212](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10212/artifact/build/artifact/wire-dev-PR1412-10212.apk)
[Download build #10213](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10213/artifact/build/artifact/wire-dev-PR1412-10213.apk)
[Download build #10214](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10214/artifact/build/artifact/wire-dev-PR1412-10214.apk)
[Download build #10216](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10216/artifact/build/artifact/wire-dev-PR1412-10216.apk)
[Download build #10218](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10218/artifact/build/artifact/wire-dev-PR1412-10218.apk)
[Download build #10223](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10223/artifact/build/artifact/wire-dev-PR1412-10223.apk)
[Download build #10224](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10224/artifact/build/artifact/wire-dev-PR1412-10224.apk)
[Download build #10230](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10230/artifact/build/artifact/wire-dev-PR1412-10230.apk)
[Download build #10231](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10231/artifact/build/artifact/wire-dev-PR1412-10231.apk)
[Download build #10232](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10232/artifact/build/artifact/wire-dev-PR1412-10232.apk)
[Download build #10235](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10235/artifact/build/artifact/wire-dev-PR1412-10235.apk)
[Download build #10236](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10236/artifact/build/artifact/wire-dev-PR1412-10236.apk)
[Download build #10240](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10240/artifact/build/artifact/wire-dev-PR1412-10240.apk)
[Download build #10241](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10241/artifact/build/artifact/wire-dev-PR1412-10241.apk)
[Download build #10244](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10244/artifact/build/artifact/wire-dev-PR1412-10244.apk)
[Download build #10245](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10245/artifact/build/artifact/wire-dev-PR1412-10245.apk)
[Download build #10247](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10247/artifact/build/artifact/wire-dev-PR1412-10247.apk)
[Download build #10248](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10248/artifact/build/artifact/wire-dev-PR1412-10248.apk)
[Download build #10250](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10250/artifact/build/artifact/wire-dev-PR1412-10250.apk)
[Download build #10251](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10251/artifact/build/artifact/wire-dev-PR1412-10251.apk)
[Download build #10255](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10255/artifact/build/artifact/wire-dev-PR1412-10255.apk)
[Download build #10256](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10256/artifact/build/artifact/wire-dev-PR1412-10256.apk)
[Download build #10258](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10258/artifact/build/artifact/wire-dev-PR1412-10258.apk)
[Download build #10261](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10261/artifact/build/artifact/wire-dev-PR1412-10261.apk)
[Download build #10262](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10262/artifact/build/artifact/wire-dev-PR1412-10262.apk)
[Download build #10264](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10264/artifact/build/artifact/wire-dev-PR1412-10264.apk)
[Download build #10265](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10265/artifact/build/artifact/wire-dev-PR1412-10265.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
- [ ] Bug 1
The Skip button doesn't always turn into Done -- not sure what triggers this bug but it's definitely happening more than 50% of the time when running C652376

**Comment by someoneEsle** [comment]
- [ ] Bug 2
Every time I select a contact, the second half of the people in the contacts list flickers.

**Comment by someoneEsle** [comment]
- [ ] Bug 3
There should be no Call button in an empty group conversation with myself only.

- [ ] Bug 4
After creating a group conversation with myself only, I shouldn't see "everyone left" as subtitle in the conversations list

**Comment by someoneEsle** [comment]
- [ ] Bug 5
The transition between the add people page and the conversation view is not smooth

**Comment by someoneEsle** [comment]
- [ ] Bug 6
Starting the flow from 1:1 (only after fresh install?) takes you straight to add people page without asking you to set a group name.  Run C652363

**Comment by someoneEsle** [comment]
- [ ] Bug 7
"All fingerprints verified" message should appear after the system messages we use for group creation. Right now it appears in the middle. 
wire 2018-02-13 at 13 54 24

**Comment by someoneEsle** [comment]
- [ ] Bug 8
Have a groupchat G. Open it, tap top toolbar, add people. Now there are two problems:
- you can't go back
- the ADD MEMBERS at the top is not being updated as you select people

**Comment by someoneEsle** [comment]
- [ ] Bug 9
When I'm typing the group name (or selecting people) and I hit the "send" button on the keyboard, I expect the app to go to the next page

**Comment by someoneEsle** [comment]
- [ ] Bug 10
The copy for the button in the start UI is wrong
Note to self and to the devs: check the copy everywhere else in the specs

**Comment by someoneEsle** [comment]
- [ ] Bug 11
Create group with A and B. System message says "you added A and B". Now remove A. System message changes to "you added B" (it should stay the same). run C686

**Comment by someoneEsle** [comment]
- [ ] Bug 12
"You removed X" from conversation should be uppercase. I suspect other system messages similar to this one may also not be uppercase anymore (like YOU ADDED or YOU LEFT)

**Comment by someoneEsle** [comment]
- [ ] Bug 13
Why is the "next" button purple? Same for skip and done

**Comment by someoneEsle** [comment]
- [ ] Bug 13
When I create a group conversation from the webapp (with the new flow) using user A, and invite my android phone with user B, then I open the group chat and I see a system message "A renamed the conversation <conversationName>" and then "A started a conversation with ... ".
On top of that, A had sent a message to the group chat before I opened it, and the message now appears before the system messages.

**Comment by someoneEsle** [comment]
- [ ] Bug 13
I'm using a personal account. I open search UI. Deny contacts permission (not forever). Create group, add people, finish flow. Now you see the permission dialogue again.

**Pull request merged**
