### PR TITLE
Bump AVS to 3.8.26.

### PR DESCRIPTION
**Pull request by jspittka**
#### APK
[Download build #9850](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9850/artifact/build/artifact/wire-dev-PR1293-9850.apk)
[Download build #9853](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9853/artifact/build/artifact/wire-dev-PR1293-9853.apk)
[Download build #9858](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9858/artifact/build/artifact/wire-dev-PR1293-9858.apk)
[Download build #9866](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9866/artifact/build/artifact/wire-dev-PR1293-9866.apk)
[Download build #9871](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9871/artifact/build/artifact/wire-dev-PR1293-9871.apk)
[Download build #9872](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9872/artifact/build/artifact/wire-dev-PR1293-9872.apk)
[Download build #9882](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9882/artifact/build/artifact/wire-dev-PR1293-9882.apk)
[Download build #9883](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9883/artifact/build/artifact/wire-dev-PR1293-9883.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
Build again

**Comment by jspittka** [comment]
Build again

**Comment by jspittka** [comment]
Build again

**Comment by jspittka** [comment]
Build again

**Comment by jspittka** [comment]
Build again

**Comment by jspittka** [comment]
Build again

**Pull request closed without merging**
