### PR TITLE
fix: call still ringing despite that the caller already ended the call (AR-3046)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3046" title="AR-3046" target="_blank">BugAR-3046</a>  Applause - [SG A52s/A.13] 1:1 Chat - Call still ringing despite that the caller already ended the call
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

1. Call still ringing despite that the caller already ended the call when the app is in the background.

Some other related issues:

2. Sometimes not receiving incoming calls (App in Background)
3. Sometimes receiving incoming calls with some delay (App in Background)

### Causes (Optional)
For issues 1, 2 and 3 :
Some calling events got ignored.

**Why?**

When the app is in the background and we receive a push notification, we enqueue a work to `NotificationFetchWorker` to fetch data and open websocket.
In some cases, the workManager got busy for a long time by an old work and any new event coming will be ignored until the current one is done(WorkPolicy is KEEP).  --> So the WebSocket will not open in time and AVS will probably miss some events to trigger endCall or IncomingCall callbacks.

This happens mainly due to ` checkCallsNotificationOnceJob()` function that is taking sometimes long time to complete inner job causing the workManager to stay on running state.

### Solutions

We are observing incoming calls in 2 places: in `GlobalObserversManager` and `WireNotificationManager`, so I kept observing calls from `GlobalObserversManager` only.

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1575/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1575/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6062311)(6062311)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6062311)(6062311)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1575/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6067977)(6067977)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6067977)(6067977)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1575/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6070474)(6070474)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6070474)(6070474)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]

**Pull request merged**
