### PR TITLE
CallingFragment

### PR DESCRIPTION
**Pull request by makingthematrix**
Feel free to merge it to multi_tasking when you're ready. 
#### APK
[Download build #10842](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10842/artifact/build/artifact/wire-dev-PR1555-10842.apk)
[Download build #10845](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10845/artifact/build/artifact/wire-dev-PR1555-10845.apk)
[Download build #10846](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10846/artifact/build/artifact/wire-dev-PR1555-10846.apk)
[Download build #10847](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10847/artifact/build/artifact/wire-dev-PR1555-10847.apk)
[Download build #10856](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10856/artifact/build/artifact/wire-dev-PR1555-10856.apk)
[Download build #10857](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10857/artifact/build/artifact/wire-dev-PR1555-10857.apk)
[Download build #10859](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10859/artifact/build/artifact/wire-dev-PR1555-10859.apk)
[Download build #10873](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10873/artifact/build/artifact/wire-dev-PR1555-10873.apk)
[Download build #10874](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10874/artifact/build/artifact/wire-dev-PR1555-10874.apk)
[Download build #10875](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10875/artifact/build/artifact/wire-dev-PR1555-10875.apk)
[Download build #10876](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10876/artifact/build/artifact/wire-dev-PR1555-10876.apk)
[Download build #10885](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10885/artifact/build/artifact/wire-dev-PR1555-10885.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Receive an incoming call. Before you see the buttons to accept/reject the call, you briefly see the button to decline somewhere in the center/bottom part of the screen

**Comment by someoneEsle** [comment]
- [ ] Bug 2
Bring back the subtitle on incoming calls/video calls (e.g. "calling..." during audio calls)

**Comment by someoneEsle** [comment]
- [ ] Bug 3
I am not asked for microphone permissions when accepting a call

**Comment by someoneEsle** [comment]
- [ ] Bug 4
(audio call) The speaker button does not turn on when I tap it

**Comment by someoneEsle** [comment]
- [ ] Bug 5
I have to tap back twice to multitask (instead of just once)

**Comment by someoneEsle** [comment]
- [ ] Bug 6
Tapping the screen doesn't bring up the controls

**Comment by makingthematrix** [comment]
Bug 1, 2, 4, and 6, should be fixed.

**Comment by deanrobertcook** [comment]
all code has been merged into: https://github.com/wireapp/wire-android/pull/1567

will move bugs there

**Pull request closed without merging**
