### PR TITLE
[AN-4362] Delete message for everyone

### PR DESCRIPTION
**Pull request by hakonbo**
Removes old multi select
Adds new menu for actions on a single message

#### APK
[Download build #7335](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7335/artifact/build/artifact/wire-dev-PR37-7335.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
lgtm

**Comment by mykola-mokhnach** [comment]
Transitioning effect is confusing if I long tap a message in the conversation view and on-screen keyboard is visible at the same time.

**Comment by mykola-mokhnach** [comment]
No "Delete for Everyone" option is present in the long tap menu for video messages

**Comment by zbsz** [comment]
I'd suggest to update to latest SE: 76.1156 it changes handling on our side quite a lot, although API is unchanged, so should not require any changes on UI

**Comment by xuanzhaopeng** [comment]
Delete text message everywhere, then it show Error - message type 'RECALLED' unknown.

(Android 4.4.2 Xiaomi MI 3W, API 19)

**Comment by hakonbo** [comment]
Updated SE to 76.1156
Allowed delete for Video messages

**Comment by xuanzhaopeng** [comment]
Touch area should be like this.

screen shot 2016-08-12 at 17 04 26

**Comment by hakonbo** [comment]
build again

**Pull request merged**
