### PR TITLE
fix: The displayed timestamp of the quote should switch between time and date/time

### PR DESCRIPTION
**Pull request by makingthematrix**
Currently the quotes show only the time. The way date/time is displayed should be consistent with how we display it in other places in the Android app (eg. in separators between messages in the conversation view).

Testing hints:
Check how the date and time of the quote is displayed in replies from today and previous days.
#### APK
[Download build #12113](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12113/artifact/build/artifact/wire-dev-PR1884-12113.apk)
[Download build #12124](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12124/artifact/build/artifact/wire-dev-PR1884-12124.apk)
[Download build #12136](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12136/artifact/build/artifact/wire-dev-PR1884-12136.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
build again

**Comment by red-avtovo** [comment]
Bug 1: timestamp is not updated automatically. Needed to restart the app
766cb76e-8753-49fe-b37f-4130f5d2a709

**Comment by makingthematrix** [comment]
The timestamp update happens only when there is some activity in the conversation and the message with the timestamp gets recycled and displayed again. But this is also what happens with the timestamps on separators between messages, so I think it's sufficient.

**Comment by red-avtovo** [comment]
lgtm

**Pull request merged**
