### PR TITLE
refactor: customization file support

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This is cherry-picked from the following PR:
- #1652 

> **Note**: A small merge conflict was found in the `default.json`, so that should be the only difference.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1660/1/) **failed**.

**Comment by vitorhugods** [comment]
> @vitorhugods looks like you are rolling back kalium to a previous commitish.
> 
> This means that the PR's target branch (develop) is using a newer version of Kalium, and the changes in this PR will rollback Kalium to an older version.
> develop 	This PR
> [fbc9bba563c857b62d85b8b52dfd27a03cb1de96](https://github.com/wireapp/kalium/tree/fbc9bba563c857b62d85b8b52dfd27a03cb1de96) 	[e5396d33b92f8213b7270dfac00c6dee9a685bd7](https://github.com/wireapp/kalium/tree/e5396d33b92f8213b7270dfac00c6dee9a685bd7)
> 
> Is this intentional?

Thanks for saving me, dear bot.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1660/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6234100)(6234100)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6234100)(6234100)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Review by trOnk12 — APPROVED** [review]

**Pull request merged**
