### PR TITLE
Team only toggle and participant list rewrite

### PR DESCRIPTION
**Pull request by makingthematrix**
#### APK
[Download build #10312](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10312/artifact/build/artifact/wire-dev-PR1424-10312.apk)
[Download build #10313](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10313/artifact/build/artifact/wire-dev-PR1424-10313.apk)
[Download build #10317](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10317/artifact/build/artifact/wire-dev-PR1424-10317.apk)
[Download build #10318](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10318/artifact/build/artifact/wire-dev-PR1424-10318.apk)
[Download build #10325](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10325/artifact/build/artifact/wire-dev-PR1424-10325.apk)
[Download build #10329](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10329/artifact/build/artifact/wire-dev-PR1424-10329.apk)
[Download build #10330](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10330/artifact/build/artifact/wire-dev-PR1424-10330.apk)
[Download build #10335](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10335/artifact/build/artifact/wire-dev-PR1424-10335.apk)
[Download build #10336](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10336/artifact/build/artifact/wire-dev-PR1424-10336.apk)
[Download build #10339](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10339/artifact/build/artifact/wire-dev-PR1424-10339.apk)
[Download build #10340](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10340/artifact/build/artifact/wire-dev-PR1424-10340.apk)
[Download build #10341](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10341/artifact/build/artifact/wire-dev-PR1424-10341.apk)
[Download build #10342](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10342/artifact/build/artifact/wire-dev-PR1424-10342.apk)
[Download build #10343](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10343/artifact/build/artifact/wire-dev-PR1424-10343.apk)
[Download build #10344](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10344/artifact/build/artifact/wire-dev-PR1424-10344.apk)
[Download build #10345](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10345/artifact/build/artifact/wire-dev-PR1424-10345.apk)
[Download build #10346](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10346/artifact/build/artifact/wire-dev-PR1424-10346.apk)
[Download build #10347](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10347/artifact/build/artifact/wire-dev-PR1424-10347.apk)
[Download build #10350](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10350/artifact/build/artifact/wire-dev-PR1424-10350.apk)
[Download build #10352](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10352/artifact/build/artifact/wire-dev-PR1424-10352.apk)
[Download build #10353](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10353/artifact/build/artifact/wire-dev-PR1424-10353.apk)
[Download build #10354](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10354/artifact/build/artifact/wire-dev-PR1424-10354.apk)
[Download build #10355](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10355/artifact/build/artifact/wire-dev-PR1424-10355.apk)
[Download build #10356](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10356/artifact/build/artifact/wire-dev-PR1424-10356.apk)
[Download build #10357](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10357/artifact/build/artifact/wire-dev-PR1424-10357.apk)
[Download build #10360](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10360/artifact/build/artifact/wire-dev-PR1424-10360.apk)
[Download build #10363](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10363/artifact/build/artifact/wire-dev-PR1424-10363.apk)
[Download build #10364](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10364/artifact/build/artifact/wire-dev-PR1424-10364.apk)
[Download build #10366](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10366/artifact/build/artifact/wire-dev-PR1424-10366.apk)
[Download build #10367](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10367/artifact/build/artifact/wire-dev-PR1424-10367.apk)
[Download build #10368](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10368/artifact/build/artifact/wire-dev-PR1424-10368.apk)
[Download build #10369](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10369/artifact/build/artifact/wire-dev-PR1424-10369.apk)
[Download build #10370](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10370/artifact/build/artifact/wire-dev-PR1424-10370.apk)
[Download build #10371](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10371/artifact/build/artifact/wire-dev-PR1424-10371.apk)
[Download build #10372](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10372/artifact/build/artifact/wire-dev-PR1424-10372.apk)
[Download build #10373](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10373/artifact/build/artifact/wire-dev-PR1424-10373.apk)
[Download build #10378](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10378/artifact/build/artifact/wire-dev-PR1424-10378.apk)
[Download build #10379](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10379/artifact/build/artifact/wire-dev-PR1424-10379.apk)

### CODE REVIEW

**Comment by makingthematrix** [comment]
build again

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Opening a wireless guest's profile details view shows no avatar, no devices tab, and shows a connect button

**Comment by someoneEsle** [comment]
- [ ] Bug 2
Statuses are missing from the group participants list

**Comment by someoneEsle** [comment]
- [ ] Bug 3
If I do not Allow guests during group creation, I should not see guests on Add people page

**Comment by someoneEsle** [comment]
- [ ] Bug 4
After logging in I do not see any of my 1:1 conversations in teams in the conversations list. (Internal works fine)

**Comment by someoneEsle** [comment]
- [ ] Bug 5
Open group chat. Tap participant A. Tap devices tab. Tap back arrow in the top left corner. Now the app goes back to "Details" tab instead of going back to group info page

**Comment by someoneEsle** [comment]
- [ ] Bug 6
OPen group chat, tap participant. The top bar with the name is huge. Check with design

**Comment by someoneEsle** [comment]
- [ ] Bug 7
A guest's participant details should have no guest label, but the new guest icon instead

**Comment by someoneEsle** [comment]
- [ ] Bug 8
When tapping a contact in the participant list, the transition is not smooth at all -- I think that for a split second it's loading the previous contact you tapped, and then updates to the one you just tapped

**Comment by someoneEsle** [comment]
- [ ] Bug 9
Conversation name should have its own cell on Group info page, and should not be in the top bar

**Comment by someoneEsle** [comment]
- [ ] Bug 10
Personal users should not be able to see statuses in the participants list

**Comment by someoneEsle** [comment]
- [ ] Bug 11
Personal accounts shouldn't have the option to "Allow guests" when creating a group...

**Comment by someoneEsle** [comment]
- [ ] Bug 12
I should not be able to find a Wireless user in Search UI

**Comment by someoneEsle** [comment]
- [ ] Bug 13
The Verified/not verified toggle when verifying a device doesn't have an ID anymore C652394

**Comment by someoneEsle** [comment]
- [ ] Bug 14
Guests do not see Bots as members of the group conversation C651488

**Comment by someoneEsle** [comment]
- [ ] Bug 15
The rows on Add people page are not tappable anymore -- only the checkboxes are

**Comment by someoneEsle** [comment]
- [ ] Bug 16
Switching the toggle while in airplane mode does not trigger an error message

**Comment by someoneEsle** [comment]
- [ ] Bug 17
Wireless guests have a black avatar in participants list

**Comment by someoneEsle** [comment]
- [ ] Bug 18
It should be PEOPLE (x) and SERVICES (x) in capital letters on group info page

**Comment by someoneEsle** [comment]
- [ ] Bug 19
create group. type name. select 2 guests on add people page. go back. turn off "allow guests". confirm. Now you see the two guests in the search bar but you don't see them in the list

**Comment by someoneEsle** [comment]
- [ ] Bug 20
Trying to disable the Allow guests toggle in Guests options page results in 2 error alerts being generated

**Comment by someoneEsle** [comment]
- [ ] Bug 21
When I select a contact on Add people page, the order of the contacts changes (?)

**Comment by someoneEsle** [comment]
- [ ] Bug 22
I should not see "Guests are present" banner in 1:1 convs

**Comment by someoneEsle** [comment]
- [ ] Bug 23
The pencil in the "ConversationName" row on Group info page should be tappable. Otherwise it's not clear how you can rename the conversation

**Comment by someoneEsle** [comment]
- [ ] Bug 24
Bots are not kicked out of the conversation when I switch guests toggle off

**Comment by someoneEsle** [comment]
- [ ] Bug 25
There should be a guest icon, not label, when you open Details view with a guest (I remember you saying it had not been implemented yet a few days ago, but I guess it should be in by now)

**Comment by someoneEsle** [comment]
- [ ] Bug 26
id='empty_group_watermark'

**Comment by someoneEsle** [comment]
- [ ] Bug 27
There is no username on 1:1 details view page

**Comment by someoneEsle** [comment]
- [ ] Bug 28
I'm a personal account. I have GroupChat with A and B, where B is a user I'm not connected to. I open groupchat, tap top toolbar, tap participant B --> I see an empty page, kind of like bug 1.

**Comment by someoneEsle** [comment]
- [ ] Bug 29
There should be a verified shield in the conversation title row (latest from design) C652384

**Pull request merged**
