### PR TITLE
chore: Bump AVS to experimental version

### PR DESCRIPTION
**Pull request by JPonte**
#### APK
[Download build #11847](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11847/artifact/build/artifact/wire-dev-PR1831-11847.apk)

### CODE REVIEW

**Comment by JPonte** [comment]
build again

**Comment by someoneEsle** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
No connecting problems on wifi/4g, 1:1/groups

**Pull request closed without merging**
