### PR TITLE
feat: removing devices from details screen (AR-2963)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2963" title="AR-2963" target="_blank">StoryAR-2963</a>  Delete a device from the devices list
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Deleting a device from settings was not being made from device details screen.
So this adds this device details screen, and execute the action of deletion from there. 

**_NOTE:_** As this was developed prev. with a wrong flow, the first commit of this PR is a revert, hence the large amount of files touched.

### Dependencies (Optional)
https://github.com/wireapp/kalium/pull/1513

Needs releases with:

- [x] GitHub link to other pull request

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

### Attachments (Optional)

https://user-images.githubusercontent.com/5806454/219745063-5cdd6832-5e5b-4a57-85c4-b12148be2f4c.mov

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1470/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5769217)(5769217)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5769217)(5769217)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1470/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5784608)(5784608)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5784608)(5784608)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1470/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5785856)(5785856)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5785856)(5785856)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM 🚀

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1470/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5792221)(5792221)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5792221)(5792221)-staging-compat.apk)

**Pull request merged**
