### PR TITLE
[WIP] Android 8 changes

### PR DESCRIPTION
**Pull request by JPonte**
fixes https://github.com/wireapp/android-project/issues/246
fixes https://github.com/wireapp/android-project/issues/252
fixes https://github.com/wireapp/android-project/issues/230
fixes https://github.com/wireapp/android-project/issues/241

Will also fix the "crash in the background" issue on internet connectivity changes
#### APK
[Download build #11607](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11607/artifact/build/artifact/wire-dev-PR1770-11607.apk)
[Download build #11610](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11610/artifact/build/artifact/wire-dev-PR1770-11610.apk)
[Download build #11620](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11620/artifact/build/artifact/wire-dev-PR1770-11620.apk)
[Download build #11621](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11621/artifact/build/artifact/wire-dev-PR1770-11621.apk)
[Download build #11622](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11622/artifact/build/artifact/wire-dev-PR1770-11622.apk)
[Download build #11625](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11625/artifact/build/artifact/wire-dev-PR1770-11625.apk)
[Download build #11628](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11628/artifact/build/artifact/wire-dev-PR1770-11628.apk)
[Download build #11632](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11632/artifact/build/artifact/wire-dev-PR1770-11632.apk)
[Download build #11633](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11633/artifact/build/artifact/wire-dev-PR1770-11633.apk)
[Download build #11634](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11634/artifact/build/artifact/wire-dev-PR1770-11634.apk)
[Download build #11635](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11635/artifact/build/artifact/wire-dev-PR1770-11635.apk)
[Download build #11636](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11636/artifact/build/artifact/wire-dev-PR1770-11636.apk)
[Download build #11638](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11638/artifact/build/artifact/wire-dev-PR1770-11638.apk)
[Download build #11639](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11639/artifact/build/artifact/wire-dev-PR1770-11639.apk)
[Download build #11642](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11642/artifact/build/artifact/wire-dev-PR1770-11642.apk)
[Download build #11643](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11643/artifact/build/artifact/wire-dev-PR1770-11643.apk)
[Download build #11644](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11644/artifact/build/artifact/wire-dev-PR1770-11644.apk)
[Download build #11645](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11645/artifact/build/artifact/wire-dev-PR1770-11645.apk)
[Download build #11646](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11646/artifact/build/artifact/wire-dev-PR1770-11646.apk)
[Download build #11647](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11647/artifact/build/artifact/wire-dev-PR1770-11647.apk)
[Download build #11648](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11648/artifact/build/artifact/wire-dev-PR1770-11648.apk)
[Download build #11649](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11649/artifact/build/artifact/wire-dev-PR1770-11649.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Wire does not play the default notification sound after a fresh install. It plays the samsung sound, even though in the settings it's set to Wire default.

**Comment by someoneEsle** [comment]
- [ ] Bug 2
add support for different notification sounds for multiple accounts

- [ ] Bug 3
I don't get incoming calls unless I have the app open. Also, there is no notification for ongoing calls.

**Comment by someoneEsle** [comment]
- [ ] Bug 4
Setting custom notification sounds doesn't work. The app keeps playing the default one

**Comment by someoneEsle** [comment]
- [ ] Bug 5
After a fresh install, vibration in Settings>Option is off by default. However the phone vibrates on incoming messages

**Comment by someoneEsle** [comment]
- [ ] Bug 6
I'm in a call with A. B calls me. I do not hear the sound of the incoming call from B/I don't have a notification for it.

**Comment by someoneEsle** [comment]
- [ ] Note to self
Test on 4.4 when things are more stable

**Comment by someoneEsle** [comment]
- [ ] Bug 7 - No notifications from inactive account when websocket is off
(phone without FCM)
Log in with two accounts, A and B.
Turn off websocket option.
Open any conversation in A.
Receive a message in B.
No notification is displayed.

**Comment by someoneEsle** [comment]
- [ ] Bug 8
S8, build 11633. I do not receive any notifications anymore when the app is minimized. I don't even have to kill the app, minimizing is enough to not receive notifications anymore.

**Comment by makingthematrix** [comment]
On Android 8, if `WebSocketBroadcastReceiver` tries to start `WebSocketService` with just `startService` we get 
```
09-06 16:35:35.140 5269-5269/com.waz.zclient.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.waz.zclient.dev, PID: 5269
    java.lang.RuntimeException: Unable to start receiver com.waz.services.websocket.WebSocketBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.waz.zclient.dev/com.waz.services.websocket.WebSocketService }: app is in background uid UidRecord{46f0edd u0a173 TRNB idle procs:1 seq(0,0,0)}
```
Tested on Android 8 and 9. (That's why I didn't see log statements). 
Instead, `startForegroundService` has to be used.

**Comment by deanrobertcook** [comment]
@someoneEsle I implemented the change you suggested where we first detect if the user has GPS before showing that advanced setting. Please note though, that if you set it to off on a device that actually has GPS, you now won't be able to turn it back on, so best to test on fresh installs

**Comment by someoneEsle** [comment]
- [ ] Bug 9
(phone without FCM) After a fresh install, the option to keep websocket alive was off by default.

**Comment by someoneEsle** [comment]
- [ ] Bug 10
(check on both Android 7 and 8) In settings>option there is a big space under "Vibration" (between Vibration and Sounds)

**Comment by someoneEsle** [comment]
- [ ] Bug 11
I am logged in with two accounts, A and B. A is the active account. I kill the app.
C calls A (I don't pick up). C stops calling A. I do not see a missed call notification from C.

However.
C calls B (I don't pick up). C stops calling B. I do see a missed call notification from C.

**Pull request merged**
