### PR TITLE
feat: Make sure the new system works with Federation (SQCORE-1181)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1181" title="SQCORE-1181" target="_blank">SubtaskSQCORE-1181</a>  [Android] Make sure the new system works with Federation
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/SQCORE-1181

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow
  - [x] contains a reference JIRA issue number
  - [x] answers the question: _If merged, this PR will: ..._

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The only issue connected to Federation that I found in the new notifications is about user connection events. A user connection from another federated server requires to fetch user data and for that we need to use the qualified id of the other person.

### Solutions

I update the code to use the qualified id if Federation is on.
By the way, I think right now there is a problem in general with user connections on Federation, not connected to new notifications. I will look into it in another PR.

### Testing

Manually 

#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3629/1/)

**Comment by makingthematrix** [comment]
build again

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3629/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3629/3/)

**Pull request merged**
