### PR TITLE
chore: provide a way to make previews with scoped view models

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently, previews for all composables that have some elements which use scoped view models does not work.

### Causes (Optional)

It requires to inject a view model using hilt which is not possible for previews.

### Solutions

Create annotation `@ViewModelScopedPreview` to mark all view model interfaces that should have the "preview" object. 
These interfaces need to have default implementations. 
KSP will generate a "preview" data object with these default implementations and create a list of all "preview" objects for all view model interfaces that are marked with this annotation.
`hiltViewModelScoped` checks if it's a preview, and if so then it takes a "preview" object, otherwise it injects the proper view model using hilt.

image

image

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1746](https://10.10.124.134/job/AR-build-pipeline/1746/) **failed**.

**Comment by AndroidBob** [comment]
Build [1752](https://10.10.124.134/job/AR-build-pipeline/1752/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8066188)(8066188)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8066188)(8066188)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]
Wow great automation 🥇

**Review by alexandreferris — APPROVED** [review]
👏🏻

**Pull request merged**
