### PR TITLE
feat: Add UI for typing indicator on privacy settings screen [WPB-4592]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4592" title="WPB-4592" target="_blank">StoryWPB-4592</a>  [Android] Typing indicator user settings screen
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Added stubs on Core logic module to be able to inject needed use cases for typing indicator CRUD ops

### Dependencies (Optional)
This PR needs to be merged after the one in Kalium

Needs releases with:

- [x] https://github.com/wireapp/kalium/pull/2066

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

### Attachments

https://github.com/wireapp/wire-android-reloaded/assets/2468164/b89b59f8-6cd1-4780-80af-c5f3375b5a2b

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [813](https://10.10.124.134/job/AR-build-pipeline/813/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7580670)(7580670)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7580670)(7580670)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [814](https://10.10.124.134/job/AR-build-pipeline/814/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7580991)(7580991)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7580991)(7580991)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [819](https://10.10.124.134/job/AR-build-pipeline/819/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7581388)(7581388)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7581388)(7581388)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [828](https://10.10.124.134/job/AR-build-pipeline/828/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7606454)(7606454)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7606454)(7606454)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [831](https://10.10.124.134/job/AR-build-pipeline/831/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7608979)(7608979)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7608979)(7608979)-staging-compat.apk)

**Pull request merged**
