### PR TITLE
[AN-5628] Ensure that intents without convId are handled from notifications

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### APK
[Download build #9462](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9462/artifact/build/artifact/wire-dev-PR1122-9462.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
While testing this I found out that sometime between your first PR and today something has broken notifications -- internal has quite a few issues. I'll have to retest this PR once the other issues get fixed

**Comment by deanrobertcook** [comment]
@someoneEsle internal will be fixed by https://github.com/wireapp/wire-android/pull/1124

**Comment by someoneEsle** [comment]
Looks like I forgot to post the bug I mentioned in person, sorry

When you have multiple notifications from account A and B, and app is focused on B, if you tap on the notifications from B the ones from A are cleared too.

**Comment by deanrobertcook** [comment]
Fix for switching "through" the last active account depends on https://github.com/wireapp/wire-android-sync-engine/pull/245

**Comment by someoneEsle** [comment]
(Note to self: also test 5636)

**Comment by deanrobertcook** [comment]
Closing since these fixes are also included in https://github.com/wireapp/wire-android/pull/1130

**Pull request closed without merging**
