### PR TITLE
Scala migration tests - Part 3

### PR DESCRIPTION
**Pull request by gizemb**
## What's new in this PR?

Jira issue: https://wearezeta.atlassian.net/browse/AN-6839

### Issues

See #2763

### Causes

See #2763

### Solutions

This PR applies the same solution as #2768 for GlobalDatabase (instead of UserDatabase).

1. Create the ZGlobal database as it was in 3.46 version
2. Insert a value through scala daos and data models. Use null or empty values wherever possible. Close legacy ZGlobal db.
3. Create the GlobalDatabase in the way that it's now in 3.47. This creates a RoomDaoDB, which wraps our Kotlin Room db.
When we create, the Room db executes the migration 24-25.
4. Try to read the value written by using Room database, Room daos and Kotlin data models (Entities). See if there's any crash.

**The findings and fixes:**

Checkout commit fbf0810, where there are only tests and no fixes yet.
Run ./gradlew :wire-android-sync-engine:zmessaging:testDebugUnitTest
Results & fixes:

1. ActiveAccountsMigrationTest:

> Parameter specified as non-null is null: method com.waz.zclient.storage.db.accountdata.AccessTokenConverter.fromStringToAccessToken, parameter tokenString
> java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.waz.zclient.storage.db.accountdata.AccessTokenConverter.fromStringToAccessToken, parameter tokenString
> 	at com.waz.zclient.storage.db.accountdata.AccessTokenConverter.fromStringToAccessToken(AccessTokenEntity.kt)
> 	at com.waz.zclient.storage.db.accountdata.ActiveAccountsDao_Impl$11.call(ActiveAccountsDao_Impl.java:308)
> 	at com.waz.zclient.storage.db.accountdata.ActiveAccountsDao_Impl$11.call(ActiveAccountsDao_Impl.java:285)

Meaning: In Scala-side data model `AccountData`, `accessToken` field is Optional. That means, it can be written as null to database, however, our converter expects a non-null field in `fromStringToAccessToken(String)` method.

Fix: Make converter method accept null String.

#### APK
[Download build #1889](http://10.10.124.11:8080/job/Pull%20Request%20Builder/1889/artifact/build/artifact/wire-dev-PR2770-1889.apk)

### CODE REVIEW

**Comment by gizemb** [comment]
build again

**Comment by gizemb** [comment]
build again

**Comment by makingthematrix** [comment]
build again

**Comment by gizemb** [comment]
build again

**Comment by gizemb** [comment]
build again

**Pull request merged**
