### PR TITLE
[AN-5828] Use new PermissionsService

### PR DESCRIPTION
**Pull request by deanrobertcook**
Current build:

## TODO:
 * Investigate flicking button thingy
#### APK
[Download build #10020](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10020/artifact/build/artifact/wire-dev-PR1322-10020.apk)
[Download build #10022](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10022/artifact/build/artifact/wire-dev-PR1322-10022.apk)
[Download build #10023](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10023/artifact/build/artifact/wire-dev-PR1322-10023.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Bug 1
when I receive a video call and swipe to accept, I'm asked for mic permissions but not camera

**Comment by someoneEsle** [comment]
Bug 2
This happened after sharing contacts with Wire on the moto g
`
12-11 16:45:43.280 720-1026/? E/WifiHAL: virtual int WifihalGeneric::handleResponse(WifiEvent &): QCA_WLAN_VENDOR_ATTR_FEATURE_SET not found
12-11 16:45:43.281 720-1026/? E/WifiHAL: nl80211: requestResponse->nl_recvmsgs failed: -5
12-11 16:45:43.282 720-867/? E/BatteryStatsService: no controller energy info supplied
12-11 16:45:43.282 720-867/? E/BatteryStatsService: no controller energy info supplied
12-11 16:45:43.298 720-867/? E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
                                                    
                                                    [ 12-11 16:45:43.330   198:  198 W/         ]
                                                    debuggerd: resuming target 241
                                                    
                                                    [ 12-11 16:45:43.332   198:  198 W/         ]
                                                    debuggerd: handling request: pid=242 uid=1013 gid=1031 tid=242
                                                    
                                                    
                                                    [ 12-11 16:45:43.383   198:  198 W/         ]
                                                    debuggerd: resuming target 242
                                                    
                                                    [ 12-11 16:45:43.385   198:  198 W/         ]
                                                    debuggerd: handling request: pid=245 uid=1040 gid=1026 tid=245
                                                    
                                                    
                                                    [ 12-11 16:45:43.433   198:  198 W/         ]
                                                    debuggerd: resuming target 245
                                                    
                                                    [ 12-11 16:45:43.434   198:  198 W/         ]
                                                    debuggerd: handling request: pid=246 uid=1013 gid=1005 tid=246
                                                    
                                                    
                                                    [ 12-11 16:45:43.499   198:  198 W/         ]
                                                    debuggerd: resuming target 246
12-11 16:45:43.741 720-843/? W/ProcessCpuTracker: Skipping unknown process pid 4829
12-11 16:45:43.743 720-843/? W/ProcessCpuTracker: Skipping unknown process pid 4832
12-11 16:45:44.423 720-843/? E/ActivityManager: ANR in com.waz.zclient.dev (com.waz.zclient.dev/com.waz.zclient.MainActivity)
                                                PID: 4559
                                                Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 16186.7ms.)
                                                Load: 13.25 / 13.21 / 13.08
                                                CPU usage from 79814ms to 0ms ago (2017-12-11 16:44:21.294 to 2017-12-11 16:45:41.109):
                                                  9.6% 217/surfaceflinger: 5.1% user + 4.4% kernel / faults: 1826 minor
                                                  8.8% 720/system_server: 6.6% user + 2.2% kernel / faults: 11207 minor 78 major
                                                  4.8% 1090/com.android.systemui: 3.9% user + 0.9% kernel / faults: 7113 minor 21 major
                                                  2.2% 8454/com.cyanogenmod.trebuchet: 1.9% user + 0.3% kernel / faults: 5022 minor 33 major
                                                  1.6% 31559/com.android.packageinstaller: 1.2% user + 0.3% kernel / faults: 11384 minor 49 major
                                                  1.5% 5729/com.android.settings: 1.3% user + 0.2% kernel / faults: 11199 minor 146 major
                                                  1.1% 152/ueventd: 0.6% user + 0.4% kernel / faults: 137 minor
                                                  0.8% 145/mmcqd/0: 0% user + 0.8% kernel
                                                  0.8% 1742/mpdecision: 0% user + 0.8% kernel / faults: 1 minor
                                                  0.7% 460/mdss_fb0: 0% user + 0.7% kernel
                                                  0% 239/installd: 0% user + 0% kernel / faults: 1156 minor 1 major
                                                  0.5% 30311/kworker/u:2: 0% user + 0.5% kernel
                                                  0.5% 24706/kworker/u:3: 0% user + 0.5% kernel
                                                  0.5% 3980/irq/339-synapti: 0% user + 0.5% kernel
                                                  0.5% 1254/kworker/u:5: 0% user + 0.5% kernel
                                                  0.4% 235/sensord: 0.1% user + 0.3% kernel
                                                  0% 19596/com.android.defcontainer: 0% user + 0% kernel / faults: 2777 minor 40 major
                                                  0.4% 216/servicemanager: 0.1% user + 0.2% kernel / faults: 1426 minor
                                                  0.3% 3359/com.google.android.gm: 0.2% user + 0% kernel / faults: 533 minor
                                                  0.3% 3/ksoftirqd/0: 0% user + 0.3% kernel
                                                  0.2% 40/system: 0% user + 0.2% kernel
                                                  0.2% 28598/com.google.android.gms.persistent: 0.1% user + 0% kernel / faults: 1301 minor 21 major
                                                  0.2% 28692/com.google.android.gms: 0.1% user + 0% kernel / faults: 1364 minor 8 major
                                                  0.2% 186/logd: 0.1% user + 0.1% kernel / faults: 61 minor
                                                  0.1% 30153/kworker/0:2: 0% user + 0.1% kernel
                                                  0.1% 8/migration/0: 0% user + 0.1% kernel
                                                  0% 16980/android.process.acore: 0% user + 0% kernel / faults: 2853 minor 265 major
                                                  0.1% 70/kswapd0: 0% user + 0.1% kernel
                                                  0% 28869/kworker/0:1: 0% user + 0% kernel
                                                  0.1% 30549/wpa_supplicant: 0% user + 0% kernel / faults: 244 minor
                                                  0.1% 7/kworker/u:0H: 0% user + 0.1% kernel
                                                  0% 20418/kworker/0:1H: 0% user + 0% kernel
                                                  0% 237/audioserver: 0% user + 0% kernel / faults: 66 minor
                                                  0% 247/netd: 0% user + 0% kernel / faults: 282 minor
                                                  0% 129/cfinteractive: 0% user + 0% kernel
                                                  0% 27573/com.google.process.gapps: 0% user + 0% kernel / faults: 99 minor
                                                  0% 2/kthreadd: 0% user + 0% kernel
                                                  0% 210/healthd: 0% user + 0% kernel / faults: 12 minor
                                                  0% 1253/com.android.phone: 0% user + 0% kernel / faults: 367 minor 5 major
                                                  0% 30546/RX_Thread: 0% user + 0% kernel
                                                  0% 215/lmkd: 0% user + 0% kernel
                                                  0% 236/zygote: 0% user + 0% kernel / faults: 232 minor
                                                  0% 30545/TX_Thread: 0% user + 0% kernel
                                                  0% 199/vold: 0% user + 0% kernel / faults: 182 minor
                                                  0% 228/rild: 0% user + 0% kernel / faults: 113 minor
                                                  0% 330/rild: 0% user + 0% kernel / faults: 112 minor
                                                  0% 30544/MC_Thread: 0% user + 0% kernel
                                                  0% 160/flush-179:0: 0% user + 0% kernel
                                                  0% 234/thermal-engine: 0% user + 0% kernel / faults: 13 minor
                                                  0% 1085/com.android.inputmethod.latin: 0% user + 0% kernel / faults: 494 minor
                                                  0% 15620/kworker/u:1: 0% user + 0% kernel
                                                  0% 29998/com.whatsapp: 0% user + 0% kernel / faults: 33 minor
                                                  0% 31508/kworker/0:0: 0% user + 0% kernel
                                                 +0% 4358/kworker/0:4: 0% user + 0% kernel
                                                 +0% 4538/kworker/0:0H: 0% user + 0% kernel
                                                 +0% 4543/migration/1: 0% user + 0% kernel
                                                 +0% 4544/kworker/1:0: 0% user + 0% kernel
                                                 +0% 4545/kworker/1:0H: 0% user + 0% kernel
                                                 +0% 4546/ksoftirqd/1: 0% user + 0% kernel
                                                 +0% 4548/kworker/1:1: 0% user + 0% kernel
                                                 +0% 4559/com.waz.zclient.dev: 0% user + 0% kernel
                                                 +0% 4782/kworker/1:1H: 0% user + 0% kernel
                                                9.3% TOTAL: 0.-1% user + 0% kernel + 0% irq +
12-11 16:45:44.443 720-720/? I/EntropyMixer: Writing entropy...
12-11 16:45:44.496 720-3150/? D/LBSSystemMonitorService: handleMessage what - 8
12-11 16:45:44.496 720-3150/? D/DeviceContext: handleMessage what - 1
12-11 16:45:44.521 28692-28692/? I/iu.Environment: update battery state; isPlugged? true*
12-11 16:45:44.558 28692-4848/? I/iu.FingerprintManager: Start processing all media`

**Comment by someoneEsle** [comment]
Bug 2
(this is already in public, but it's worth looking into it code-wise, at least to see what's going on/what could be affected)
Share contacts with Wire (giving it all the permissions, both the system permissions and in settings>options).
Go to Settings>Options
Now go to the android settings, find wire, remove contacts permission
Go back to Wire
Some buttons are switching themselves on and off like crazy

**Comment by someoneEsle** [comment]
Bug 3
open a conversation
long tap the mic icon
accept the permission
now you can't stop recording

Before this PR, the user had to restart recording after accepting the microphone permission

**Comment by deanrobertcook** [comment]
Bug 3 should now be fixed - I also migrated the short-cut (long-tap) audio button to scala. I've tested it pretty thoroughly myself, but could always use some more :)

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
Bug 4
send an audio message by long tap and swipe up
Now, when you long tap the mic icon again, you see a green flash as the recording starts. I can reproduce consistently

**Comment by someoneEsle** [comment]
Bug 5
Share contacts with Wire (giving it all the permissions, both the system permissions and in settings>options).
Revoke contacts permission (the android permission)
Open contacts
I do not see a popup asking me to either accept contacts permission or share contacts with Wire

**Comment by someoneEsle** [comment]
Question/bug
Launch Wire without giving it any permissions. Open a conversation. Tap video action button. At this point, Wire asks for two permissions: camera and storage. While I can understand why we're asking for the storage permission, is it necessary that we ask for the camera? I mean, since we are able to record the video without asking for the microphone permission (because we are using an external tool to record), shouldn't we be able to also avoid asking for the camera permission? My understanding is that either we need permissions for both camera and mic, or neither permission is necessary.

**Pull request merged**
