### PR TITLE
a new command in testing_gallery: enable/disable wifi

### PR DESCRIPTION
**Pull request by makingthematrix**
You can now enable/disable wifi on the device from adb shell
#### APK
[Download build #8630](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8630/artifact/build/artifact/wire-dev-PR700-8630.apk)
[Download build #8647](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8647/artifact/build/artifact/wire-dev-PR700-8647.apk)
[Download build #8656](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8656/artifact/build/artifact/wire-dev-PR700-8656.apk)

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by red-avtovo** [comment]
Can you build this PR?

**Comment by JPonte** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Comment by xuanzhaopeng** [comment]
Why we do not only use :

Enable:
adb shell svc wifi enable
Disable:
adb shell svc wifi disable

What's the reason why we need to add extra command for Testing Gallery?

**Comment by red-avtovo** [comment]
That's only because of issue, we met at Android 7.0
You cannot disable WiFi with regular settings command

**Comment by xuanzhaopeng** [comment]
What's the difference between turn off wifi  and enable Airplane mode?

To enable the Airplane mode use the following commands:

adb shell settings put global airplane_mode_on 1
adb shell am broadcast -a android.intent.action.AIRPLANE_MODE
To disable the Airplane mode, you have to chnage the setting to 0 and broadcast the intent again:

adb shell settings put global airplane_mode_on 0
adb shell am broadcast -a android.intent.action.AIRPLANE_MODE

**Comment by makingthematrix** [comment]
Build again

**Comment by red-avtovo** [comment]
No effect on Android 6.0.1

**Comment by red-avtovo** [comment]
Checked on:
Android 4.4
Android 5.0.1
Android 6.0
Android 7.0

**Pull request merged**
