### PR TITLE
feat: handle different FailedToAdd system messages types [WPB-5939]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5939" title="WPB-5939" target="_blank">StoryWPB-5939</a>  [Android] Handling groups with guests that become under LH
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The app handles "failed to add member" system message only for the errors related to federation, but now it can also happen for the " missing legal hold consent".

### Solutions

Handle different types of `FailedToAdd` system message type.
Simplify system message composable so that it's more unified and doesn't use two different solutions for "Learn more" link.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/2525

#### How to Test

Try to add a guest to the group conversation which is under legal hold.

### Attachments (Optional)

`@michaltest546`, `@michaltest546_2` and  `@michaltest546_3` are members from the same team.
`@mstest` (user name `M M`) is a guest account.
`@michaltest546_3` is under legal hold so the `mmm` group is also under legal hold.
In this case, `@mstest` cannot be added because only team members with legal hold consent can be added.

https://github.com/wireapp/wire-android/assets/30429749/15140356-f4c6-4d0e-b126-abdd10308828

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3247](https://10.10.124.134/job/AR-build-pipeline/3247/) **failed**.

**Comment by AndroidBob** [comment]
Build [3253](https://10.10.124.134/job/AR-build-pipeline/3253/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8957017)(8957017)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8957017)(8957017)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]
Great work ! The refactor end being really cool and make everything tidy 💯

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3259](https://10.10.124.134/job/AR-build-pipeline/3259/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8964046)(8964046)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8964046)(8964046)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3336](https://10.10.124.134/job/AR-build-pipeline/3336/) **failed**.

**Comment by AndroidBob** [comment]
Build [3338](https://10.10.124.134/job/AR-build-pipeline/3338/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8998802)(8998802)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8998802)(8998802)-staging-compat.apk)

**Pull request merged**
