### PR TITLE
chore(qa): Feature/default json refactoring

### PR DESCRIPTION
**Pull request by Gardosen**
This PR refactors the way we build clients based on variables coming from the default.json or custom.json.

it allows us to change any given variable over a pipe modification or custom.json on any given flavor to build.

- [ ] test all flavor variations if the references are correct
- [ ] update all custom.json files
- [ ] review the possible shrink of the flavors by removing unnecessary redundant flavors

### CODE REVIEW

**Review by makingthematrix — APPROVED** [review]
It seems like now all those fields in `app/build.gradle` are redundant but it's not a big deal. Maybe we will have time to simplify it in the future.

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/8/)

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/12/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/15/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:18
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/18/)

**Comment by AndroidBob** [comment]
Build Success
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:20
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/20/)

**Comment by AndroidBob** [comment]
Build Failure
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/21/)

**Comment by AndroidBob** [comment]
Build Failure
ID:22
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/22/)

**Comment by AndroidBob** [comment]
Build Success
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/23/)

**Comment by AndroidBob** [comment]
Build Success
ID:24
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/24/)

**Review by mythsunwind — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:27
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3578/27/)

**Pull request merged**
