### PR TITLE
fix: DEV notification duplicates

### PR DESCRIPTION
**Pull request by borichellow**
Copy of [release-PR ](https://github.com/wireapp/wire-android-reloaded/pull/1434) for `develop`

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1444/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1444/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5698237)(5698237)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5698237)(5698237)-staging-compat.apk)

**Comment by borichellow** [comment]
was included in [PR](https://github.com/wireapp/wire-android-reloaded/pull/1451)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1444/3/) **failed**.

**Pull request closed without merging**
