### PR TITLE
fix(e2ei): error handling in E2EI flow (WPB-6271)

### PR DESCRIPTION
**Pull request by AndroidBob**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6271" title="WPB-6271" target="_blank">BugWPB-6271</a>  [Android] Fix crashes during enrollment and show proper error details
  </td></table>
  <br />
 

Cherry pick from the original PR: 
- #2721

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like 
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?
Fixed and refactored the error handling for E2EI
Needs releases with:

- [ ] https://github.com/wireapp/kalium/pull/2522

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. .

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3278](https://10.10.124.134/job/AR-build-pipeline/3278/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3359](https://10.10.124.134/job/AR-build-pipeline/3359/) **failed**.

**Comment by AndroidBob** [comment]
Build [3363](https://10.10.124.134/job/AR-build-pipeline/3363/) **failed**.

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3393](https://10.10.124.134/job/AR-build-pipeline/3393/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9023995)(9023995)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9023995)(9023995)-staging-compat.apk)

**Pull request merged**
