### PR TITLE
AN-5214. SE version bump

### PR DESCRIPTION
**Pull request by makingthematrix**
The actual fix is in the SE
#### APK
[Download build #8917](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8917/artifact/build/artifact/wire-dev-PR884-8917.apk)

### CODE REVIEW

**Comment by makingthematrix** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Pull request merged**
