### PR TITLE
Scalafy ConversationListManagerFragment

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### APK
[Download build #10013](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10013/artifact/build/artifact/wire-dev-PR1347-10013.apk)
[Download build #10014](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10014/artifact/build/artifact/wire-dev-PR1347-10014.apk)
[Download build #10015](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10015/artifact/build/artifact/wire-dev-PR1347-10015.apk)
[Download build #10019](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10019/artifact/build/artifact/wire-dev-PR1347-10019.apk)
[Download build #10021](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10021/artifact/build/artifact/wire-dev-PR1347-10021.apk)
[Download build #10024](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10024/artifact/build/artifact/wire-dev-PR1347-10024.apk)
[Download build #10025](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10025/artifact/build/artifact/wire-dev-PR1347-10025.apk)
[Download build #10027](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10027/artifact/build/artifact/wire-dev-PR1347-10027.apk)
[Download build #10030](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10030/artifact/build/artifact/wire-dev-PR1347-10030.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Bug 1
I cannot swipe to go back to the conversations list when I'm in a conversation

Bug 2
I cannot open archive and contacts. (This is not consistent, and unfortunately I do not see anything in the logs)

**Comment by someoneEsle** [comment]
Bug 3 (not consistent)
When looking at the conversations list, sometimes I'm able to swipe a conversation back into view (this was disabled some time ago, and design does not want this back for now)

**Comment by someoneEsle** [comment]
Bug 4
Open a conversation
open the keyboard
swipe to close the conversation
keyboard doesn't close

This was recently "fixed" in another PR, maybe rebasing on latest master would help(?)

**Comment by someoneEsle** [comment]
Bug 5
Have an account Z that has a group conversation whose name is in the form "ParticipantA, ParticipantB, ..., ParticipantX". Log in with Z. Tap on the group conversation. Right before the conversation opens, you can see that its name changes to "ParticipantM, ParticipantN, ..." with M and N any two participants (it happens very quickly and I am not sure what the pattern is, but I can reproduce). This seems to happen only after the first time you log in, as I don't seem to be able to reproduce after killing the app.

**Comment by someoneEsle** [comment]
Bug 6
The animations when closing the archive and closing the contacts list are broken. The animation just isn't there anymore -- which explains why this morning you asked me if I thought the app was slower.

**Comment by deanrobertcook** [comment]
As discussed, bug 6 will be fixed later:
https://wearezeta.atlassian.net/browse/AN-5871

**Pull request merged**
