### PR TITLE
Fix/delete session keys on wipe

### PR DESCRIPTION
**Pull request by CalumMcCall**
### Issues

Session files, prekeys and the global DB were not being deleted when the account info was wiped. [More info here](https://wearezeta.atlassian.net/browse/AN-6459)

### Causes

These files were overlooked as they need to be inspected manually to ensure they are gone.

### Testing

Manual testing was done to verify the session files folder is deleted. Testing was also done to ensure that logging in was possible again even after wiping all the databases.
#### APK
[Download build #583](http://10.10.124.11:8080/job/Pull%20Request%20Builder/583/artifact/build/artifact/wire-dev-PR2472-583.apk)

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by marcoconti83** [comment]
ok to test

**Comment by marcoconti83** [comment]
build again

**Comment by CalumMcCall** [comment]
build again

**Comment by marcoconti83** [comment]
build again

**Pull request merged**
