### PR TITLE
Handle starting the camera in landscape on tablets

### PR DESCRIPTION
**Pull request by deanrobertcook**
This commit also ensures that the CameraPreviewController does not return the Camera to the CameraPreviewTextureView. Instead only a future of a PreviewSize is returned, and this allows the TextureView to resize itself properly whenever a new camera is opened with a potentially different PreviewSize.

All rotation of the CameraFragment is now handled inside of the Fragment itself. If the Camera feed is showing, the orientation is locked into portrait, else it is freed up again to let the device decide.

#### Ticket:
https://wearezeta.atlassian.net/browse/AN-4380

#### Test Description:
* On tablets, start the camera both in Landscape and Portrait orientations, rotate the camera, and leave the camera in a different orientation.
* Ensure that the photo preview is free to rotate
* Ensure that rotation is unlocked again for the rest of the app

#### Known Issues:
* When opening the camera in landscape, for a brief moment it may appear distorted before the view rotates again. In a separate PR I will attempt to fix this ugly locking of the screen rotation

#### APK

[Download build #7278](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7278/artifact/build/artifact/wire-dev-PR28-7278.apk)
[Download build #7291](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7291/artifact/build/artifact/wire-dev-PR28-7291.apk)
[Download build #7292](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7292/artifact/build/artifact/wire-dev-PR28-7292.apk)
[Download build #7293](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7293/artifact/build/artifact/wire-dev-PR28-7293.apk)
[Download build #7294](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7294/artifact/build/artifact/wire-dev-PR28-7294.apk)
[Download build #7295](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7295/artifact/build/artifact/wire-dev-PR28-7295.apk)
[Download build #7296](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7296/artifact/build/artifact/wire-dev-PR28-7296.apk)
[Download build #7298](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7298/artifact/build/artifact/wire-dev-PR28-7298.apk)
[Download build #7305](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7305/artifact/build/artifact/wire-dev-PR28-7305.apk)
[Download build #7306](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7306/artifact/build/artifact/wire-dev-PR28-7306.apk)
[Download build #7309](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7309/artifact/build/artifact/wire-dev-PR28-7309.apk)
[Download build #7313](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7313/artifact/build/artifact/wire-dev-PR28-7313.apk)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Camera Preview on Samsung Galaxy Tab 4 has wrong orientation:
screen

**Comment by mykola-mokhnach** [comment]
Camera preview reload continuously if I try to change my self profile picture from Settings in Landscape

**Comment by mykola-mokhnach** [comment]
1. Tap Picture item inside Setting->Account to see camera view.
2. Tap hardware Back button multiple times to return to conversations list

AR:
Camera view is opened instead of conversation list/view

ER:
Camera view should not be visible after STR

**Comment by deanrobertcook** [comment]
@mykola-mokhnach please file last two issues as separate ticket

**Comment by mykola-mokhnach** [comment]
@deanrobertcook done:
https://wearezeta.atlassian.net/browse/AN-4382
https://wearezeta.atlassian.net/browse/AN-4381

**Comment by deanrobertcook** [comment]
@mykola-mokhnach thank you, all fixed now

**Comment by mykola-mokhnach** [comment]
Nexus 5:
Making landscape picture with keyboard gallery makes the resulting picture to be flipped:
screen

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
@mykola-mokhnach oopsies, good catch. Fixed

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by mykola-mokhnach** [comment]
Much better now

**Pull request merged**
