### PR TITLE
fix: make login and sync loading smoother [AR-3001]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3001" title="AR-3001" target="_blank">BugAR-3001</a>  Loading spinner on setting up Wire Screen is not visible on android 9
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Loading state UI is frozen during initial sync on Android 9. 
Loading state when logging in is wrong and progress disappears after a split second. 

### Solutions

Login:
Remove turning off the loading flag on login screen right after the first call and let it be visible throughout the whole login flow. 
Execute all important actions on IO to not block the main thread and let the loading be as smooth as possible.

Initial sync:
Call `waitUntilSyncIsCompleted` in `LaunchedEffect` with `Unit` key to make sure it's executed only once.
Change `collect` to `firstOrNull` to not collect items when it's not needed anymore.

Register device:
Open "initial sync" screen also after registering a device if the sync hasn't been done yet.

#### How to Test

Login and sync to see the difference.

### Attachments (Optional)

Before:

https://user-images.githubusercontent.com/30429749/226672004-8a9bc044-ed0d-4469-848e-8d92229a41f8.mp4

<br />
<br />

After:

https://user-images.githubusercontent.com/30429749/226672139-fc92e0b5-e631-48b9-8ee8-71bdff36ed30.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1567/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1567/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(6044991)(6044991)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(6044991)(6044991)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
🪄✨

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Pull request merged**
