### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6414670)(6414670)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6414670)(6414670)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6467303)(6467303)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6467303)(6467303)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6467680)(6467680)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6467680)(6467680)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6483852)(6483852)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6483852)(6483852)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6484672)(6484672)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6484672)(6484672)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6485605)(6485605)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6485605)(6485605)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6490721)(6490721)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6490721)(6490721)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6491569)(6491569)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6491569)(6491569)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6492101)(6492101)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6492101)(6492101)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/11/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6492456)(6492456)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6492456)(6492456)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/12/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6517334)(6517334)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6517334)(6517334)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/13/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6517768)(6517768)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6517768)(6517768)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [14](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/14/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6518181)(6518181)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6518181)(6518181)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/16/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6526165)(6526165)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6526165)(6526165)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [17](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/17/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6527449)(6527449)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6527449)(6527449)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [18](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/18/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6534204)(6534204)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6534204)(6534204)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [19](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/19/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6534631)(6534631)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6534631)(6534631)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [20](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/20/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6535003)(6535003)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6535003)(6535003)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [22](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/22/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6536454)(6536454)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6536454)(6536454)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [24](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/24/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6536862)(6536862)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6536862)(6536862)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [25](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/25/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6551587)(6551587)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6551587)(6551587)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [26](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/26/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6579013)(6579013)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6579013)(6579013)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [27](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/27/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6579389)(6579389)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6579389)(6579389)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [28](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/28/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6581019)(6581019)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6581019)(6581019)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [31](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/31/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6588195)(6588195)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6588195)(6588195)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [32](https://10.10.124.134/job/wire-android-reloaded/job/PR-1751/32/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6588785)(6588785)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6588785)(6588785)-staging-compat.apk)

**Pull request merged**
