### PR TITLE
feat: Show e2ei certificate in device details screen - PART 1  (WPB-3214) 

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-3214" title="WPB-3214" target="_blank">StoryWPB-3214</a>  [Android] 5.3.24 Show E2EI certificate info
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description

In this PR, I am creating the required UI for displaying E2EI certificate with it's different states.
 
Next PR will be for calling correspondent use cases.

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Go device details

### Attachments (Optional)

Wire 2023-10-11 at 4_03 PM

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1243](https://10.10.124.134/job/AR-build-pipeline/1243/) **failed**.

**Comment by AndroidBob** [comment]
Build [1244](https://10.10.124.134/job/AR-build-pipeline/1244/) **failed**.

**Comment by AndroidBob** [comment]
Build [1247](https://10.10.124.134/job/AR-build-pipeline/1247/) **failed**.

**Comment by AndroidBob** [comment]
Build [1291](https://10.10.124.134/job/AR-build-pipeline/1291/) **failed**.

**Comment by AndroidBob** [comment]
Build [1294](https://10.10.124.134/job/AR-build-pipeline/1294/) **failed**.

**Comment by AndroidBob** [comment]
Build [1295](https://10.10.124.134/job/AR-build-pipeline/1295/) **failed**.

**Comment by AndroidBob** [comment]
Build [1298](https://10.10.124.134/job/AR-build-pipeline/1298/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7824331)(7824331)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7824331)(7824331)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1324](https://10.10.124.134/job/AR-build-pipeline/1324/) **failed**.

**Comment by AndroidBob** [comment]
Build [1343](https://10.10.124.134/job/AR-build-pipeline/1343/) **failed**.

**Comment by AndroidBob** [comment]
Build [1348](https://10.10.124.134/job/AR-build-pipeline/1348/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7850578)(7850578)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7850578)(7850578)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by mchenani — APPROVED** [review]
🤘

**Comment by AndroidBob** [comment]
Build [1508](https://10.10.124.134/job/AR-build-pipeline/1508/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7925364)(7925364)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7925364)(7925364)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1519](https://10.10.124.134/job/AR-build-pipeline/1519/) **failed**.

**Comment by AndroidBob** [comment]
Build [1530](https://10.10.124.134/job/AR-build-pipeline/1530/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7927405)(7927405)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7927405)(7927405)-staging-compat.apk)

**Pull request merged**
