### PR TITLE
chore: Enable strict mode (ACOL-72)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACOL-72" title="ACOL-72" target="_blank">TopicACOL-72</a>  Detect performance issues and ANRs
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Description 

This PR aims to enable [Strict Mode](https://developer.android.com/reference/android/os/StrictMode) in Android Reloaded which will help us to improve app performance and prevent possible ANRs.

> StrictMode is a developer tool which detects things you might be doing by accident and brings them to your attention so you can fix them.

`penaltyDeath()`, which will crash the app in case of any detected violation, is commented for now until we fix current issues.

For now we will just log these violations, when we fix them we will make the app crashes when  

#### How to Test

In the log you can see all violations reported by StrictMode  using the tag `StrictMode`

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1286/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1286/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5397079)(5397079)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5397079)(5397079)-dev-compat.apk)

**Review by alexandreferris — APPROVED** [review]
🔥

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1286/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5405629)(5405629)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5405629)(5405629)-dev-compat.apk)

**Review by yamilmedina — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1286/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5430433)(5430433)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5430433)(5430433)-dev-compat.apk)

**Pull request merged**
