### PR TITLE
fix: do not show confirmation dialogs when unarchiving conversations [WPB-4435]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4435" title="WPB-4435" target="_blank">StoryWPB-4435</a>  add un-archive option in the context menu of the archived list
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
When trying to unarchive a conversation item from the Archive screen, app was displaying the archiving confirmation dialog which is wrong. Also, when the Archive screen was empty, we were showing the wrong message. This PR fixes both issues.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1168](https://10.10.124.134/job/AR-build-pipeline/1168/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1169](https://10.10.124.134/job/AR-build-pipeline/1169/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7755780)(7755780)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7755780)(7755780)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1170](https://10.10.124.134/job/AR-build-pipeline/1170/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7761403)(7761403)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7761403)(7761403)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1174](https://10.10.124.134/job/AR-build-pipeline/1174/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7761854)(7761854)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7761854)(7761854)-staging-compat.apk)

**Pull request merged**
