### PR TITLE
fix: show deleted regular message [AR-3278]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3278" title="AR-3278" target="_blank">BugAR-3278</a>  Deleted label not visible anymore, instead message is gone
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Regular messages with null content and delete visibility was ignored to show on messages list

### Causes (Optional)

Deleted messages was not showing on conversation screen

### Solutions

We were checking twice message visibility in mappers so I changed it to have it in one place and added new content type for regular message to make it more readable

### CODE REVIEW

**Review by tmspzz — APPROVED** [review]

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1627/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1627/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1627/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6165803)(6165803)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6165803)(6165803)-staging-compat.apk)

**Pull request merged**
