### PR TITLE
feat: hide group creation and edit options for external user [WPB-5749]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5749" title="WPB-5749" target="_blank">TaskWPB-5749</a>  [Android] Hide group creation buttons for external users
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

External users have the possibility to create groups, add participants to existing groups and edit group name resulting in errors because they shouldn't be allowed to. 

### Solutions

Check if the user is external and if so then hide option to create group, add participants to the existing group and edit name of the group. 
Created dedicated class `ItemActionType` to choose if the items can be clicked or/and checked.
Cleaned up and unified the state defining the possibilities to edit particular group options according to this table:
 | for given option to be allowed...          | ...user needs to be                                |
 |--------------------------------------------|----------------------------------------------------|
 | add participants to group allowed          | group admin & not external team member             |
 | group name change allowed                  | group admin & not external team member             |
 | group guests option change allowed         | group admin & team member of the group owner team  |
 | group services option change allowed       | group admin                                        |
 | self deleting option change allowed        | group admin                                        |
 | group read receipts option change allowed  | group admin & group created by a team member       |

Let me know if any of these conditions is incorrect.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/2653

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Log in as external user and try to create group, add participants to existing group or change the name of the group.

### Attachments (Optional)

https://github.com/wireapp/wire-android/assets/30429749/cbd57d04-5332-4880-b970-d97280cc7930

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3623](https://10.10.124.134/job/AR-build-pipeline/3623/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9154006)(9154006)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9154006)(9154006)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3628](https://10.10.124.134/job/AR-build-pipeline/3628/) **failed**.

**Comment by AndroidBob** [comment]
Build [3633](https://10.10.124.134/job/AR-build-pipeline/3633/) **failed**.

**Comment by AndroidBob** [comment]
Build [3636](https://10.10.124.134/job/AR-build-pipeline/3636/) **failed**.

**Comment by AndroidBob** [comment]
Build [3637](https://10.10.124.134/job/AR-build-pipeline/3637/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9156977)(9156977)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9156977)(9156977)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Review by mchenani — APPROVED** [review]

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3642](https://10.10.124.134/job/AR-build-pipeline/3642/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9181277)(9181277)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9181277)(9181277)-staging-compat.apk)

**Pull request merged**
