### PR TITLE
 Notifications: Process the new messages when the app comes to the front + refactoring (SQCORE-1142)

### PR DESCRIPTION
**Pull request by makingthematrix**
https://wearezeta.atlassian.net/browse/SQCORE-1142

Currently each new notification is processed at once for all the app’s functionalities - this is exactly what makes the notification processing so heavy but it also means that when the app comes to the front, all messages are already processed. In the new implementation we will need to be aware that while the app was in the background or off, a new message might have been processed by Work Manager but only to the point where the decrypted message is stored in the database. We need to test if, when the app comes to the front, the app gets updated properly.

One special case is when the app is getting opened by the user tapping on a displayed notification or reply to a message in a notification. These actions should be handled as they are handled now.

This PR also contains fixes to cancelling notifications when the app is opened.
And I removed `NotificationService` and its unit tests - this contributes to the big part of deleted lines of code. I planned to do it only in [SQCORE-1143](https://wearezeta.atlassian.net/browse/SQCORE-1143) but `NotificationSerivce` was connected to various parts of the app and was always getting in the way of the new system.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/2/)

**Comment by AndroidBob** [comment]
Build Success
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/3/)

**Review by mdimjasevic — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3609/2/)

**Pull request merged**
