### PR TITLE
feat: search message highlight [WPB-5163]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5163" title="WPB-5163" target="_blank">StoryWPB-5163</a>  Highlight search result that matches the input text
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- highlight searched messages by query text 
- trim search query and disable search for empty spaces

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/13151239/16e298fd-0ffd-48f7-ad5e-9283076fe750

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1832](https://10.10.124.134/job/AR-build-pipeline/1832/) **failed**.

**Comment by AndroidBob** [comment]
Build [1833](https://10.10.124.134/job/AR-build-pipeline/1833/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8106373)(8106373)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8106373)(8106373)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]
Amazing work 👏🏻

**Review by yamilmedina — APPROVED** [review]

**Review by mchenani — APPROVED** [review]
🍳

**Comment by AndroidBob** [comment]
Build [1843](https://10.10.124.134/job/AR-build-pipeline/1843/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8108324)(8108324)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8108324)(8108324)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1849](https://10.10.124.134/job/AR-build-pipeline/1849/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8108860)(8108860)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8108860)(8108860)-staging-compat.apk)

**Pull request merged**
