### PR TITLE
chore: Crowdin updates

### PR DESCRIPTION
**Pull request by AndroidBob**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/6/)

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/7/)

**Comment by AndroidBob** [comment]
Build Success
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/8/)

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/11/)

**Comment by AndroidBob** [comment]
Build Success
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/12/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/13/)

**Comment by AndroidBob** [comment]
Build Success
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/14/)

**Comment by AndroidBob** [comment]
Build Success
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/15/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:18
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/18/)

**Comment by AndroidBob** [comment]
Build Success
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/19/)

**Comment by AndroidBob** [comment]
Build Success
ID:20
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/20/)

**Comment by AndroidBob** [comment]
Build Success
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/21/)

**Comment by AndroidBob** [comment]
Build Success
ID:22
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/22/)

**Comment by AndroidBob** [comment]
Build Failure
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/23/)

**Comment by AndroidBob** [comment]
Build Success
ID:24
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/24/)

**Comment by AndroidBob** [comment]
Build Failure
ID:25
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/25/)

**Comment by AndroidBob** [comment]
Build Failure
ID:26
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/26/)

**Comment by AndroidBob** [comment]
Build Success
ID:27
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/27/)

**Comment by AndroidBob** [comment]
Build Failure
ID:29
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/29/)

**Comment by AndroidBob** [comment]
Build Success
ID:31
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/31/)

**Comment by AndroidBob** [comment]
Build Success
ID:32
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/32/)

**Comment by AndroidBob** [comment]
Build Success
ID:33
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/33/)

**Comment by AndroidBob** [comment]
Build Success
ID:34
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/34/)

**Comment by AndroidBob** [comment]
Build Success
ID:35
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/35/)

**Comment by AndroidBob** [comment]
Build Failure
ID:36
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/36/)

**Comment by AndroidBob** [comment]
Build Success
ID:37
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/37/)

**Comment by AndroidBob** [comment]
Build Success
ID:38
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/38/)

**Comment by AndroidBob** [comment]
Build Success
ID:40
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/40/)

**Comment by AndroidBob** [comment]
Build Success
ID:41
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/41/)

**Comment by AndroidBob** [comment]
Build Success
ID:42
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/42/)

**Comment by AndroidBob** [comment]
Build Failure
ID:43
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/43/)

**Comment by AndroidBob** [comment]
Build Success
ID:44
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3663/44/)

**Review by marcoconti83 — APPROVED** [review]

**Pull request merged**
