### PR TITLE
fix: Update Firebase tocken when new comes (AR-2489)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2489" title="AR-2489" target="_blank">BugAR-2489</a>  New Firebase token is not updated in BackEnd side
  </td></table>
  <br />
 

# What's new in this PR?

new flow for registering Firebase token 

### Issues

Firebase token is not updated on our BE side if Firebase decides to create a new one (it's rare but possible case).

### Causes (Optional)

FB token when it comes was just saving into local DB and when user login we register that token for the user.

### Solutions

Add some flag into UserScope "shouldUpdateFirebaseToken"
On every `init` in `UserScope` check this `shouldUpdateFirebaseToken` flag if it's true - update the token for BE.
And everytime Firebase generate a new token we save it into local DB **and** set `shouldUpdateFirebaseToken` for all users to `true`.
 
All of it was implemented on `kalium` side, on android side we just new to remove registration calling, it will be done without any interactions from android side.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4489187)(4489187)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4489187)(4489187)-dev-release.apk)

**Review by MohammedMokresh — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1016/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4504448)(4504448)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4504448)(4504448)-dev-release.apk)

**Pull request merged**
