### PR TITLE
[AN-4399] Various LTR issues fixed

### PR DESCRIPTION
**Pull request by hakonbo**
* User names are left aligned and avatars are right aligned
* Single line messages don’t have any right margin
* Ping message alignment
* Add/remove message alignment
* File message alignment
* Audio message alignment
* Error message alignment
* Missed call message alignment
* Group participant details margins
* Single participant details margins
* Button alignment in cursor camera
* Adjusted giphy/avatar in cursor

http://192.168.10.18:8080/job/Pull%20Request%20Builder/7378/artifact/build/artifact/wire-dev-PR52-7378.apk

### CODE REVIEW

**Comment by shumengye** [comment]
nice!

**Comment by mykola-mokhnach** [comment]
This all looks perfect for me. Only one control is left where it would be nice to fix typing direction - this is Start UI/Add to Group input field:
screen
screen2

**Comment by hakonbo** [comment]
I'll have a look at the start UI in a separate PR.

**Comment by mykola-mokhnach** [comment]
Then it's done

**Pull request merged**
