### PR TITLE
feat: GitHub actions upload to s3 testing the theory

### PR DESCRIPTION
**Pull request by borichellow**
testing

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4883](https://10.10.124.134/job/AR-build-pipeline/4883/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9740713)(9740713)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9740713)(9740713)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4923](https://10.10.124.134/job/AR-build-pipeline/4923/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9742951)(9742951)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9742951)(9742951)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4936](https://10.10.124.134/job/AR-build-pipeline/4936/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9748954)(9748954)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9748954)(9748954)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4940](https://10.10.124.134/job/AR-build-pipeline/4940/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9749594)(9749594)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9749594)(9749594)-staging-compat.apk)

**Comment by yamilmedina** [comment]
Goo job, I left a comment in the ticket https://wearezeta.atlassian.net/browse/WPB-8730?focusedCommentId=125018

**Review by yamilmedina — CHANGES_REQUESTED** [review]
In a good direction, just left a comment in the ticket with some details we need to address
https://wearezeta.atlassian.net/browse/WPB-8730?focusedCommentId=125018

**Pull request closed without merging**
