### PR TITLE
fix: Notification issues (AR-2373, AR-2370)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2373" title="AR-2373" target="_blank">BugAR-2373</a>  Quick Reply button seems to not working properly (but does)
  </td></table>
  <br />
 

### Issues

fixed issues: 
1. Quick Reply button seems to not working properly (but does)
2. UserName is not displayed in connectionRequest notification

Also did some small refactoring, to organize the notifications structure better

### Causes (Optional)

1. about "reply": sometimes Android updates notification on which user replied, sometimes it doesn't
2. about userName: notification title was working like this: if it's group conversation - then title is a group name, otherwise - no title. So when ConnectionRequest comes -> no title was added.

about refactoring: MessageNotificationManager becomes too big.

### Solutions

1. update notification on which was the reply everytime after reply was sent (succeed, or not)
2. add check if the notification is about ConnectionRequest, then add title.

refactoring: extract all the NotificationActions into a separate file, also moved `WireFirebaseMessagingService` into `services` packager, I believe it's better place for it.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4420787)(4420787)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4420787)(4420787)-dev-release.apk)

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4444542)(4444542)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4444542)(4444542)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4444688)(4444688)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4444688)(4444688)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-984/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4463754)(4463754)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4463754)(4463754)-dev-release.apk)

**Pull request merged**
