### PR TITLE
Contribution to issue #233

### PR DESCRIPTION
**Pull request by bgermann**
This pull request together with https://github.com/wireapp/wire-android-sync-engine/pull/101 replaces the spotifyAuth dependency from Wire's 3rd party repo with a stock version.

Also proprietary dependencies are removed from the opensource.txt file.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
@bgermann thanks for the contribution, but I'll close this one as we decided to take out the Spotify player code from the UI for now, see #805. Spotify and Soundcloud links will be displayed in the conversation stream with Artist/title and album art, clicking links will open browser/spotify app/soundcloud app.

**Pull request closed without merging**
