### PR TITLE
feat: End call on conversation degraded (WPB-4487)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4487" title="WPB-4487" target="_blank">StoryWPB-4487</a>  [proteus] Show a dialog to explain why a call was ended (conversation degraded status)
  </td></table>
  <br />
 

# What's new in this PR?

When the conversations verification status (MLS or Proteus) degrades from the "Verified" during the call, call should be ended and user should see the dialog informing him why the call was ended

**PS** a lot of changes are just imports updates which caused by changes in kalium, donnow why corresponding PR is absent in AR.

#### How to Test

For now kalium part works only for the Proteus.

- verify all your devices
- verify all the devices of some user
- open the conversation with that user and start a call
-  (without ending a call) un-verify some device of that user

**expected result:** call is ended and you see the dialog informing that call was ended because of verification changes

- verify all your devices
- verify all the devices of some user
- open the conversation with that user and start a call
-  (without ending a call) un-verify some of your devices

**expected result:** call is ended and you see the dialog informing that call was ended because of verification changes

### Attachments (Optional)

Screenshot 2023-11-08 at 11 05 17

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1684](https://10.10.124.134/job/AR-build-pipeline/1684/) **failed**.

**Comment by AndroidBob** [comment]
Build [1685](https://10.10.124.134/job/AR-build-pipeline/1685/) **failed**.

**Comment by AndroidBob** [comment]
Build [1698](https://10.10.124.134/job/AR-build-pipeline/1698/) **failed**.

**Comment by AndroidBob** [comment]
Build [1700](https://10.10.124.134/job/AR-build-pipeline/1700/) **failed**.

**Comment by AndroidBob** [comment]
Build [1708](https://10.10.124.134/job/AR-build-pipeline/1708/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(8049103)(8049103)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(8049103)(8049103)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
🛡️

**Review by yamilmedina — APPROVED** [review]

**Pull request merged**
