### PR TITLE
[AN-5030][AN-REVEAL] Issues with reveal

### PR DESCRIPTION
**Pull request by JPonte**
This is to avoid long scrolling when pressing "reveal message" and scrolling to random positions.
The smooth scrolling was deactivated for now since it seems to be a bit more temperamental.

Ticket: https://wearezeta.atlassian.net/browse/AN-5030

#### APK

[Download build #8565](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8565/artifact/build/artifact/wire-dev-PR675-8565.apk)
[Download build #8572](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8572/artifact/build/artifact/wire-dev-PR675-8572.apk)
[Download build #8578](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8578/artifact/build/artifact/wire-dev-PR675-8578.apk)
[Download build #8586](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8586/artifact/build/artifact/wire-dev-PR675-8586.apk)
[Download build #8590](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8590/artifact/build/artifact/wire-dev-PR675-8590.apk)
[Download build #8601](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8601/artifact/build/artifact/wire-dev-PR675-8601.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Comment by red-avtovo** [comment]
Scrolling is not working properly, when user is getting more messages
STR:
C1 opens local search and taps on picture he wants to reveal
C2 sends several messages
C1 (while C2 is sending) taps button "reveal in conversation"

AR:
C1 sees beginning of the conversation after scroll
ER:
C1 sees the image he tried to reveal

**Comment by red-avtovo** [comment]
Scrolling is not working properly, when user is getting more messages
STR:
C1 opens local search inputs text to search
C1 reveals the message
C2 sends several messages

AR:
C1 is scrolled down to the last message
ER:
C1 sees the revealed message

**Comment by JPonte** [comment]
build again

**Comment by red-avtovo** [comment]
👍

**Comment by JPonte** [comment]
build again

**Pull request merged**
