### PR TITLE
feat: my account password recovery (AR-1944)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-1944" title="AR-1944" target="_blank">StoryAR-1944</a>  Reset password
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Creates a new flow in the settings screen to allow users to change their password.
This applies only for users that doesn't have an SSO id.

Also, as part of this scope, we are displaying some basic information in the new section: "My Account" without the possibility of edit, since this is scope of another ticket.

#### Test Coverage (Optional) 

**WIP**

- [ ] I have added automated test to this contribution

### Attachments (Optional)

https://user-images.githubusercontent.com/5806454/194336998-e911a210-309f-4411-a7fd-fdd730801fdf.mov

#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1079/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4609523)(4609523)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4609523)(4609523)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1079/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4609913)(4609913)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4609913)(4609913)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1079/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4610280)(4610280)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4610280)(4610280)-dev-release.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM 🚀

**Pull request merged**
