### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6183266)(6183266)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6183266)(6183266)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6233025)(6233025)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6233025)(6233025)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6242129)(6242129)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6242129)(6242129)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6243486)(6243486)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6243486)(6243486)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/6/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6286974)(6286974)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6286974)(6286974)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [10](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/10/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6311968)(6311968)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6311968)(6311968)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [12](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/12/) **failed**.

**Comment by AndroidBob** [comment]
Build [13](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/13/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6337395)(6337395)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6337395)(6337395)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [14](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/14/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6337743)(6337743)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6337743)(6337743)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [15](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/15/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6361796)(6361796)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6361796)(6361796)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [18](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/18/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6362245)(6362245)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6362245)(6362245)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [19](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/19/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6362436)(6362436)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6362436)(6362436)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [20](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/20/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6362655)(6362655)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6362655)(6362655)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [21](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/21/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6363530)(6363530)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6363530)(6363530)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [22](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/22/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6370247)(6370247)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6370247)(6370247)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [23](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/23/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6370585)(6370585)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6370585)(6370585)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [26](https://10.10.124.134/job/wire-android-reloaded/job/PR-1647/26/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6372708)(6372708)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6372708)(6372708)-staging-compat.apk)

**Pull request merged**
