### PR TITLE
refactor: introduce convention plugins

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We're currently relying on logic written in `buildSrc` to configure our project.
As mentioned in #1898, using `buildSrc` [impacts performance](https://proandroiddev.com/stop-using-gradle-buildsrc-use-composite-builds-instead-3c38ac7a2ab3) as it invalidates lots of caches even on small changes, causing the whole project to be rebuilt.

### Solutions

In order to rely less on `buildSrc`, and prepare the ground for the project to become multi-module, this PR migrates some of the `buildSrc` configuration to use an convention plugins via an included build.
> **Note**: More info about this solution can be seen on [this blog post](https://developer.squareup.com/blog/herding-elephants/).

To start, this PR provides the backbones to build more plugins, and only addresses "compilation logic" in a way that it can be easily shared between Android Applications and Libraries.

Other `buildSrc` logic, like `infrastructure`, `testing`, `variants`, etc. will be tackled in future PRs.

----
#### PR Post Merge Checklist for internal contributors

- [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [163](https://10.10.124.134/job/AR-build-pipeline/163/) **failed**.

**Comment by AndroidBob** [comment]
Build [165](https://10.10.124.134/job/AR-build-pipeline/165/) **failed**.

**Comment by AndroidBob** [comment]
Build [166](https://10.10.124.134/job/AR-build-pipeline/166/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(6942240)(6942240)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(6942240)(6942240)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]
🔥

**Pull request merged**
