### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [402](https://10.10.124.134/job/AR-build-pipeline/402/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7435601)(7435601)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7435601)(7435601)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [420](https://10.10.124.134/job/AR-build-pipeline/420/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7442337)(7442337)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7442337)(7442337)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [434](https://10.10.124.134/job/AR-build-pipeline/434/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7444555)(7444555)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7444555)(7444555)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [438](https://10.10.124.134/job/AR-build-pipeline/438/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7450308)(7450308)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7450308)(7450308)-staging-compat.apk)

**Pull request merged**
