### PR TITLE
fix: ignore mention with negative index [WPB-4854]

### PR DESCRIPTION
**Pull request by Garzas**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some mention data contained negative index which caused ` java.lang.StringIndexOutOfBoundsException`

### Solutions

Ignore broken mentions with negative indexes

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [956](https://10.10.124.134/job/AR-build-pipeline/956/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7668131)(7668131)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7668131)(7668131)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [960](https://10.10.124.134/job/AR-build-pipeline/960/) **failed**.

**Review by gongracr — APPROVED** [review]
Looking good! 🍪 But maybe we can also test the empty mention "@" ?

**Comment by AndroidBob** [comment]
Build [964](https://10.10.124.134/job/AR-build-pipeline/964/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7668874)(7668874)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7668874)(7668874)-staging-compat.apk)

**Pull request merged**
