### PR TITLE
fix: Create Group protocol not editable anymore [WPB-7109]

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-7109" title="WPB-7109" target="_blank">BugWPB-7109</a>  Different behaviour to identify a MLS conversation on Android and Web
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

User should not be able to change a protocol during the creating a group. 
Group protocol is the default one!

### Causes (Optional)

Requirements changed

### Solutions

Change it.

### Attachments (Optional)

Screenshot 2024-03-14 at 12 21 04

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]
So now we will always show the protocol instead of only showing when MLS was enabled 👌🏻

**Comment by borichellow** [comment]
> So now we will always show the protocol instead of only showing when MLS was enabled 👌🏻

yes, just to inform users. And there is no chance to change the protocol :)

**Review by yamilmedina — APPROVED** [review]
👏

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3596](https://10.10.124.134/job/AR-build-pipeline/3596/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.2(9144615)(9144615)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.2(9144615)(9144615)-staging-compat.apk)

**Pull request merged**
