### PR TITLE
feat: [DEV] crash app on migration erorrs (#1658)

### PR DESCRIPTION
**Pull request by MohamadJaara**
* chore: crash the migration worker if there is an error (#1579)

* chore: crash the migration worker if there is an error

* styling

* trigger CI

* address PR comments

(cherry picked from commit f66e02fdfd9ebe1f1756146afc43aa0b4a0c3f68)

* feat: redo migration on app update when failure (#1584)

* chore: crash the migration worker if there is an error

* feat: redo migration when completed with errors on a previous version

* styling

* trigger CI

* address PR comments

* styling

* unit tests

(cherry picked from commit 172b2bf84ee82b23f9fd5b07bb169f83adcd7404)

* fix: check if user is logged in after migraion error (#1607)

* fix: check if user is logged in after migraion error

* clear backstack when navigating to login

(cherry picked from commit 825f5b086888f9a72e5ad3d660f169675af7ae2c)

* fix: try catch migration errors and include the report when failing (#1616)

Co-authored-by: Tommaso Piazza <196761+tmspzz@users.noreply.github.com>

(cherry picked from commit ed2827f7a2a91f390f764b77fa51e459a97ea815)

* fix: propagate migration errors to the UI and crash in the view model (#1628)

* fix: propagate migration errors to the UI and crash in the view model

* revert disabling strict mode

* remove unnecessary logs

(cherry picked from commit fff30dab75bf0fd4f8bca5e1bb29054583daca58)

* fix: merge issues

* styling

---------

Co-authored-by: Vitor Hugo Schwaab <vitor@schwaab.xyz>
(cherry picked from commit 038bb7c8b81a80172f26c8b4da29c8f561a95b58)

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1662/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6234294)(6234294)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6234294)(6234294)-staging-compat.apk)

**Review by saleniuk — COMMENTED** [review]
Should this be merged to `develop` or `release/candidate`? 🤔

**Comment by vitorhugods** [comment]
> Should this be merged to `develop` or `release/candidate`? 🤔

- https://github.com/wireapp/wire-android-reloaded/pull/1658

Was merged to RC already. I guess it doesn't hurt to have the same code in `develop` to make it easier to maintain.

Drawback is that we need to disable this later eventually.

But... To be fair. We'll need to disable the whole migration at some point in time :)

**Comment by MohamadJaara** [comment]
> Should this be merged to `develop` or `release/candidate`? 🤔

As vitor already mentioned, we do need it to unify the migration logic and until we deprecate migration we need this logic in ever release

**Review by tmspzz — APPROVED** [review]

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1662/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6301326)(6301326)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6301326)(6301326)-staging-compat.apk)

**Pull request merged**
