### PR TITLE
[WIP] Sbt build integration

### PR DESCRIPTION
**Pull request by charafau**
This is work in progress PR for sbt integration. I decided to create it because of this issue:

https://github.com/wireapp/wire-android/issues/151

and because of problems which I would like to discuss with developers. 

What I've done so far:
- upgraded sbt plugins
- upgraded sbt version
- fixed proguard settings

sbt integration was done pretty well, one option is not available so I commented it out.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by charafau** [comment]
Now there are available projects: 

[info] Adding android subproject dependency rules for: zclient-app, flavor-experimental, flavor-internal, flavor-qaavs, flavor-prod, wireUi, flavor-custom, flavor-avs, flavor-candidate

I choose `flavor-prod` 

> sbt
> project flavor-prod
> android:package

but unfortunately sbt cannot find those dependencies:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.wire#zmessaging-android;78-SNAPSHOT: not found
[warn] 	:: com.wearezeta.avs#avs;2.7.19: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.wire:zmessaging-android:78-SNAPSHOT (/Users/rafal/Apps/github/wire-android/build.sbt#L60)
[warn] 		  +- wirecore:wirecore:2.7.99999
[warn] 		com.wearezeta.avs:avs:2.7.19 (/Users/rafal/Apps/github/wire-android/build.sbt#L60)
[warn] 		  +- wirecore:wirecore:2.7.99999
```

not sure how I can resolve this.

**Comment by hakonbo** [comment]
Thanks for the PR @charafau 

We will have a look at it as soon as time permits, hopefully soon, in the mean time can I ask you to have a look at the [CLA](https://cla-assistant.io/wireapp/wire-android?pullRequest=269). We need to have that agreed on before the PR can be merged. 

Thanks again!

**Comment by charafau** [comment]
@hakonbo  thank you. it might be good solution since scala's gradle plugin has stuck on 1.5. I signed up your CLA.

**Comment by hakonbo** [comment]
@charafau great, thanks. @deanrobertcook will take a look, probably not this week though...

**Comment by deanrobertcook** [comment]
Hi @charafau, apologies for the delayed response. There have been a few other tasks demanding my time for the last few weeks...

So, a bit of context: the `message_stream` branch is still itself quite a WIP, and I don't think the SBT build setup was polished for external use. TBH, I relied on the gradle plugin most of the time and another colleague was using the SBT build. 

So the `zmessaging-android` `SNAPSHOT` build can be replaced with another build from the https://github.com/wireapp/wire-android-sync-engine project, or one of the latest public builds (right now: `85.1277`).

As for AVS, I'm not sure why that one didn't work, but you can always update to the latest used in master (`2.8.65@aar`) and that should work fine. Please let me know if it doesn't.

Now I guess you really want to be able to build from master using sbt, in which case you can just rebase your changes with master and I'll happily merge it (we currently don't have an sbt build there, so it shouldn't conflict). Otherwise, I'll hopefully be resuming some work on the `message_stream` branch in the near future, in which case I'll re-evaluate and tidy up the sbt config already there, and incorporate your changes too.

It all falls under a larger, and much longer term plan of merging the two projects and moving towards using scala where possible. Right now it's a bit in between...

I hope that all makes sense and thank-you for you time and effort. Just let me know how you want to proceed. 

PS: I just checked out the https://github.com/scala-android/sbt-android-protify project, and that looks sweet! Thanks for the tip

**Comment by charafau** [comment]
Thanks for response. I will give it a try with master branch then. What tasks is the main one for development purposes ? `installProdDebug` ?

**Comment by deanrobertcook** [comment]
@charafau Generally we use `installDevDebug` for development purposes

**Comment by hakonbo** [comment]
Will close for now as the `message_stream` branch is quite out of sync with master. Feel free to re-open against master though.

**Comment by charafau** [comment]
Sorry for not moving forward. Got busy pipeline lately. Hopefully I will make it happen in near future.

**Pull request closed without merging**
