### PR TITLE
fix: invisible buttons after changes in WireButton size parameters

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

After `minWidth` and `minHeight` were grouped into `minSize` and second parameter `minClickableSize` added to customise the space button really takes if needed, some of the buttons that had size set directly in the passed `modifier` (`Modifier.size(width = X, height = X)`) ended up having paddings applied from the default `minClickableSize` and then size from modifier - in some cases it ended up with too small area for the button.

### Solutions

Removed sizes that are added directly in the passed `modifier`, now it relies only on parameters defined specifically to handle button sizes (`minSize` and `minClickableSize`).
Added previews for all buttons that have `minClickableSize` defined.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by yamilmedina — APPROVED** [review]
Just tested it really quick and looks perfect 🙌

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [706](https://10.10.124.134/job/AR-build-pipeline/706/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7555276)(7555276)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7555276)(7555276)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [714](https://10.10.124.134/job/AR-build-pipeline/714/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7555783)(7555783)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7555783)(7555783)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [721](https://10.10.124.134/job/AR-build-pipeline/721/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7556172)(7556172)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7556172)(7556172)-staging-compat.apk)

**Pull request merged**
