### PR TITLE
refactor: app navigation - compose destinations [RC] [WPB-360] 

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Our navigation is complex, not easy to understand how things work and to make any additional changes, and it’s very difficult to find possible errors. This is also because of the limitations of the standard compose navigation, which works using routes that are intended to be url-like, so there is no type-safety and passing arguments backwards is complicated.

### Solutions

We refactored the navigation to use the Compose Destinations library, which is an overlay on the Official Jetpack Compose Navigation, which allows us to hide the complex, boilerplate code and use type-safe parameters and make the whole navigation graph and process easier and more readable.

#### How to Test

The whole navigation in the app should work as before (or even better).

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [662](https://10.10.124.134/job/AR-build-pipeline/662/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7131658)(7131658)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7131658)(7131658)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [715](https://10.10.124.134/job/AR-build-pipeline/715/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7141665)(7141665)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7141665)(7141665)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [760](https://10.10.124.134/job/AR-build-pipeline/760/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7158499)(7158499)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7158499)(7158499)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [785](https://10.10.124.134/job/AR-build-pipeline/785/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7190526)(7190526)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7190526)(7190526)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [808](https://10.10.124.134/job/AR-build-pipeline/808/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7193609)(7193609)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7193609)(7193609)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [836](https://10.10.124.134/job/AR-build-pipeline/836/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7201353)(7201353)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7201353)(7201353)-staging-compat.apk)

**Comment by saleniuk** [comment]
Closing it as we decided not to merge it to RC 4.3.x, only to develop 4.4.x

**Pull request closed without merging**
