### PR TITLE
feat: migrate cryptobox and client data [AR-2591] [AR-2658]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2591" title="AR-2591" target="_blank">SubtaskAR-2591</a>  migrate users crypto box
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In order to successfully perform a migration from scala app, we need to copy cryptobox files to the appropriate destination and registered client data to the new database.|

### Solutions

Added `isMigrationCompletedFlow` to `ConnectionPolicyManager` not to `startObservingAppLifecycle` until the migration is completed.
Added `ScalaCryptoBoxDirectoryProvider` to get the path of the cryptobox files.
Updated `ScalaUserDatabaseProvider` to be able to get database for multiple users.
Refactored `MigrateActiveAccountsUseCase` to return list of migrated user ids.
Implemented `MigrateClientsDataUseCase` which moves cryptobox files to the proper destination, adds registered client ids and creates the user session to perform a sync after that.

#### How to Test

Install and log in to the scala app and update to the AR version, the app should perform the migration and be already logged in and able to send and receive messages.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1124/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1124/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4792175)(4792175)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4792175)(4792175)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
Awesome ! 🪁

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1124/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4798098)(4798098)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4798098)(4798098)-dev-release.apk)

**Pull request merged**
