### PR TITLE
fix: asset issues for images [AR-2552]

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2552" title="AR-2552" target="_blank">BugAR-2552</a>  Assets(except images) are not visible on remote side
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Fixes the issues of images not being displayed in the AR client, when received from other clients that sends preview messages.

### Solutions

Handle the Preview image message as a new type mapped in UI, before we were handling the image as one.
Also @vitorhugods  added handling of download using Coil mechanism.

Needs releases with:

Upcoming PR on kalium https://github.com/wireapp/kalium/pull/1003 

- [x] GitHub link to other pull request

#### Test Coverage (Optional)

WIP

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1065/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1065/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1065/4/) **failed**.

**Review by gongracr — APPROVED** [review]
Grande compa! Go Go Go 👨‍🎨

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1065/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4592507)(4592507)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4592507)(4592507)-dev-release.apk)

**Pull request merged**
