### PR TITLE
Notification changes

### PR DESCRIPTION
**Pull request by hakonbo**
* Show system notification for new messages in conversations for active account in non-active conversations
* Don't show system notifications for active account when in conversation list view
* Fix for team group conversation notification header

#### APK
[Download build #9580](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9580/artifact/build/artifact/wire-dev-PR1176-9580.apk)
[Download build #9584](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9584/artifact/build/artifact/wire-dev-PR1176-9584.apk)
[Download build #9588](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9588/artifact/build/artifact/wire-dev-PR1176-9588.apk)
[Download build #9602](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9602/artifact/build/artifact/wire-dev-PR1176-9602.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
build again

**Comment by JPonte** [comment]
@hakonbo does this fix AN-5681?

**Comment by hakonbo** [comment]
Yeah, I hope so ;)

**Comment by hakonbo** [comment]
build again

**Pull request merged**
