### PR TITLE
chore: update kalium with java 17 and jenv to 17.0

### PR DESCRIPTION
**Pull request by Garzas**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Updated jenv java version to 17 and kalium

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [558](https://10.10.124.134/job/AR-build-pipeline/558/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7088142)(7088142)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7088142)(7088142)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [586](https://10.10.124.134/job/AR-build-pipeline/586/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7095403)(7095403)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7095403)(7095403)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [619](https://10.10.124.134/job/AR-build-pipeline/619/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7123600)(7123600)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7123600)(7123600)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [627](https://10.10.124.134/job/AR-build-pipeline/627/) **failed**.

**Comment by AndroidBob** [comment]
Build [634](https://10.10.124.134/job/AR-build-pipeline/634/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7124434)(7124434)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7124434)(7124434)-staging-compat.apk)

**Pull request merged**
