### PR TITLE
chore: simplify icon structure

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We're using a mix of .png and .xml files to define our app icons.
An unnecessary complication as it makes it harder to work with.

Instead of importing a single vector icon, transforming it into a vector drawable, we need to handle one png for each pixel density.

Also, vector drawables are easy to copy/paste and edit the colors. Something not easily done with png files.

### Solutions

- Replace all the multiple `ic_launcher_background.png` with their XML equivalent.
- Change the launcher icon reference from `@mipmap` to `@drawable` to accommodate it.

This leaves only the _absolutely necessary_ .png files behind: the ones for Android 25 and below. For our app: Android 7.1 and Android 7.0 are the **only** versions that will use the PNG files.

### Bonus

1. Added back the `monochrome` icon, but **only** to the `prod` flavour, so we can still differentiate internal/debug/staging builds. 
2. Because it was so easy to copy/paste icons and change the colours in the XML files, added icons for `dev` and `staging` build types. So we can also differentiate them better while developing new features and using the staging backend. They're 🔴 Red and 🟠 Orange, respectively.

### Testing

----
#### PR Post Merge Checklist for internal contributors

- [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1733/2/) **failed**.

**Review by ohassine — APPROVED** [review]
Nice ✨🧹 We may need to add Wire copyright to xml files ?

**Comment by vitorhugods** [comment]
> Nice ✨🧹 We may need to add Wire copyright to xml files ?

Good catch :)

Although they are either generated by Android Studio, and the others depict the Wire logo... I'll add them anyway.

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1733/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6362334)(6362334)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6362334)(6362334)-staging-compat.apk)

**Pull request merged**
