### PR TITLE
refactor(rc): split click blocking flag into two - block when syncing and when connecting [AR-2693]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2693" title="AR-2693" target="_blank">BugAR-2693</a>  Can't send the message in offline mode
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Copy of https://github.com/wireapp/wire-android-reloaded/pull/1573

### Issues

Current implementation allows us to only block buttons and clicks until the app is fully synchonized.
If the message send fails, we schedule a worker to retry sending after some time or when the connection is back. At the current stage, we don't want to deal with such complex logic and just mark every message as failed to send when there's an error.

### Solutions

Expand the click blocking mechanism to add another parameter to allow buttons and clicks to be disabled when there is no connection or when the app is syncing (current flag is being split into these two cases). 
Additionally, it updates the kalium reference to use changes related to disabling resending pending messages for all messages and just mark messages as failed if the error occurs during the send, even if it's because of no network. In the near future, we will implement the manual retry mechanism for the user to send such message again.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/1602

#### How to Test

Disable the network and try to send a message.

### Attachments (Optional)

https://user-images.githubusercontent.com/30429749/227153263-79bd69bc-6e86-46f6-93d0-397a5da8acf1.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1587/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1587/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6097095)(6097095)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6097095)(6097095)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
🪄✨

Classy

**Review by ohassine — APPROVED** [review]

**Review by gongracr — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1587/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1587/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6105752)(6105752)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6105752)(6105752)-staging-compat.apk)

**Pull request merged**
