### PR TITLE
feat(calling): adapt video calling for federation (FS-153)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-153" title="FS-153" target="_blank">StoryFS-153</a>  [Android] As a participant of federated calls I like to use video or screen sharing in my calls
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently calling feature works only for non federated backend.

### Solutions

With this PR, the user can enable/disable video in a call.

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

Manually tested

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3631/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3631/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3631/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3631/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3631/5/)

**Comment by ohassine** [comment]
Closing this PR as there is a newer one for this feature #3641

**Pull request closed without merging**
