### PR TITLE
chore(rc): update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [405](https://10.10.124.134/job/AR-build-pipeline/405/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7436030)(7436030)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7436030)(7436030)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [412](https://10.10.124.134/job/AR-build-pipeline/412/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7441692)(7441692)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7441692)(7441692)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [415](https://10.10.124.134/job/AR-build-pipeline/415/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7441976)(7441976)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7441976)(7441976)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [416](https://10.10.124.134/job/AR-build-pipeline/416/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7441992)(7441992)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-v4.4.0(7441992)(7441992)-dev-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Pull request merged**
