### PR TITLE
Multi tasking

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### APK
[Download build #10841](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10841/artifact/build/artifact/wire-dev-PR1558-10841.apk)
[Download build #10844](http://192.168.120.33:8080/job/Pull%20Request%20Builder/10844/artifact/build/artifact/wire-dev-PR1558-10844.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
- [ ] Bug 2
There should be no "Join" button in the conversations list if I'm already in the call

**Comment by AndroidBob** [comment]
test

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
- [ ] Bug 3
add arrow to minimize call

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Pull request merged**
