### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/1/) **failed**.

**Comment by gongracr** [comment]
Currently there is an open issue with Crowdin and the internal processor they enabled for us to use the `zero` modifier for plural translations. It works out of the box for all locales/languages except for the `arabic` one, since for this language, Crowdin already offers a built in tool on their website, so this string comes duplicated, breaking the CI.

Therefore, DO NOT MERGE this PR until this issue has been fixed from their side.

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/3/) **failed**.

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/5/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6181369)(6181369)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6181369)(6181369)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/8/) **failed**.

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/9/) **failed**.

**Comment by AndroidBob** [comment]
Build [11](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/11/) **failed**.

**Comment by AndroidBob** [comment]
Build [14](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/14/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6182002)(6182002)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6182002)(6182002)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [16](https://10.10.124.134/job/wire-android-reloaded/job/PR-1571/16/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6182949)(6182949)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6182949)(6182949)-staging-compat.apk)

**Pull request merged**
