### PR TITLE
refactor: update text input logic to v2 TextFieldState, part 2 [WPB-8779]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-8779" title="WPB-8779" target="_blank">TaskWPB-8779</a>  Introduce BasicTextField2
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Android Compose has new v2 version of text field inputs, and with that, they are going away from the previous approach with `TextFieldValue` and `onValueChanged` and replacing it with `TextFieldState`.
We already updated text fields to v2 but still are using "hybrid" solution which synchronises between `TextFieldValue/onValueChanged` and `TextFieldState`.

In this PR, following screens, their ViewModels logic and tests are updated to use `TextFieldState`:
- LoginEmailScreen
- LoginSSOScreen
- ProxyScreen
- LoginEmailVerificationCodeScreen
- CreateAccountCodeScreen
- CreateAccountDetailsScreen
- CreateAccountEmailScreen

Also, states for login are split into two dedicated for email login and sso login as having one for both was making a confusion, especially when having instances of all three `LoginViewModel`, `LoginEmailViewModel` and `LoginSSOViewModel` was giving impression that the state is shared between them but in theory they could have different values.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Use text fields from any of listed screens.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4944](https://10.10.124.134/job/AR-build-pipeline/4944/) **failed**.

**Comment by AndroidBob** [comment]
Build [4946](https://10.10.124.134/job/AR-build-pipeline/4946/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9750115)(9750115)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9750115)(9750115)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4956](https://10.10.124.134/job/AR-build-pipeline/4956/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9750888)(9750888)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9750888)(9750888)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5048](https://10.10.124.134/job/AR-build-pipeline/5048/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9793333)(9793333)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9793333)(9793333)-staging-compat.apk)

**Review by borichellow — APPROVED** [review]
LGTM 👍

**Review by ohassine — APPROVED** [review]

**Pull request merged**
