### PR TITLE
fix: Remove NotificationDot for some notifications RC

### PR DESCRIPTION
**Pull request by AndroidBob**
Cherry pick from the original PR: 
- #2856

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

# What's new in this PR?

### Issues

NotificationDot (on app icon) shouldn't be shown for the notifications: OngoingCall, PersistentWebSocket, MigrationWorker, NotificationFetchWorker, SingleUserMigrationWorker

### Causes (Optional)

flag  wasn't set to false for those notifications.

### Solutions

set  flag to  for the channels of those notifications.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3989](https://10.10.124.134/job/AR-build-pipeline/3989/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9333943)(9333943)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9333943)(9333943)-staging-compat.apk)

**Review by borichellow — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4000](https://10.10.124.134/job/AR-build-pipeline/4000/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4067](https://10.10.124.134/job/AR-build-pipeline/4067/) **failed**.

**Comment by AndroidBob** [comment]
Build [4072](https://10.10.124.134/job/AR-build-pipeline/4072/) **failed**.

**Pull request merged**
