### PR TITLE
feat: Move mute notification settings to conv options

### PR DESCRIPTION
**Pull request by makingthematrix**
fixes https://github.com/wireapp/android-project/issues/301

In case of group conversations the notifications options (all allowed / mentions only / all muted) should appear on the group participants view, and they should work just as "Timed messages" options. The entry from the bottom popup menu should be removed. In case of one-to-one conversations the notifications options should stay in the bottom popup menu.

Note: We are waiting for the WireStyleKit notification icon from the Design. Right now I use the "Mute" icon instead. The code can be reviewed and tested as it is.
#### APK
[Download build #11879](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11879/artifact/build/artifact/wire-dev-PR1841-11879.apk)
[Download build #11880](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11880/artifact/build/artifact/wire-dev-PR1841-11880.apk)
[Download build #11886](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11886/artifact/build/artifact/wire-dev-PR1841-11886.apk)
[Download build #11887](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11887/artifact/build/artifact/wire-dev-PR1841-11887.apk)
[Download build #11985](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11985/artifact/build/artifact/wire-dev-PR1841-11985.apk)
[Download build #11986](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11986/artifact/build/artifact/wire-dev-PR1841-11986.apk)
[Download build #11999](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11999/artifact/build/artifact/wire-dev-PR1841-11999.apk)
[Download build #12034](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12034/artifact/build/artifact/wire-dev-PR1841-12034.apk)

### CODE REVIEW

**Comment by red-avtovo** [comment]
Bug 1
There is no Notifications option in options menu, when I long press on group conversation

**Comment by red-avtovo** [comment]
screenshot_20181018-171755

**Comment by JPonte** [comment]
This is a pro only feature, but in personal accounts' groups I can see it in the options.

**Comment by someoneEsle** [comment]
build again

**Comment by someoneEsle** [comment]
By the way, it should say "Mentions and replies" instead of "Only mentions". I know it may not have been part of this PR because it was only changed only with the current sprint, but since it's just a string replacement it probably makes sense to change it now before we forget

**Comment by red-avtovo** [comment]
Omar is right, there is no reason not to comply to the latest specs

**Comment by makingthematrix** [comment]
Ok, I changed the name and moved the value text below the name text, as the new design doc requires.

**Pull request merged**
