### PR TITLE
feat: [RC] crash app on migration erorrs

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues
@MohamadJaara
[chore: crash the migration worker if there is an error (](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/6e5e235d72f2db9b0a6e449ebe92afdc64b2cde7)https://github.com/wireapp/wire-android-reloaded/pull/1579[)](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/6e5e235d72f2db9b0a6e449ebe92afdc64b2cde7)
[6e5e235](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/6e5e235d72f2db9b0a6e449ebe92afdc64b2cde7)
@MohamadJaara
[feat: redo migration on app update when failure (](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/7468f11ffd1a0d8024e79e693c1c8ee0b269c346)https://github.com/wireapp/wire-android-reloaded/pull/1584[)](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/7468f11ffd1a0d8024e79e693c1c8ee0b269c346)
[7468f11](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/7468f11ffd1a0d8024e79e693c1c8ee0b269c346)
@MohamadJaara
[fix: check if user is logged in after migraion error (](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/beb615521449c57f6954cec503a9bfbab94f1e49)https://github.com/wireapp/wire-android-reloaded/pull/1607[)](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/beb615521449c57f6954cec503a9bfbab94f1e49)
[beb6155](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/beb615521449c57f6954cec503a9bfbab94f1e49)
@MohamadJaara
[fix: try catch migration errors and include the report when failing (](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/bf892cd2b9294cc40c629055c26d4d6717cc3661)https://github.com/wireapp/wire-android-reloaded/pull/1616
[bf892cd](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/bf892cd2b9294cc40c629055c26d4d6717cc3661)
@MohamadJaara
[fix: propagate migration errors to the UI and crash in the view model (](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/98e7035cf33c2b4490423cdd2c815bc1036e5a8a)https://github.com/wireapp/wire-android-reloaded/pull/1628
[98e7035](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/98e7035cf33c2b4490423cdd2c815bc1036e5a8a)
@MohamadJaara
[fix: merge issues](https://github.com/wireapp/wire-android-reloaded/pull/1658/commits/d3a029904732cf071ff0ed897b583c15bc2980d0)

----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1658/1/) **failed**.

**Review by vitorhugods — APPROVED** [review]
👨‍🍳👌

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1658/2/) **failed**.

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1658/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1658/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6233955)(6233955)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6233955)(6233955)-staging-compat.apk)

**Pull request merged**
