### PR TITLE
fix: Block user toast is not visible (AR-2809)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2809" title="AR-2809" target="_blank">BugAR-2809</a>  Block user toast message is sometimes not visible
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

On OtherUserProfileScreen: when blocking the user, the sneckbar "User was blocked" is not visible.

### Causes (Optional)

Cause it's covered by bottomsheet menu. For some reason (still don't get why) bottomsheet can't be hidden while its content is changing.
 
So we have 2 actions at the same time: 
1. changing BS content, cause user was blocked.
2. closing BS
Sometimes (in most cases) BS is not hidden 🤷‍♂️

### Solutions

Close BS when user click "ok" in blockUserDialog, instead of when user was actually blocked.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1240/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1240/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5221428)(5221428)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5221428)(5221428)-dev-compat.apk)

**Review by MohammedMokresh — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1240/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5247048)(5247048)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5247048)(5247048)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1240/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5248027)(5248027)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5248027)(5248027)-dev-compat.apk)

**Pull request merged**
