### PR TITLE
chore: update jenkins emulator image to use 14 (rc)

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some instrumented tests were failing on emulator 10 (CI only), locally and GH actions they are green.

### Causes (Optional)

Flaky tests.

### Solutions

Try it out latest emulator with Android 14

### Dependencies (Optional)

[x] Image pulled in the host machine.

#### How to Test

Instrumentation tests must be green

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2841](https://10.10.124.134/job/AR-build-pipeline/2841/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8790024)(8790024)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8790024)(8790024)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2845](https://10.10.124.134/job/AR-build-pipeline/2845/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8790534)(8790534)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8790534)(8790534)-staging-compat.apk)

**Comment by yamilmedina** [comment]
wont merge, got solved by #2657

**Comment by AndroidBob** [comment]
Build [2849](https://10.10.124.134/job/AR-build-pipeline/2849/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8790963)(8790963)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8790963)(8790963)-staging-compat.apk)

**Pull request closed without merging**
