### PR TITLE
fix(RC): adjust transition animations according to the design documentation [WPB-1817]

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

Copy of https://github.com/wireapp/wire-android-reloaded/pull/2138

### Issues

Current transition animations are not fully aligned with the design documentation.

### Solutions

New and existing transition animations and their parameters adjusted to the design documentation, in consultation with Wolfgang. Created `TransitionAnimationType` with both animation types (slide and pop-up) and set default enter, exit, popEnter and popExit animations for them. Provided more destination styles to be able to set custom transitions for some screens. Basically, every screen having X button instead of back arrow should use the "pop-up" animation. Implemented base `DestinationStyleAnimated` interface to handle the logic of choosing the right transition animation depending on the recently opened destination, to not mix two transition styles when both destinations involved in the transition use different styles.

### Attachments (Optional)

https://github.com/wireapp/wire-android-reloaded/assets/30429749/76020c93-1951-472a-b8fd-42352e5802d1

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [497](https://10.10.124.134/job/AR-build-pipeline/497/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7485977)(7485977)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7485977)(7485977)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [506](https://10.10.124.134/job/AR-build-pipeline/506/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7486875)(7486875)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7486875)(7486875)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [520](https://10.10.124.134/job/AR-build-pipeline/520/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7487551)(7487551)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7487551)(7487551)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [535](https://10.10.124.134/job/AR-build-pipeline/535/) **failed**.

**Comment by AndroidBob** [comment]
Build [540](https://10.10.124.134/job/AR-build-pipeline/540/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7493253)(7493253)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7493253)(7493253)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Pull request merged**
