### PR TITLE
feat(calling): adapt audio calling for federation #FS-11

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-11" title="FS-11" target="_blank">TaskFS-11</a>  [Android] As a user, I can place a call with a user in my contact list who is part of a federated backend
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently calling feature works only for non federated backend.

### Solutions
This PR aims to adapt calling with federation by allowing user to start, answer and end/reject a federated audio call.
Next PR will for video calls.

### Testing

Manually tested

----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/4/)

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/5/)

**Comment by AndroidBob** [comment]
Build Failure
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/6/)

**Comment by AndroidBob** [comment]
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/7/)

**Comment by AndroidBob** [comment]
Build Failure
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/8/)

**Comment by ohassine** [comment]
build again

**Comment by AndroidBob** [comment]
Build Success
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/9/)

**Comment by AndroidBob** [comment]
Build Success
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/10/)

**Comment by AndroidBob** [comment]
Build Success
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3630/11/)

**Comment by ohassine** [comment]
Closing this PR as there is a newer one for this feature #3641

**Pull request closed without merging**
