### PR TITLE
feat: support building with custom backends

### PR DESCRIPTION
**Pull request by vitorhugods**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Only Wire's `Staging` and `Production` backends can be selected when building Reloaded.
Some customers might have a self-hosted backend with a custom app.

### Solutions

Instead of using a flag for selection between backends, just use the `default.json` (and then `custom.json`) to list all the default backend definitions.

> **Note**: The more I fiddle with feature configs, the more I'd love to have a dedicated Gradle Plugin that will generate actual Kotlin code instead of a huge `BuildConfigs` Java file.

### Testing

Manually tested. Compiler will also scream if things are null.

----
#### PR Post Merge Checklist for internal contributors

- [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by ohassine — APPROVED** [review]
✨

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1674/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6251007)(6251007)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6251007)(6251007)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1674/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1674/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6277430)(6277430)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6277430)(6277430)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1674/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6292432)(6292432)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6292432)(6292432)-staging-compat.apk)

**Pull request merged**
