### PR TITLE
fix: rename group screen UI [AR-2788]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2788" title="AR-2788" target="_blank">BugAR-2788</a>  [Edit conversation name] Triggering a system message only upon change, wrong label & title
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

- system notification is triggered about a change in the group name even if the name is the same
- the button on the bottom has the wrong label (“Continue”)
- the button on the bottom is enabled even if there is no change
- the “group name” page has the wrong title (should be “Group Name”, not the actual group name)
- the input is not centered on the screen
- the screen is not scrollable on smaller screens

### Solutions

Fix all of the issues listed above.

#### How to Test

Open "edit name" screen to change the name or "create new group" screen to see how it behaves with the additional dropdown.

#### Before:

https://user-images.githubusercontent.com/30429749/209832098-d9706587-5de8-4009-afaf-d0f8d29e3537.mp4

#### After:

https://user-images.githubusercontent.com/30429749/209832152-092cfd3f-9371-4040-becc-31e1cdd04d9c.mp4

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1267/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5327395)(5327395)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5327395)(5327395)-dev-compat.apk)

**Review by Garzas — APPROVED** [review]
LGTM 🥇

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1267/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5334668)(5334668)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5334668)(5334668)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1267/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5342826)(5342826)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5342826)(5342826)-dev-compat.apk)

**Pull request merged**
