### PR TITLE
[AN-5805] Logging in with phone should always request verification code

### PR DESCRIPTION
**Pull request by JPonte**
SE PR: https://github.com/wireapp/wire-android-sync-engine/pull/280/

Dev build with new SE:
https://drive.google.com/open?id=1IE3aGG2VfpyIxeOPlLKy-Wppd-j1wsPa
#### APK
[Download build #9946](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9946/artifact/build/artifact/wire-dev-PR1314-9946.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Bug 1
Create account with phone number
You are prompted to type your password (which you do not have)

**Comment by someoneEsle** [comment]
Bug 2
Sign in with any account
Add an account that has phone number and email. Sign in using phone number, and type the password when required.
Log ouf of this last account
Try to log in again using phone number. After typing the verification code, no password is required to see the conversation list

**Comment by someoneEsle** [comment]
bug 3
- Log in with 2 accounts, A and B. A can be anything, B has phone number only.
- B logs out.
- Try to log back in using B. Type phone number, type verification code --> now you see the conversations list of A, and there is no B account anywhere in the app.

**Comment by someoneEsle** [comment]
Bug 3 does not seem to be related to this PR

**Comment by deanrobertcook** [comment]
Is this meant to be in 3.3?

**Pull request merged**
