### PR TITLE
chore: update translation strings via Crowdin

### PR DESCRIPTION
**Pull request by gongracr**

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1747/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6373037)(6373037)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6373037)(6373037)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1747/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6404837)(6404837)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6404837)(6404837)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1747/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6405174)(6405174)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6405174)(6405174)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1747/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6406959)(6406959)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6406959)(6406959)-staging-compat.apk)

**Pull request merged**
