### PR TITLE
fix: use compatibility build profile for the dev flavour [AR-2776]

### PR DESCRIPTION
**Pull request by sysvinit**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2776" title="AR-2776" target="_blank">TaskAR-2776</a>  Update product flavours
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

QA wants to test the upgrade path from the old Scala app to Reloaded. As Android requires the same signing key to be used when upgrading an application to a newer version, this means that we need the Reloaded APK to be signed with the old app's key. We only want to change the signing key for the `dev`-flavoured build, to allow QA to test the upgrade functions without interfering with our existing beta testers.

The build scripts for Reloaded have two build configurations, `debug` and `release`; orthogonally, there are (at least) three different build *flavours*: `public`, `internal`, and `dev`. The Jenkins pipeline is configured to use different signing keys for `debug` and `release` builds, but presently does not have any logic for switching the signing keys for different build flavours.

However, while the build scripts default to using the debug config, the Jenkins pipeline is hardcoded to override this to use the release config.

### Solutions

**Edit:** I've changed my approach here. I had missed the fact that building clients in the `debug` configuration adds a ".debug" suffix to the application ID, which means that it's not possible to use a `dev+debug` debug build of Reloaded to upgrade over a `dev+release` version of the Scala app.

After much frustration with Gradle and some help from @MohamadJaara, we've opted instead to extend the build scripts with a third `compat` build flavour, which is otherwise identical to `release` other than using a different signing configuration. The Jenkins pipeline is updated in this PR to build `dev` clients in the `compat` config, and at the time of writing I've updated the Jenkins configuration with the required environment variables to use the Scala app's signing keys for the `compat` profile.

**Old solution:**

*As a first step, I have extended the logic of the pipeline to use the debug build config when compiling `dev`-flavoured builds. This decouples the signing configuration for `dev` from the signing configuration for `internal` and `public`, so once this change is in `develop`, the configuration in Jenkins can be updated so that the old Scala app's signing key is used for debug builds, which will only affect the `dev` flavour.*

#### How to Test

- Observe that builds on this PR branch should be compiled in the debug configuration.
- Once the keystore configuration in Jenkins has been updated, check whether builds on this PR branch can be installed over an install of the old Scala client with the same application ID.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5196522)(5196522)-dev-debug.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/debug/com.wire.android-vv0.0.1(5196522)(5196522)-dev-debug.apk)

**Comment by sysvinit** [comment]
> Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/1/) **succeeded**.
> 
> The build produced the following APK's:
> 
>     * [com.wire.android-vv0.0.1(5196522)(5196522)-dev-debug.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/debug/com.wire.android-vv0.0.1(5196522)(5196522)-dev-debug.apk)

This appears to be a debug build, based on the filename at least. I've just updated the Jenkins side to use the old app's dev signing key, so I'll manually kick off another build to test with that.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5196683)(5196683)-dev-debug.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/debug/com.wire.android-vv0.0.1(5196683)(5196683)-dev-debug.apk)

**Comment by sysvinit** [comment]
> 



> Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/2/) **succeeded**.
> 
> The build produced the following APK's:
> 
>     * [com.wire.android-vv0.0.1(5196683)(5196683)-dev-debug.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/debug/com.wire.android-vv0.0.1(5196683)(5196683)-dev-debug.apk)

@MohamadJaara @CinnamonNinja ^ take this one for a spin.

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5198641)(5198641)-dev-debug.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/debug/com.wire.android-vv0.0.1(5198641)(5198641)-dev-debug.apk)

**Comment by sysvinit** [comment]
After spending an afternoon working on this, I've decided that instead of trying to change the debug build flavour, introducing a new "compatiblity" build flavour would work better. I've updated the PR title and description accordingly.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5206671)(5206671)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5206671)(5206671)-dev-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
🚀

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1228/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5213304)(5213304)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5213304)(5213304)-dev-compat.apk)

**Pull request merged**
