### PR TITLE
[AN-5767] Create team account flow

### PR DESCRIPTION
**Pull request by JPonte**
#### APK
[Download build #9784](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9784/artifact/build/artifact/wire-dev-PR1270-9784.apk)
[Download build #9785](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9785/artifact/build/artifact/wire-dev-PR1270-9785.apk)
[Download build #9786](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9786/artifact/build/artifact/wire-dev-PR1270-9786.apk)
[Download build #9787](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9787/artifact/build/artifact/wire-dev-PR1270-9787.apk)
[Download build #9788](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9788/artifact/build/artifact/wire-dev-PR1270-9788.apk)
[Download build #9789](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9789/artifact/build/artifact/wire-dev-PR1270-9789.apk)
[Download build #9790](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9790/artifact/build/artifact/wire-dev-PR1270-9790.apk)
[Download build #9791](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9791/artifact/build/artifact/wire-dev-PR1270-9791.apk)
[Download build #9792](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9792/artifact/build/artifact/wire-dev-PR1270-9792.apk)
[Download build #9793](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9793/artifact/build/artifact/wire-dev-PR1270-9793.apk)
[Download build #9794](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9794/artifact/build/artifact/wire-dev-PR1270-9794.apk)
[Download build #9795](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9795/artifact/build/artifact/wire-dev-PR1270-9795.apk)
[Download build #9796](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9796/artifact/build/artifact/wire-dev-PR1270-9796.apk)
[Download build #9797](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9797/artifact/build/artifact/wire-dev-PR1270-9797.apk)
[Download build #9800](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9800/artifact/build/artifact/wire-dev-PR1270-9800.apk)
[Download build #9802](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9802/artifact/build/artifact/wire-dev-PR1270-9802.apk)
[Download build #9803](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9803/artifact/build/artifact/wire-dev-PR1270-9803.apk)
[Download build #9804](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9804/artifact/build/artifact/wire-dev-PR1270-9804.apk)
[Download build #9807](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9807/artifact/build/artifact/wire-dev-PR1270-9807.apk)
[Download build #9811](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9811/artifact/build/artifact/wire-dev-PR1270-9811.apk)
[Download build #9817](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9817/artifact/build/artifact/wire-dev-PR1270-9817.apk)
[Download build #9823](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9823/artifact/build/artifact/wire-dev-PR1270-9823.apk)
[Download build #9827](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9827/artifact/build/artifact/wire-dev-PR1270-9827.apk)
[Download build #9831](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9831/artifact/build/artifact/wire-dev-PR1270-9831.apk)
[Download build #9834](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9834/artifact/build/artifact/wire-dev-PR1270-9834.apk)
[Download build #9837](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9837/artifact/build/artifact/wire-dev-PR1270-9837.apk)
[Download build #9839](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9839/artifact/build/artifact/wire-dev-PR1270-9839.apk)
[Download build #9840](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9840/artifact/build/artifact/wire-dev-PR1270-9840.apk)
[Download build #9841](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9841/artifact/build/artifact/wire-dev-PR1270-9841.apk)
[Download build #9843](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9843/artifact/build/artifact/wire-dev-PR1270-9843.apk)
[Download build #9844](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9844/artifact/build/artifact/wire-dev-PR1270-9844.apk)
[Download build #9848](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9848/artifact/build/artifact/wire-dev-PR1270-9848.apk)
[Download build #9854](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9854/artifact/build/artifact/wire-dev-PR1270-9854.apk)
[Download build #9856](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9856/artifact/build/artifact/wire-dev-PR1270-9856.apk)
[Download build #9857](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9857/artifact/build/artifact/wire-dev-PR1270-9857.apk)
[Download build #9861](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9861/artifact/build/artifact/wire-dev-PR1270-9861.apk)
[Download build #9862](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9862/artifact/build/artifact/wire-dev-PR1270-9862.apk)
[Download build #9863](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9863/artifact/build/artifact/wire-dev-PR1270-9863.apk)
[Download build #9873](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9873/artifact/build/artifact/wire-dev-PR1270-9873.apk)
[Download build #9874](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9874/artifact/build/artifact/wire-dev-PR1270-9874.apk)
[Download build #9875](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9875/artifact/build/artifact/wire-dev-PR1270-9875.apk)
[Download build #9881](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9881/artifact/build/artifact/wire-dev-PR1270-9881.apk)
[Download build #9884](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9884/artifact/build/artifact/wire-dev-PR1270-9884.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Bug 1
There is no back arrow in the top left corner in the first screen

Bug 2
"What is wire for teams?" should link to the right page (I know you know, but if I post it here I will remember to not remove the QA label until it's fixed)

Bug 3
On SET EMAIL page, if I type a badly formatted email it says "Unauthorized email or phone number". "Phone number" should not be part of the string.

Bug 4 - Eike
The copy needs to change -- see pdf from design

Bug 5 - Eike
The subtitles in every page need to have a bigger font

Bug 6 - Eike
The container with Create account and Create Team should be vertically centered (it's too far down right now)

Bug 7 - Eike
Log in instead of Login

Bug 8
When you type your verification code, you are taken to the next screen. From here, you can go back: if you do, you will never be able to go forward again -- tapping the code you wrote doesn't bring up the keyboard or anything, there is no arrow anywhere, we're stuck

Bug 9
When you go into your profile view, tapping Create team and Add account should take you to the right section of the new flow (you shouldn't be redirected to a web page, and you shouldn't see the new welcome screen)

Bug 10
If on any page I tap "back", and edit the information I previously typed, going forward I should not see the old stuff I typed before going back (hope it makes sense)

**Comment by someoneEsle** [comment]
Bug 11
Type an invalid activation code. Then tap the last digit in the code. The cursor is now on the second (no idea why this is even happening)

Bug 12
Why can I only delete the activation code starting from the last digit? Can't I decide to only delete one digit? If I mistyped the first one I'll have to retype the whole code

Bug 13
ToS should be accepted when creating the password

Bug 14
There is no page to invite people

Bug 15
We should remove the page where we ask users to set a profile picture

Note to self: check the copy on every page
Note to joao: implement the copy design requested

**Comment by someoneEsle** [comment]
Bug 20 - Eike
the 2 text buttons in the code screen have a weird box appear around them when tapped, that should not be there

**Comment by someoneEsle** [comment]
Bug 21
When logging in via email, after you type email/password and confirm, there is no spinner that tells you that the app is working.

**Comment by someoneEsle** [comment]
Bug 22
go back and forward between two screens -- at some point the titles overlap

**Comment by someoneEsle** [comment]
Bug 23
If I tap next on the keyboard, I should go to the next screen

**Comment by someoneEsle** [comment]
Bug 24
Deleting the code one digit at a time and typing new digit works in unexpected ways

**Comment by someoneEsle** [comment]
Bug 25
When I tap the back arrow on "Name your team", we should close the keyboard

Bug 26
On any of the pages of the team creation, lock the screen. When you turn it back on, you see the animation

**Comment by someoneEsle** [comment]
Bug 27
When I try to log in (I'm not sure how this code got affected) it takes forever to load the next page after typing email/password, and no spinner is shown

**Comment by someoneEsle** [comment]
Bug 27
I can enter an empty Team name

**Comment by someoneEsle** [comment]
Bug 28
Type team name, see the "Accept terms" dialogue, click back without accepting. Enjoy the spinning wheel :D

**Comment by someoneEsle** [comment]
Bug 29
The first time you land on "Your account" page, if you type an email and click ">" on the keyboard, nothing happens. You can only tap the blue arrow on the text field

**Comment by someoneEsle** [comment]
Bug 30
When typing the code, if I tap "delete" on the keyboard I can only delete one digit.

**Comment by someoneEsle** [comment]
Bug 31
Typing the wrong verification code should display an error message more meaningful than "Try to register again". Probably something that mentions the fact that the user typed the wrong code

**Comment by someoneEsle** [comment]
Bug 32
On "Set password" we display the hint "at least 8 characters", but the arrow turns blue/clickable after you type 6. And you can actually go to the next screen -- didn't check if we get an error from backend in the logs, but something is wrong here

**Comment by someoneEsle** [comment]
Bug 33
Open profile > Tap New team or account > Create a team > Tap back button. I should see the profile now, but I'm seeing the welcome screen instead.

Bug 34
Disable the create team button if I'm already logged in with 2 accounts

**Comment by someoneEsle** [comment]
Bugs -- Eike
- All error messages should be uppercase
- code entry screen: should not have a back button
- set password screen: it says "at least 8 characters" but the button to proceed becomes active after 6 characters already and it works
- error messages are not always correct. for example: i entered a username and got the error "this email is already in use"

**Comment by someoneEsle** [comment]
Bug 35
After you create a team, you see the empty conversations list. Now go to settings, create a team -> all the fields are already prefilled

Bug - Eike
the log in button on the first screen is too close to the text "Already have an account?". Move the log in a few points down

**Comment by someoneEsle** [comment]
Bug 36
I can create a team whose name is blank spaces only

**Comment by someoneEsle** [comment]
Bug 37
"Name your team" and the back arrow are too close

**Comment by someoneEsle** [comment]
Bug 38
Deleting one digit of the code deletes two

**Comment by someoneEsle** [comment]
Bug 39
Add an @ at the beginning of the username

**Comment by someoneEsle** [comment]
Bug 40
After typing the correct code, you can navigate back to the previous screen by tapping the back button. Wait a second. App crashes

**Comment by someoneEsle** [comment]
Bug 41
Enter an invalid code. Lock the screen. Now you can't edit the code anymore

**Comment by someoneEsle** [comment]
Bug 42
Right before seeing the conversations list, I see the "pick username" takeover for half a second.

**Comment by someoneEsle** [comment]
Bug 43
Logging out from all the accounts should take you to the welcome screen, not login or create a team.

**Comment by someoneEsle** [comment]
Notes
- get rid of touch interactions -- only make the text a lighter color
- margin between "what is wire for teams?" and the keyboard should be smaller

**Comment by someoneEsle** [comment]
Bug 44
Using Swype as keyboard, the titles of the pages go way out of the screen

**Comment by someoneEsle** [comment]
Bug 45 - Eike
all the subtitles should end with the full period

Bug 46
input field should always high the same

**Comment by JPonte** [comment]
Code view shouldn't be displayed after back from set password

**Comment by someoneEsle** [comment]
Tracking bugs

- registration.opened_phone_signup should be removed
- tapping Log In should trigger start.opened_login, not start.opened_person_registration
- "method": "copy_paste" should appear only if I actually pasted the code (which I didn't)
- team.verified was not triggered
- settings.opted_in_tracking is logged after creating a password. ?
- registration.added_photo is logged even if I didn't add any photo

**Comment by eike96** [comment]
"your account" screen: headline and description are still too far down. should be same position as headline in other screens

**Pull request merged**
