### PR TITLE
fix: Doubled notification for attachment message (AR-2894)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2894" title="AR-2894" target="_blank">BugAR-2894</a>  Two notifications are displayed when we receive assets/images/pings
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

When we receive an asset/image or ping, we receive 2 notifications for this

### Causes (Optional)

there are 3 reasons for that:

### 1. 
in `MessageNotificationManager` there is a filtering "if such a notification is already displayed" ()
```
activeMessages?.find { it.text == notificationMessage.text && it.timestamp == notificationMessage.timestamp } == null
```
but the problem is that attachment and ping messages has italic style, so `it.text == notificationMessage.text` is false for them even if the text is the same. 

### 2. 
when the app goes into background observing the messages for the notifications is not stoped, connection dropped, but observing keeps going in a coroutine scope. So when the new message comes -> FCM comes -> `fetchAndShowNotificationsOnce` is called -> connect to websockets. As a result we observe notifications in 2 flows: in `triggerSyncForUserIfAuthenticated` and in `observeNotificationsAndCalls` (it wasn't canceled, remember?). And both of that flows emit a new notification. As far as "duplicate-filtering" doesn't work for such messages (explanation in `reason #1`) user gets 2 notifications. 

### 3. 
in `WireActivityViewModel` we observe `PersistentWebSocketConnectionStatus`, it returns all the logged-in userIds and their flags if they turned on PersistentWebSocketConnection. The idea: if user enabled PersistentWebSocketConnection -> no need to observe notifications it's already observer in `PersistentWebSocketConnectionService`, if not -> observe the notifications for such a user. 
But there was an error: the observing notifications was always called for the `currentUser` and not for the user that is checked ;P 

### 1.
check `it.text.toString() == notificationMessage.text.toString()` for the notification to check only the text and ignore its styles

### 2.
in `WireNotificationManager`: save all the users and "observing notifications job" for them into `observingJobs` hashMap.
Every time we when we want to start observing notifications for some user check if it's already observed (jobs present in `observingJobs`) and cancel and remove those jobs from the `observingJobs` if user was logged out.

### 3.
call `observeNotificationsAndCalls` for all the users that disabled PersistentWebSocketConnection.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/3/) **failed**.

**Review by MohammedMokresh — APPROVED** [review]
LGTM

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5428765)(5428765)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5428765)(5428765)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/6/) **failed**.

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1285/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5429893)(5429893)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5429893)(5429893)-dev-compat.apk)

**Pull request merged**
