### PR TITLE
Make a dev option for creating convs with up to 256 users

### PR DESCRIPTION
**Pull request by makingthematrix**

### CODE REVIEW

**Comment by someoneEsle** [comment]
- [ ] Bug 1
Creating an empty conversation actually creates an empty conversation instead of selecting 255 people. Tested on QA test 27 (Moto E on my desk)

**Comment by makingthematrix** [comment]
build again

**Comment by someoneEsle** [comment]
(still not working)

**Comment by someoneEsle** [comment]
(still not working)

**Comment by someoneEsle** [comment]
- [ ] Bug 2
intent.action.HIDE_GDPR_POPUPS is not working anymore

**Comment by deanrobertcook** [comment]
update to SE `124.2079` and then we can merge

**Pull request merged**
