### PR TITLE
chore: update compose to version 1.5

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

This PR aims to upgrade to compose 1.5
Upgrading to that version requires usage of API 34

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [853](https://10.10.124.134/job/AR-build-pipeline/853/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [858](https://10.10.124.134/job/AR-build-pipeline/858/) **failed**.

**Comment by AndroidBob** [comment]
Build [868](https://10.10.124.134/job/AR-build-pipeline/868/) **failed**.

**Comment by AndroidBob** [comment]
Build [869](https://10.10.124.134/job/AR-build-pipeline/869/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7624105)(7624105)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7624105)(7624105)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [884](https://10.10.124.134/job/AR-build-pipeline/884/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7632717)(7632717)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7632717)(7632717)-staging-compat.apk)

**Pull request merged**
