### PR TITLE
fix: 1:1 calls can not be established on staging environment (WPB-9359) - approach 3 

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-9359" title="WPB-9359" target="_blank">BugWPB-9359</a>  [Android] 1:1 calls can not be established on staging environment
  </td></table>
  <br />
 

…ta build

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

1:1 calls can not be established.

### Causes (Optional)

After extracting calls to another Activity, the app cannot observe its lifecycle state properly.

### Solutions

Move observing from `WireActivity` to `WireApplication` so that it's in one place and the state is consistent across the app.

#### How to Test

STR:
- Login to staging env on android as user A
- Login to saging env on web as user B
- Start a 1:1 call on android as user A
- Pick it up on web as user B

Expected: 
- 1:1 call should be established

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4989](https://10.10.124.134/job/AR-build-pipeline/4989/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9758764)(9758764)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9758764)(9758764)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4990](https://10.10.124.134/job/AR-build-pipeline/4990/) **failed**.

**Comment by AndroidBob** [comment]
Build [4991](https://10.10.124.134/job/AR-build-pipeline/4991/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9783019)(9783019)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9783019)(9783019)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Pull request merged**
