### PR TITLE
fix: muting group conversation from details screen not working [WPB-4994]

### PR DESCRIPTION
**Pull request by gongracr**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4994" title="WPB-4994" target="_blank">BugWPB-4994</a>  [Android]- Muting conversation from group details to nothing or mention&replies, does not apply
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

App was not muting group conversations because the mapping when receiving the click event, was not being done correctly.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1364](https://10.10.124.134/job/AR-build-pipeline/1364/) **failed**.

**Review by borichellow — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1369](https://10.10.124.134/job/AR-build-pipeline/1369/) **failed**.

**Comment by AndroidBob** [comment]
Build [1402](https://10.10.124.134/job/AR-build-pipeline/1402/) **failed**.

**Comment by AndroidBob** [comment]
Build [1406](https://10.10.124.134/job/AR-build-pipeline/1406/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7866567)(7866567)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7866567)(7866567)-staging-compat.apk)

**Pull request merged**
