### PR TITLE
chore: temp local avs dependency until deployed to artifactory

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently, the AVS lib is not available on Sonatype, causing that the current workaround -creating a module for this dependency and adding it as a project- to break autocompletion and running tests on the IDE.

### Solutions

Point to a local -temp- m2 defined repo, leaving untouched the calling module. So when we bump to the proper version in artifactory, that one will be picked automatically over this local repo. Also added a repository filter, so we don't waste time in other project dependencies.

#### How to Test

Checkout the branch, and you should be able to build, and run specific tests on the project

#### Note

After the version is published on artifactory, we can remove the whole `avs` directory.

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1313/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1313/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5440981)(5440981)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5440981)(5440981)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1313/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5441623)(5441623)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5441623)(5441623)-dev-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1313/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5442820)(5442820)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5442820)(5442820)-dev-compat.apk)

**Pull request merged**
