### PR TITLE
fix: !!!DO NOT MERGE IT!!!  develop Stuck on Waiting for network after new client [WPB-401]

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-401" title="WPB-401" target="_blank">BugWPB-401</a>  Stuck on connecting after account was used on another device (with app in the background)
  </td></table>
  <br />
 

Just applying changes from [kalium PR ](https://github.com/wireapp/kalium/pull/1772). To get a build and be able test it

## Important
I hade to remove `WIP` and `DO NOT MERGE` label so Jenkins create a build for testing, but this PR should not be merged yet!!!

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1834/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1834/2/) **failed**.

**Review by vitorhugods — COMMENTED** [review]
Keep in mind that this PR is currently switching kalium reference to `fix/develop_stuck_on_waiting_for_network_after_new_client` so it's no longer on `develop`.

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1834/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1834/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6698849)(6698849)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6698849)(6698849)-staging-compat.apk)

**Comment by borichellow** [comment]
fix doesn't work

**Pull request closed without merging**
