### PR TITLE
feat: legal hold indicators on group details screens [WPB-4569]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4569" title="WPB-4569" target="_blank">StoryWPB-4569</a>  [Android] LH indication for in group details view
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Wire users need to see information about LH in the conversation details view.

### Solutions

Add clickable legal hold banner to the conversation details header info - after clicking it opens a dialog with the information about the legal hold.
Add legal hold indicators on participants list for group members that are under legal hold.

#### How to Test

Have at least one member of the group under legal hold and open the group details screen.

### Attachments (Optional)

https://github.com/wireapp/wire-android/assets/30429749/a454a2b7-c87a-464b-8917-6cda389f5f83

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3149](https://10.10.124.134/job/AR-build-pipeline/3149/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8895343)(8895343)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8895343)(8895343)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3212](https://10.10.124.134/job/AR-build-pipeline/3212/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8937275)(8937275)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8937275)(8937275)-staging-compat.apk)

**Review by borichellow — APPROVED** [review]
looks good :)

**Review by vitorhugods — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3231](https://10.10.124.134/job/AR-build-pipeline/3231/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(8945571)(8945571)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(8945571)(8945571)-staging-compat.apk)

**Pull request merged**
