### PR TITLE
refactor: Remove remoteMap from ConversationStorage

### PR DESCRIPTION
**Pull request by makingthematrix**
https://github.com/wireapp/wire-android-sync-engine/pull/431

Please test new connections requests and performance on old devices.
Merge only if the performance is not visibly worse. 

#### APK
[Download build #11792](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11792/artifact/build/artifact/wire-dev-PR1814-11792.apk)
[Download build #11803](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11803/artifact/build/artifact/wire-dev-PR1814-11803.apk)
[Download build #11804](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11804/artifact/build/artifact/wire-dev-PR1814-11804.apk)
[Download build #11836](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11836/artifact/build/artifact/wire-dev-PR1814-11836.apk)
[Download build #11881](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11881/artifact/build/artifact/wire-dev-PR1814-11881.apk)
[Download build #11971](http://192.168.120.33:8080/job/Pull%20Request%20Builder/11971/artifact/build/artifact/wire-dev-PR1814-11971.apk)
[Download build #12004](http://192.168.120.33:8080/job/Pull%20Request%20Builder/12004/artifact/build/artifact/wire-dev-PR1814-12004.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
@makingthematrix I would say use `refactor` instead of `chore`

**Comment by red-avtovo** [comment]
What does it affect?

**Comment by red-avtovo** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Comment by red-avtovo** [comment]
build again

**Comment by red-avtovo** [comment]
lgtm

**Pull request merged**
