### PR TITLE
Revert slow sync and update based on team size + copy change 

### PR DESCRIPTION
**Pull request by BradleyWire**
## What's new in this PR?

Revert slow sync and update based on team size: https://wearezeta.atlassian.net/browse/AN-6842
Copy change: https://wearezeta.atlassian.net/browse/AN-6844

### Issues

After a in-depth discussion with Backend, it became clear that the current issues with the search are not fixable in a matter of days.

The issue is that you can not find people in your team at all if there are enough privte users matching the same query. For example, if you look for "Marco", you will not find Marco in your team but instead the first 100 (or whatever the threshold is) "Marco" private users. The search results will be truncated there, and you will never find your team mate. The private user have "pushed out" your team mates.

This is an issue only for backends that have consumers (i.e. our cloud version). On an on-prem backend, all results will be from your team anyway because there are no consumer. So if you get 100 Marco, it can only be because you have 100 Marco in your team, which is the desired result.

This is fixable on the backend, but it will take weeks, waaaay longer than expected. We need to come up with plan B.

### Solutions

We previously removed the behavior from clients to fetch the entire team. However clients were already successfully fetching teams up to 1,500, so they can handle it.

If we implement fetching the entire team on the client, then they will be able to perform local search for teams up to 1,500, and for teams that are larger than that, they will rely on backend results. Right now those results are brokens, but since we won't have teams larger than 1,500 on cloud, the user won't notice as they have everyone locally anyway. Only when the backend fixes the search, then the backend can remove the team limit on cloud too.

What does it mean for the client code?

Clients should re-add fetching the entire team on slow sync. If the response payload has a flag that indicates that there are more members than those returned ("has_more" is true), then we can ignore those - we are on a on-prem backend or even on the cloud after the search has been fixed. If the response payload contains the entire team ("has_more" is false), then store those results in the local DB and use them later for local search.

### CODE REVIEW

**Comment by BradleyWire** [comment]
build again

**Comment by makingthematrix** [comment]
Please rebase this on top of the main Large Team PR. I fixed conflicts between the main PR and develop, and these are the conflicts which show up here now.

**Comment by BradleyWire** [comment]
build again

**Comment by BradleyWire** [comment]
Build again

**Pull request closed without merging**
