### PR TITLE
chore: add user agent

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

the app user agent does not include any useful information 

### Solutions

add the user agent in the format of 

```
"Wire/${BuildConfig.VERSION_NAME}/${GitCommit()}/sdk:$sdkVersion/${System.getProperty("http.agent")}"

result:

Wire/v4.1.0(6347348)-beta/194c5773/sdk:33/Dalvik/2.1.0 (Linux; U; Android 13; Pixel 6 Build/TQ2A.230305.008.E1)
```

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1716/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1716/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6346807)(6346807)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6346807)(6346807)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
👨‍🍳🤌🏻

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1716/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.0(6347249)(6347249)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.0(6347249)(6347249)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Pull request merged**
