### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4525](https://10.10.124.134/job/AR-build-pipeline/4525/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9542204)(9542204)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9542204)(9542204)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4528](https://10.10.124.134/job/AR-build-pipeline/4528/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9543674)(9543674)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9543674)(9543674)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4542](https://10.10.124.134/job/AR-build-pipeline/4542/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9567491)(9567491)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9567491)(9567491)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4569](https://10.10.124.134/job/AR-build-pipeline/4569/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9570002)(9570002)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9570002)(9570002)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4598](https://10.10.124.134/job/AR-build-pipeline/4598/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9577223)(9577223)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9577223)(9577223)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4610](https://10.10.124.134/job/AR-build-pipeline/4610/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9579499)(9579499)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9579499)(9579499)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4627](https://10.10.124.134/job/AR-build-pipeline/4627/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9603557)(9603557)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9603557)(9603557)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4637](https://10.10.124.134/job/AR-build-pipeline/4637/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9604615)(9604615)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9604615)(9604615)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4643](https://10.10.124.134/job/AR-build-pipeline/4643/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9607543)(9607543)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9607543)(9607543)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4649](https://10.10.124.134/job/AR-build-pipeline/4649/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9610793)(9610793)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9610793)(9610793)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4654](https://10.10.124.134/job/AR-build-pipeline/4654/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9612201)(9612201)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9612201)(9612201)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4666](https://10.10.124.134/job/AR-build-pipeline/4666/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9613422)(9613422)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9613422)(9613422)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4681](https://10.10.124.134/job/AR-build-pipeline/4681/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9619473)(9619473)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9619473)(9619473)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4713](https://10.10.124.134/job/AR-build-pipeline/4713/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9638669)(9638669)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9638669)(9638669)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4724](https://10.10.124.134/job/AR-build-pipeline/4724/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9662341)(9662341)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9662341)(9662341)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4744](https://10.10.124.134/job/AR-build-pipeline/4744/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9673456)(9673456)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9673456)(9673456)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4767](https://10.10.124.134/job/AR-build-pipeline/4767/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9682193)(9682193)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9682193)(9682193)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4770](https://10.10.124.134/job/AR-build-pipeline/4770/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9683085)(9683085)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9683085)(9683085)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4785](https://10.10.124.134/job/AR-build-pipeline/4785/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9690150)(9690150)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9690150)(9690150)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4806](https://10.10.124.134/job/AR-build-pipeline/4806/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9722194)(9722194)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9722194)(9722194)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4817](https://10.10.124.134/job/AR-build-pipeline/4817/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9723603)(9723603)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9723603)(9723603)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4835](https://10.10.124.134/job/AR-build-pipeline/4835/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9731656)(9731656)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9731656)(9731656)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4851](https://10.10.124.134/job/AR-build-pipeline/4851/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9733328)(9733328)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9733328)(9733328)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4904](https://10.10.124.134/job/AR-build-pipeline/4904/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.8.0(9741831)(9741831)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.8.0(9741831)(9741831)-staging-compat.apk)

**Pull request closed without merging**
