### PR TITLE
Show timestamp on liked message and set message status

### PR DESCRIPTION
**Pull request by hakonbo**
#### APK
[Download build #7472](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7472/artifact/build/artifact/wire-dev-PR98-7472.apk)
[Download build #7473](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7473/artifact/build/artifact/wire-dev-PR98-7473.apk)
[Download build #7474](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7474/artifact/build/artifact/wire-dev-PR98-7474.apk)
[Download build #7476](http://192.168.10.18:8080/job/Pull%20Request%20Builder/7476/artifact/build/artifact/wire-dev-PR98-7476.apk)

### CODE REVIEW

**Comment by shumengye** [comment]
@hakonbo in `updateLikeButton()`, will the like button have red color also when it's liked by another user?

**Comment by hakonbo** [comment]
Like button is only red if _you_ like the message.

**Comment by hakonbo** [comment]
build again

**Comment by shumengye** [comment]
build again

**Pull request merged**
