### PR TITLE
chore(federation): Turn on federation for testing #FS-104

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/FS-104" title="FS-104" target="_blank">TaskFS-104</a>  [Android] [Clients] When checking if a user is in the same team as the user, consider the domain
  </td></table>
  <br />
 

## What's new in this PR?

Enabling the federation flag for testing purpose

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Failure
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/1/)

**Comment by AndroidBob** [comment]
Build Failure
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/2/)

**Comment by makingthematrix** [comment]
@ohassine : Do you want to merge this one? Is it safe to do it now?

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/3/)

**Comment by AndroidBob** [comment]
Build Failure
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/4/)

**Comment by ohassine** [comment]
build again

**Comment by AndroidBob** [comment]
Build Failure
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/5/)

**Comment by AndroidBob** [comment]
Build Success
ID:6
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/6/)

**Comment by AndroidBob** [comment]
Build Failure
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/7/)

**Comment by AndroidBob** [comment]
Build Failure
ID:8
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/8/)

**Comment by AndroidBob** [comment]
Build Failure
ID:9
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/9/)

**Comment by AndroidBob** [comment]
Build Failure
ID:10
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/10/)

**Comment by AndroidBob** [comment]
Build Failure
ID:11
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/11/)

**Comment by AndroidBob** [comment]
Build Failure
ID:12
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/12/)

**Comment by AndroidBob** [comment]
Build Failure
ID:13
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/13/)

**Comment by AndroidBob** [comment]
Build Failure
ID:14
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/14/)

**Comment by AndroidBob** [comment]
Build Failure
ID:15
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/15/)

**Comment by AndroidBob** [comment]
Build Success
ID:16
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/16/)

**Comment by AndroidBob** [comment]
Build Success
ID:17
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/17/)

**Comment by AndroidBob** [comment]
Build Success
ID:18
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/18/)

**Comment by AndroidBob** [comment]
Build Failure
ID:19
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/19/)

**Comment by AndroidBob** [comment]
Build Failure
ID:20
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/20/)

**Comment by AndroidBob** [comment]
Build Success
ID:21
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/21/)

**Comment by ohassine** [comment]
build again

**Comment by AndroidBob** [comment]
Build Success
ID:23
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3604/23/)

**Pull request closed without merging**
