### PR TITLE
feat: avatar border and message padding improvements [WPB-5059]

### PR DESCRIPTION
**Pull request by AndroidBob**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5059" title="WPB-5059" target="_blank">BugWPB-5059</a>  [Android] Paddings between messages from the same sender are off
  </td></table>
  <br />
 

Cherry pick from the original PR: 
- #2428

---- 

 ⚠️ Conflicts during cherry-pick:
kalium

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like 
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- added border to avatar
- improved paddings for messages
- increased size of system message icons

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

| Before | After |
| ----------- | ------------ |
|  before_1 | after_1   |
| before_2 | after_2  |

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1854](https://10.10.124.134/job/AR-build-pipeline/1854/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8109302)(8109302)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8109302)(8109302)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1942](https://10.10.124.134/job/AR-build-pipeline/1942/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1943](https://10.10.124.134/job/AR-build-pipeline/1943/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8176245)(8176245)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8176245)(8176245)-staging-compat.apk)

**Review by saleniuk — APPROVED** [review]
`shouldHaveSmallBottomPadding` is the cause of `IndexOutOfBoundsException` crashes, but I think we can merge that as it has also other improvements and the fix for that exception will be ready in a few minutes

**Pull request merged**
