### PR TITLE
Tracking events migrated to SE, HockeyApp migrated to UI

### PR DESCRIPTION
**Pull request by makingthematrix**
More info here: https://github.com/wireapp/wire-android-sync-engine/pull/274
#### APK
[Download build #9892](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9892/artifact/build/artifact/wire-dev-PR1272-9892.apk)
[Download build #9896](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9896/artifact/build/artifact/wire-dev-PR1272-9896.apk)
[Download build #9899](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9899/artifact/build/artifact/wire-dev-PR1272-9899.apk)
[Download build #9900](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9900/artifact/build/artifact/wire-dev-PR1272-9900.apk)

### CODE REVIEW

**Comment by JPonte** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by someoneEsle** [comment]
I tested several scenarios (opening team creation, registration, login, sending normal/ephemeral messages/pictures/audio messages, calling, opting out and back in) and it seems like tracking is still working. I did not test every single event, but everything I tested worked fine.

**Comment by someoneEsle** [comment]
See AN-5822

**Pull request merged**
