### PR TITLE
fix: ForegroundServiceDidNotStartInTimeException (AR-3285)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3285" title="AR-3285" target="_blank">BugAR-3285</a>  PlayStore crash : android.app.ForegroundServiceDidNotStartInTimeException
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The crash is reported in Play console but it's not clear which service is causing the issue

```
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException:
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2160)
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2131)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2396)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:240)
  at android.os.Looper.loop (Looper.java:351)
  at android.app.ActivityThread.main (ActivityThread.java:8381)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:584)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1013)
```

### Causes (Optional)

This exception happens when `startForeground()` is not called after about 10s.

### Solutions

Not sure if PersistentWebSocketService.kt is causing the issue as nothing helpful in logs.
But to be more safe I moved notification creation to `onCreate()`, Android system could invoke `onStartCommand() `after the required time.

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1651/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6225669)(6225669)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6225669)(6225669)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]
Great catch!

From reading how `startForeground()` needs to work it is also safe to have them both in `onCreate()` and `onStartCommand()` in case it is not properly called in any of them.

👌🏻

**Comment by ohassine** [comment]
> Great catch!
> 
> From reading how `startForeground()` needs to work it is also safe to have them both in `onCreate()` and `onStartCommand()` in case it is not properly called in any of them.
> 
> 👌🏻

But what will happen if it's called twice ?

**Review by borichellow — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1651/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6284862)(6284862)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6284862)(6284862)-staging-compat.apk)

**Pull request merged**
