### PR TITLE
fix: not marking messages as read (AR-2436)

### PR DESCRIPTION
**Pull request by vitorhugods**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2436" title="AR-2436" target="_blank">BugAR-2436</a>  Not marking messages as read
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some messages are not being marked as read by the app.

### Causes

When the user stops scrolling, we check the most recent message visible and compare its time with the `lastUnreadMessage`.
We need to check if the the latest visible message is more recent than the last unread. And if it is the case, we should update the conversation last read date.

Unfortunatelly this logic was originally implemented on the Composable itself, instead of being on the `ViewModel` or ideally in a `UseCase` inside Kalium.

And I ended-up changing the comparison yesterday with #979, introducing a bug.

### Solutions

Revert the comparison operator between `lastVisibleMessageDateTime` and `lastUnreadDateTime` back to `>=` from `>`.

### Testing

Not easily testable without further rewrite. This logic should not be in the Composable.

#### How to Test

Open a conversation.
Receive messages.
Scroll down to the latest message.
Going out the conversation, seeing the conversation list, it should have no unread messages.

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-985/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4426409)(4426409)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4426409)(4426409)-dev-release.apk)

**Review by trOnk12 — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-985/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4426883)(4426883)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4426883)(4426883)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-985/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4429362)(4429362)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4429362)(4429362)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-985/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4443426)(4443426)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4443426)(4443426)-dev-release.apk)

**Pull request merged**
