### PR TITLE
feat: Indicate user with valid E2EI certificate (WPB-3228)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-3228" title="WPB-3228" target="_blank">StoryWPB-3228</a>  [Android] 5.3.16 Indicate user with valid certificates
  </td></table>
  <br />
 

# What's new in this PR?

Show if user has valid E2EI Certificate in UserProfile and Conversations participants list 

### Dependencies (Optional)

[kalium PR](https://github.com/wireapp/kalium/pull/2335)

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

### CODE REVIEW

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2444](https://10.10.124.134/job/AR-build-pipeline/2444/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8531701)(8531701)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8531701)(8531701)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2453](https://10.10.124.134/job/AR-build-pipeline/2453/) **failed**.

**Review by mchenani — APPROVED** [review]
🛡️

**Comment by AndroidBob** [comment]
Build [2509](https://10.10.124.134/job/AR-build-pipeline/2509/) **failed**.

**Comment by AndroidBob** [comment]
Build [2510](https://10.10.124.134/job/AR-build-pipeline/2510/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8599795)(8599795)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8599795)(8599795)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2515](https://10.10.124.134/job/AR-build-pipeline/2515/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8600121)(8600121)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8600121)(8600121)-staging-compat.apk)

**Pull request merged**
