### PR TITLE
chore: handle snackbar using UIText for connection requests

### PR DESCRIPTION
**Pull request by trOnk12**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

- Cancelling request does not show the send request icon

This is a cherry pick , Original PR : https://github.com/wireapp/wire-android-reloaded/pull/1570/files

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1570/2/) **failed**.

**Review by gongracr — APPROVED** [review]
🥝

**Review by saleniuk — APPROVED** [review]
I think the title doesn't exactly reflect what was actually changed, this PR only updates the way snackbar messages are handled,  in the original PR the crucial part that actually fixed the issue mentioned in the topic, was this:
image

and fortunately I remembered that it was already merged to develop by Kubaz in the meantime 😄 

Please, next time attach the link to the original PR (https://github.com/wireapp/wire-android-reloaded/pull/1458), especially when both have slightly different titles 😅

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1570/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(6051926)(6051926)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(6051926)(6051926)-staging-compat.apk)

**Pull request merged**
