### PR TITLE
Web socket tracking and ping internal pref

### PR DESCRIPTION
**Pull request by wire-android**
Added events for websocket connection tracking.
Added PingIntervalPref to handle changes in SE: https://github.com/wireapp/wire-android-sync-engine/pull/70
See individual commit message for more info.
#### APK
[Download build #8555](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8555/artifact/build/artifact/wire-dev-PR618-8555.apk)

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Pull request merged**
