### PR TITLE
feat: E2EI certificat renew logic (WPB-3326)

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

- Added dialogs for: Remew E2EI certificate (with or without snooze), Error while creating/renewing E2EI certificate, Success after creating/renewing E2EI certificate.
- Extracted all the E2EICertificate-related dialogs into a separate file
- Updated `FeatureFlagNotificationViewModel` to handle a new implementation of `ObserveE2EIRequiredUseCase`

### Release with 

[kalium PR](https://github.com/wireapp/kalium/pull/1971)

### Attachments (Optional)

Screenshot 2023-08-11 at 12 39 17

Screenshot 2023-08-11 at 12 39 37

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [936](https://10.10.124.134/job/AR-build-pipeline/936/) **failed**.

**Comment by AndroidBob** [comment]
Build [937](https://10.10.124.134/job/AR-build-pipeline/937/) **failed**.

**Comment by AndroidBob** [comment]
Build [1011](https://10.10.124.134/job/AR-build-pipeline/1011/) **failed**.

**Comment by AndroidBob** [comment]
Build [1014](https://10.10.124.134/job/AR-build-pipeline/1014/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1023](https://10.10.124.134/job/AR-build-pipeline/1023/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7277961)(7277961)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7277961)(7277961)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1055](https://10.10.124.134/job/AR-build-pipeline/1055/) **failed**.

**Comment by AndroidBob** [comment]
Build [1058](https://10.10.124.134/job/AR-build-pipeline/1058/) **failed**.

**Comment by AndroidBob** [comment]
Build [1067](https://10.10.124.134/job/AR-build-pipeline/1067/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7303893)(7303893)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7303893)(7303893)-staging-compat.apk)

**Pull request merged**
