### PR TITLE
Enable video calling on 1:1 team conversations

### PR DESCRIPTION
**Pull request by deanrobertcook**
#### APK
[Download build #8991](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8991/artifact/build/artifact/wire-dev-PR918-8991.apk)
[Download build #8994](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8994/artifact/build/artifact/wire-dev-PR918-8994.apk)
[Download build #8995](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8995/artifact/build/artifact/wire-dev-PR918-8995.apk)
[Download build #8996](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8996/artifact/build/artifact/wire-dev-PR918-8996.apk)
[Download build #9001](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9001/artifact/build/artifact/wire-dev-PR918-9001.apk)

### CODE REVIEW

**Comment by deanrobertcook** [comment]
build again

**Comment by deanrobertcook** [comment]
build again

**Comment by mykola-mokhnach** [comment]
The video overlay always shows the label about the other user turned off his video while making video call in team 1:1 conversation and the other side is webapp chrome. Although the video is properly shown on both sides.

**Comment by mykola-mokhnach** [comment]
Please merge

**Pull request merged**
