### PR TITLE
fix: update view model state race condition [AR-3300]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3300" title="AR-3300" target="_blank">BugAR-3300</a>  PlayTest 12.04 - Account details screen is sometimes empty
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

RC: https://github.com/wireapp/wire-android-reloaded/pull/1680

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1696/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1696/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1696/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6305577)(6305577)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6305577)(6305577)-staging-compat.apk)

**Comment by saleniuk** [comment]
image

And I think these changes are already merged to develop, right? 
https://github.com/wireapp/wire-android-reloaded/pull/1681

What is the purpose of this PR then? 😄

**Pull request closed without merging**
