### PR TITLE
chore: update dependencies before code freeze

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Updating libraries versions, taken from dependabot log, before code freeze.
Also removes spotless, since was never used.

### Needs release with

- https://github.com/wireapp/kalium/pull/2715

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4412](https://10.10.124.134/job/AR-build-pipeline/4412/) **failed**.

**Comment by AndroidBob** [comment]
Build [4413](https://10.10.124.134/job/AR-build-pipeline/4413/) **failed**.

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4420](https://10.10.124.134/job/AR-build-pipeline/4420/) **failed**.

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4428](https://10.10.124.134/job/AR-build-pipeline/4428/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9499677)(9499677)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9499677)(9499677)-staging-compat.apk)

**Pull request merged**
