### PR TITLE
fix: visual bugs in account switching UI

### PR DESCRIPTION
**Pull request by MohamadJaara**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

visual issues related to 

1. the `YOUR OTHER ACCOUNTS` header have wrong color
2. @ is added before the team name 

### Solutions

1. use `FolderHeader` for the YOUR OTHER ACCOUNTS`  header
2. Modify `HighlightSubtitle` composable to take suffix parameter instead of hard codded @ suffix

----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-943/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4358633)(4358633)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4358633)(4358633)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-943/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4358761)(4358761)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4358761)(4358761)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-943/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4358928)(4358928)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4358928)(4358928)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-943/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4359383)(4359383)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4359383)(4359383)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-943/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4374041)(4374041)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4374041)(4374041)-dev-release.apk)

**Pull request merged**
