### PR TITLE
[DO NOT MERGE] Bump AVS to 3.3.7

### PR DESCRIPTION
**Pull request by jspittka**
#### APK
[Download build #8571](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8571/artifact/build/artifact/wire-dev-PR683-8571.apk)
[Download build #8573](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8573/artifact/build/artifact/wire-dev-PR683-8573.apk)
[Download build #8574](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8574/artifact/build/artifact/wire-dev-PR683-8574.apk)
[Download build #8592](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8592/artifact/build/artifact/wire-dev-PR683-8592.apk)

### CODE REVIEW

**Comment by jspittka** [comment]
build again

**Comment by wmengli** [comment]
No incoming call overlay when screen is locked
https://wearezeta.atlassian.net/browse/AN-5077

**Comment by jspittka** [comment]
Meng, Bjoern, and I just decided to NOT merge this for the upcoming Android release but wait until the SDP renegotiation functionality has been properly tested with Webapp. Also, it leaves time to propery integrate the roaming functionality.

**Comment by deanrobertcook** [comment]
Closing as we now also have: 
https://github.com/wireapp/wire-android/pull/713

**Pull request closed without merging**
