### PR TITLE
[AN-5841] Remove custom InputConnection

### PR DESCRIPTION
**Pull request by JPonte**
The custom InputConnection was incorrectly deleting text and was unused
#### APK
[Download build #10120](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10120/artifact/build/artifact/wire-dev-PR1382-10120.apk)
[Download build #10121](http://192.168.10.18:8080/job/Pull%20Request%20Builder/10121/artifact/build/artifact/wire-dev-PR1382-10121.apk)

### CODE REVIEW

**Comment by JPonte** [comment]
build again

**Comment by someoneEsle** [comment]
build again

**Comment by JPonte** [comment]
build again

**Comment by someoneEsle** [comment]
Fixes https://github.com/wireapp/wire-android/issues/1328

**Pull request merged**
