### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [487](https://10.10.124.134/job/AR-build-pipeline/487/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7485075)(7485075)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7485075)(7485075)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [522](https://10.10.124.134/job/AR-build-pipeline/522/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7487653)(7487653)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7487653)(7487653)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [531](https://10.10.124.134/job/AR-build-pipeline/531/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7488297)(7488297)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7488297)(7488297)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [555](https://10.10.124.134/job/AR-build-pipeline/555/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7493803)(7493803)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7493803)(7493803)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [563](https://10.10.124.134/job/AR-build-pipeline/563/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7494372)(7494372)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7494372)(7494372)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [568](https://10.10.124.134/job/AR-build-pipeline/568/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7494756)(7494756)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7494756)(7494756)-staging-compat.apk)

**Pull request merged**
