### PR TITLE
feat: handle legal hold system messages [WPB-4779]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-4779" title="WPB-4779" target="_blank">StoryWPB-4779</a>  [Android] System messages for conversations on legal hold
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

- updated creating strings with styled parameters
- updated legal hold indicator
- created UI and implemented handling of legal hold system messages

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/2291

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Enable or disable legal hold for a team member to see system messages.

### Attachments (Optional)

self_legal_hold

https://github.com/wireapp/wire-android/assets/30429749/e92edf00-2aa6-47d0-9338-908c655460d6

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2184](https://10.10.124.134/job/AR-build-pipeline/2184/) **failed**.

**Comment by AndroidBob** [comment]
Build [2186](https://10.10.124.134/job/AR-build-pipeline/2186/) **failed**.

**Comment by AndroidBob** [comment]
Build [2187](https://10.10.124.134/job/AR-build-pipeline/2187/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8297275)(8297275)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8297275)(8297275)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2225](https://10.10.124.134/job/AR-build-pipeline/2225/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8332954)(8332954)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8332954)(8332954)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2233](https://10.10.124.134/job/AR-build-pipeline/2233/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8333875)(8333875)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8333875)(8333875)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2235](https://10.10.124.134/job/AR-build-pipeline/2235/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8334742)(8334742)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8334742)(8334742)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
👍

**Comment by AndroidBob** [comment]
Build [2239](https://10.10.124.134/job/AR-build-pipeline/2239/) **failed**.

**Comment by AndroidBob** [comment]
Build [2244](https://10.10.124.134/job/AR-build-pipeline/2244/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8341047)(8341047)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8341047)(8341047)-staging-compat.apk)

**Pull request merged**
