### PR TITLE
Improve convs performance

### PR DESCRIPTION
**Pull request by wire-android**
This improves conversation list scrolling performance and account switch at the same time.
Main goal is to avoid DB operations on every list item load/update, this rule should be followed for every list, even when operations are run in background it still is very expensive. Everything should be cached and loaded in batch, or precomputed and stored. Ideally conversation list item would only display informations stored in `ConversationData`.
Sometimes it's not exactly clear which operation will cause DB access, most notable things here were: - members list loading, this executes select query, even though members storage is cached, search queries always go to db in SE
- MessagesStorage access, this storage is optimised for access to limited number of conversations at a time. It preloads messages index for whole conversation, thus it can not cache many conversations at the same time, so scrolling convs list would overflow this cache and force it to load all messages every time
For specific changes see individual commits.

There are still several possible improvements in conversation row, but this PR addresses the main performance issues.

This requires SE update from this PR: https://github.com/wireapp/wire-android-sync-engine/pull/225
#### APK
[Download build #9423](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9423/artifact/build/artifact/wire-dev-PR1089-9423.apk)
[Download build #9428](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9428/artifact/build/artifact/wire-dev-PR1089-9428.apk)
[Download build #9436](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9436/artifact/build/artifact/wire-dev-PR1089-9436.apk)
[Download build #9438](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9438/artifact/build/artifact/wire-dev-PR1089-9438.apk)
[Download build #9441](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9441/artifact/build/artifact/wire-dev-PR1089-9441.apk)
[Download build #9443](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9443/artifact/build/artifact/wire-dev-PR1089-9443.apk)
[Download build #9446](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9446/artifact/build/artifact/wire-dev-PR1089-9446.apk)
[Download build #9447](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9447/artifact/build/artifact/wire-dev-PR1089-9447.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
Subtitles in conversation list do not show pings, missed calls, etc. They only show "X new message(s)"

**Comment by wire-android** [comment]
There is an error in SE part of this change.
Please retest with this change: https://github.com/wireapp/wire-android-sync-engine/pull/238

**Comment by deanrobertcook** [comment]
build again

**Comment by JPonte** [comment]
build again

**Pull request merged**
