### PR TITLE
Wrong Alert dialog title in camera permission

### PR DESCRIPTION
**Pull request by Paulavelandiar**
### Issues
The alert dialog for the camera permission has "Microphone permission" as title, it is changed.

### Causes
The title was repeated for the microphone permission and it was not changed

### Solutions
Change the title

### CODE REVIEW

**Comment by AndroidBob** [comment]
Can one of the admins verify this patch?

**Comment by Paulavelandiar** [comment]
> Can one of the admins verify this patch?

It happens when you take away all the permissions and try to make a videocall, if you want to verify it I have a photo of the situation
Permisos videollamadas (2)

**Comment by makingthematrix** [comment]
@Paulavelandiar : This PR tries to merge the whole master branch to develop. I'm pretty sure this is not what you want :) If the only problem here is the translation, you can find us at the Crowdin platform where we work on our translations (and your help is very welcome): https://crowdin.com/project/wire-android

And if it's something in the codebase, please clone the current `develop` branch and create a PR from there.

**Comment by android10** [comment]
@Paulavelandiar there might be 2 visible problems related to the size of your change-set:

 - First you did not clone the wire repo and you are not working on your own copied version of the repo.
 - Second it could be that your cloned version of the repo is out of date and that is why the difference.

Please verify those 2 things to reduce the size of the PR, especially for only one translation.

Thank you very much :smiley:

**Pull request closed without merging**
