### PR TITLE
chore: increase VS-NFD banner visibility (AR-2610)

### PR DESCRIPTION
**Pull request by alexandreferris**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2610" title="AR-2610" target="_blank">StoryAR-2610</a>  Increase visibility on VS-NFD banner
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

VS-NFD banner needed visibility increase.

### Solutions

Increase visibility on VS-NDF banners by changing its color and properly applying them on Light and Dark Mode.

#### How to Test

Verify this screens for the banner on Light/Dark Mode:
- Conversation
- Other user Profile (Connected)
- Other user Profile (Not Connected)
- Incoming Call
- Outgoing Call

### Attachments (Optional)

| Light Mode | Dark Mode |
| ----------- | ------------ |
| connected  | dark_connected  |
| not_connected  | dark_not_connected  |
| conversation  | dark_conversation  |
| incoming_call  |  dark_incoming_call |
| outgoing_call  | dark_outgoing_call  |
| conversation_unclassified  |  dark_conversation_unclassified |

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1549/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5990785)(5990785)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5990785)(5990785)-staging-compat.apk)

**Comment by typfel** [comment]
Have you also updated the "not classified" banner to be red? There's no screenshot of it in the PR description?

**Comment by alexandreferris** [comment]
> Have you also updated the "not classified" banner to be red? There's no screenshot of it in the PR description?

Yes I did, only after all the screenshots I remembered about the unclassified screenshots 😓 
I will update the description in a bit.

**Review by typfel — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]
✨

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1549/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5999342)(5999342)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5999342)(5999342)-staging-compat.apk)

**Pull request merged**
