### PR TITLE
chore: hide delete and share logs buttons

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

The app is crashing when the user clicks on delete logs while logging is disabled.

`com.wire.android.util.LogFileWriter.clearActiveLoggingFileContent
java.io.FileNotFoundException`

### Causes (Optional)

We are trying to delete something that is not yet created.

### Solutions

Hide Delete logs and share logs options when logging is off.

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Using a prod version, go to setting  --> Debug settings
You should not see those two options. if Enable logging is diabled

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1468/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.1(5765659)(5765659)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.1(5765659)(5765659)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Review by MohamadJaara — DISMISSED** [review]
no need to disabled the button if logging is not enabled 
the issue is fixed here
https://github.com/wireapp/wire-android-reloaded/pull/1465

**Review by alexandreferris — COMMENTED** [review]
Already been fixed by @MohamadJaara on https://github.com/wireapp/wire-android-reloaded/pull/1465

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1468/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.1(5765863)(5765863)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.1(5765863)(5765863)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1468/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.1(5767658)(5767658)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.1(5767658)(5767658)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1468/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.1(5793387)(5793387)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.1(5793387)(5793387)-staging-compat.apk)

**Pull request merged**
