### PR TITLE
fix: [RC] Open conversation on notification tap (AR-2999)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2999" title="AR-2999" target="_blank">BugAR-2999</a>  Tapping on notification directs user to conversation list screen
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

Tap on notification opens Conversation list, should open Conversation 

### Causes (Optional)

1. After adding notification for multiple accounts: deeplink that is used on notification tap was changed (upended by `userId`) but Deeplink in navigation was not updated 
2. when the app is running deeplink handling became `suspend` and launched in a new coroutine. So when the app checks deeplink handling result it's not updated yet.

### Solutions

1. update Conversation screen deeplink scheme 
2. run deeplink handling in the same coroutine

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1419/2/) **failed**.

**Review by alexandreferris — APPROVED** [review]
Great work👌🏻 

Strangely enough depending on some emulator versions it was working before the fix (could be tested from develop/develop). But as I had to remove and recreate all my devices I couldn't tell which one now :/

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1419/3/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1419/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.0(5646325)(5646325)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.0(5646325)(5646325)-staging-compat.apk)

**Pull request merged**
