### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [4224](https://10.10.124.134/job/AR-build-pipeline/4224/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9428887)(9428887)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9428887)(9428887)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4235](https://10.10.124.134/job/AR-build-pipeline/4235/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9430099)(9430099)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9430099)(9430099)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4247](https://10.10.124.134/job/AR-build-pipeline/4247/) **failed**.

**Comment by AndroidBob** [comment]
Build [4275](https://10.10.124.134/job/AR-build-pipeline/4275/) **failed**.

**Comment by AndroidBob** [comment]
Build [4276](https://10.10.124.134/job/AR-build-pipeline/4276/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9439307)(9439307)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9439307)(9439307)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4285](https://10.10.124.134/job/AR-build-pipeline/4285/) **failed**.

**Comment by AndroidBob** [comment]
Build [4290](https://10.10.124.134/job/AR-build-pipeline/4290/) **failed**.

**Comment by AndroidBob** [comment]
Build [4296](https://10.10.124.134/job/AR-build-pipeline/4296/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9446798)(9446798)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9446798)(9446798)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4306](https://10.10.124.134/job/AR-build-pipeline/4306/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9447755)(9447755)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9447755)(9447755)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4321](https://10.10.124.134/job/AR-build-pipeline/4321/) **failed**.

**Comment by AndroidBob** [comment]
Build [4331](https://10.10.124.134/job/AR-build-pipeline/4331/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9454563)(9454563)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9454563)(9454563)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4344](https://10.10.124.134/job/AR-build-pipeline/4344/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9455945)(9455945)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9455945)(9455945)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4371](https://10.10.124.134/job/AR-build-pipeline/4371/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9482372)(9482372)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9482372)(9482372)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4374](https://10.10.124.134/job/AR-build-pipeline/4374/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9482848)(9482848)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9482848)(9482848)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4396](https://10.10.124.134/job/AR-build-pipeline/4396/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9489975)(9489975)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9489975)(9489975)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4421](https://10.10.124.134/job/AR-build-pipeline/4421/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9498705)(9498705)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9498705)(9498705)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4432](https://10.10.124.134/job/AR-build-pipeline/4432/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9500258)(9500258)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9500258)(9500258)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4439](https://10.10.124.134/job/AR-build-pipeline/4439/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9506460)(9506460)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9506460)(9506460)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [4457](https://10.10.124.134/job/AR-build-pipeline/4457/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9507728)(9507728)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9507728)(9507728)-staging-compat.apk)

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [4463](https://10.10.124.134/job/AR-build-pipeline/4463/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9508892)(9508892)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9508892)(9508892)-staging-compat.apk)

**Pull request merged**
