### PR TITLE
fix: blinking placeholder avatar on profile screen [WPB-3917]

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When opening any profile screen, a placeholder image appears for a short amount of time before the proper avatar is loaded, even if the image is already cached.

### Solutions

Provide a small delay of 200ms before showing the placeholder when loading proper avatar which is enough to fetch data from database and get the cached image, so it doesn't need to show the placeholder, only when the image is not already cached and needs to be downloaded, but even then it looks better together with the crossfade animation and new transition animations between screens.

#### How to Test

Open any profile screen.

### Attachments (Optional)

These before/after videos are recorded with disabled transition animations to better see how exactly it looks.

| Before | After |
| ----------- | ------------ |
|<video src="https://github.com/wireapp/wire-android-reloaded/assets/30429749/ec123218-79cc-4f69-a9d7-c067bb357c7f">|<video src="https://github.com/wireapp/wire-android-reloaded/assets/30429749/fd18cfc2-9d9b-4e54-8a46-bcc7c9114eeb">|

| After with transitions |
| ----------- |
| <video src="https://github.com/wireapp/wire-android-reloaded/assets/30429749/74b6df41-b8e2-43bd-a08d-d5e8925c98b6"> |

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [602](https://10.10.124.134/job/AR-build-pipeline/602/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7504585)(7504585)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7504585)(7504585)-staging-compat.apk)

**Review by vitorhugods — APPROVED** [review]
👨🏼‍🍳🤌🏻

**Review by alexandreferris — APPROVED** [review]

**Comment by ohassine** [comment]
Should we merge it into RC ?

**Comment by saleniuk** [comment]
> Should we merge it into RC ?

@ohassine do we currently have any restrictions on what fixes should be added to RC? 🤔 
It's not a new feature and not any breaking change so I don't see any reason why not 😄

**Comment by ohassine** [comment]
> > Should we merge it into RC ?
> 
> @ohassine do we currently have any restrictions on what fixes should be added to RC? 🤔 
> It's not a new feature and not any breaking change so I don't see any reason why not 😄 

AFAIK, only flagged issues should go into RC

**Comment by saleniuk** [comment]
> > > Should we merge it into RC ?
> > 
> > 
> > @ohassine do we currently have any restrictions on what fixes should be added to RC? 🤔
> > It's not a new feature and not any breaking change so I don't see any reason why not 😄
> 
> AFAIK, only flagged issues should go into RC

Currently we have only one flagged bug in our whole backlog so I don't think this rule applies. We were not supposed to merge any new features. 🤔

**Comment by AndroidBob** [comment]
Build [629](https://10.10.124.134/job/AR-build-pipeline/629/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7513478)(7513478)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7513478)(7513478)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [645](https://10.10.124.134/job/AR-build-pipeline/645/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7519273)(7519273)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7519273)(7519273)-staging-compat.apk)

**Pull request merged**
