### PR TITLE
chore: make previews public [ACOL-69]

### PR DESCRIPTION
**Pull request by Garzas**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/ACOL-69" title="ACOL-69" target="_blank">TopicACOL-69</a>  Writing Previews for composables, naming convention
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

According to https://wearezeta.atlassian.net/wiki/spaces/AR/pages/122520039/Code+Style+Guideline#Preview changed all composable preview functions to public and renamed them.

### Issues

Preview composable functions marked as private cannot be accessed by generator for automated snapshot test so we need to make them public

### Causes (Optional)

In future we will be able to easily generate snapshot test for each Composable Preview

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1322/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5456148)(5456148)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5456148)(5456148)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1322/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5456379)(5456379)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5456379)(5456379)-dev-compat.apk)

**Review by gongracr — APPROVED** [review]
Well done! 🧹 💪

**Review by saleniuk — APPROVED** [review]
You said that maybe we should also unify the order of `@Composable` `@Preview`, so does it mean that it's not required? 😄

**Comment by Garzas** [comment]
> You said that maybe we should also unify the order of `@Composable` `@Preview`, so does it mean that it's not required? 😄

Maybe I missed something 😓

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1322/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5465509)(5465509)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5465509)(5465509)-dev-compat.apk)

**Pull request merged**
