### PR TITLE
feat: add Russian string translation

### PR DESCRIPTION
**Pull request by Alex0z**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Russian translation added

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1643/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6182125)(6182125)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6182125)(6182125)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1643/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.1.1(6183015)(6183015)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.1.1(6183015)(6183015)-staging-compat.apk)

**Comment by yamilmedina** [comment]
Thanks @Alex0z for taking the initiative 🤝  We have updated our main [README](https://github.com/wireapp/wire-android-reloaded#contributing) regarding how to contribute to translations to the app.

**Comment by Alex0z** [comment]
Thanks @yamilmedina for respecting my work, I think this strings could be just merged if somebody will to do this.

**Pull request closed without merging**
