### PR TITLE
fix(dev): handle role edit option for federated users (AR-3347)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3347" title="AR-3347" target="_blank">BugAR-3347</a>  Federation - It's possible to make a user from another backend admin in a group conversation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We can edit the role of the user, even if there is no possible for them to execute operations as their new role.

### Causes (Optional)

Failing admin operations for users on different domains

### Solutions

Check if the user is a member of the same domain, and only then, the user admin can elevate/change the role of the target user.

### Attachments

https://user-images.githubusercontent.com/5806454/234564259-718da3dd-c67e-4314-9670-feb54b400ef5.mov

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

Context: Log in a federated environment, have a group conversation with users from other backends.
Expected: Me as an admin I cannot edit the role of user if is on a different domain (aka, federated)

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1726/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6354586)(6354586)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6354586)(6354586)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1726/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6355258)(6355258)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6355258)(6355258)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]
LGTM 👌

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1726/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6363493)(6363493)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6363493)(6363493)-staging-compat.apk)

**Pull request merged**
