### PR TITLE
fix: show proper empty screen when no contacts [WPB-250]

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When user does not have any contacts, he/she sees an empty screen when creating new conversation and can easily get confused because of that.

### Solutions

Add proper empty screen according to the design documentation and fix returning `EmptyResult` when there are no contacts.

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Log in to a personal account which does not yet have any contacts.

### Attachments (Optional)

| Before | After&nbsp;&nbsp;&nbsp;  |
| ----------- | ------------ |
| empty_contacts_list_before | empty_contacts_list_after |

----

#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by alexandreferris — APPROVED** [review]

**Review by MohamadJaara — APPROVED** [review]

**Review by yamilmedina — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [426](https://10.10.124.134/job/AR-build-pipeline/426/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7444148)(7444148)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7444148)(7444148)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [442](https://10.10.124.134/job/AR-build-pipeline/442/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7451143)(7451143)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7451143)(7451143)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [484](https://10.10.124.134/job/AR-build-pipeline/484/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7484922)(7484922)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7484922)(7484922)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [498](https://10.10.124.134/job/AR-build-pipeline/498/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7486074)(7486074)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7486074)(7486074)-staging-compat.apk)

**Pull request merged**
