### PR TITLE
chore: include commit hash id into the build

### PR DESCRIPTION
**Pull request by yamilmedina**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We don't have a “error proof” way to check for a version released and correlate fixes to a particular commit in the code repository

### Causes (Optional)

It is more difficult to check if a bug/crash is solved or not, by just looking at the version number or version name.

### Solutions

Get the git short Hash ID, and include it in the build, so when we look at logs - files or datadog- we can correlate fixes to releases easier.

### Attachments (Optional)

Screenshot 2022-12-20 at 19 28 59

Screenshot 2022-12-20 at 19 13 18

Screenshot 2022-12-20 at 19 12 43

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1252/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5259420)(5259420)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5259420)(5259420)-dev-compat.apk)

**Review by vitorhugods — APPROVED** [review]
👨‍🍳🤌 noice

One nice step to speed up the debugging and log analysis, and also one step towards guiding users towards reproducible builds, linking them to GitHub, etc

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1252/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5260225)(5260225)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5260225)(5260225)-dev-compat.apk)

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1252/7/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5260950)(5260950)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5260950)(5260950)-dev-compat.apk)

**Pull request merged**
