### PR TITLE
feat: horizontal pager solution to paddings and scroll (AR-2949)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2949" title="AR-2949" target="_blank">SubtaskAR-2949</a>  Implement imported media horizontal pager and conversation selection
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Horizontal pager scroll had padding issues when combining generic assets and image assets.

### Causes (Optional)

The horizontal scroll had a glitch when doing swipe

### Solutions

- Add correct padding to content not container for generic assets
- Add `LocalOverscrollConfiguration` behavior to horizontal pager

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1340/1/) **failed**.

**Review by alexandreferris — APPROVED** [review]
👌🏻

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1340/3/) **failed**.

**Review by gongracr — APPROVED** [review]
I was not really aware of the use of `CompositionLocalProvider` and `LocalOverscrollConfiguration` but it seems it makes the trick 💪  Thanks for the help! 🎖️

**Pull request merged**
