### PR TITLE
feat: Notifications: Fix notifications sounds (SQCORE-1182)

### PR DESCRIPTION
**Pull request by makingthematrix**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQCORE-1182" title="SQCORE-1182" target="_blank">SubtaskSQCORE-1182</a>  [Android] Fix notifications sounds
  </td></table>
  <br />
 

https://wearezeta.atlassian.net/browse/SQCORE-1182

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow
  - [x] contains a reference JIRA issue number
  - [x] answers the question: _If merged, this PR will: ..._

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

For a long time now an incoming notification doesn’t produce a sound. The paths to sound files are wrong and there are errors about it in the logs. Try fixing it but don’t spend much time on this.

### Solutions

The functionality was simplified. Now we will have only four notification channels: incoming calls, outgoing calls, messages, and pings. There will be no differentiation based on user accounts - it gives little value and as the current implementation shows, it introduces a lot of complexity and we were never able to handle it well.

### Testing

Manually 

#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:1
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/1/)

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/4/)

**Comment by AndroidBob** [comment]
Build Success
ID:5
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/5/)

**Review by ohassine — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build Success
ID:7
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3623/7/)

**Pull request merged**
