### PR TITLE
chore: add google services

### PR DESCRIPTION
**Pull request by MohammedMokresh**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

add google services to the code base 

#### How to Test

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-561/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3271233)(3271233)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3271233)(3271233)-dev-release.apk)

**Comment by ohassine** [comment]
I think it would be better if we get rid of google-services.json file and initialise Firebase manually ?...that will be useful later as we don't need Firebase for f-droid
Also the google-service file is containing a lot of informations that we may not need them, for FCM we only need FIREBASE_APP_ID and FIREBASE_PUSH_SENDER_ID I think

**Comment by ohassine** [comment]
I think it would be better if we get rid of google-services.json file and initialise Firebase manually ?...that will be useful later as we don't need Firebase for f-droid
Also the google-service file is containing a lot of informations that we may not need them, for FCM we only need FIREBASE_APP_ID and FIREBASE_PUSH_SENDER_ID I think

**Review by yamilmedina — APPROVED** [review]
🎸  💯

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-561/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(3277563)(3277563)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(3277563)(3277563)-dev-release.apk)

**Pull request merged**
