### PR TITLE
feat(calling): end call on member leave or conversation deleted (WPB-2955)

### PR DESCRIPTION
**Pull request by ohassine**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-2955" title="WPB-2955" target="_blank">BugWPB-2955</a>  [android] Call not ended, when being removed from an conversation
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Call not ended, when being removed from a conversation
 
### Causes (Optional)

Not implemented 

### Solutions

I used `EndCallOnConversationChangeUseCase`  in `GlobalObserversManager` to keep observing active call and it's conversation details in background and foreground.

The moment the user is no longer part of that conversation, conversation is deleted or the user is deleted, the call will be terminated

### Dependencies (Optional)

Needs this PR
[feat(calling): create usecase for ending call on member leave or conversation delete (WPB-2955)
](https://github.com/wireapp/kalium/pull/1865)

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

- Be in a group call
- Remove you self from a different device or current device
--> Call should be ended

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_ 

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [244](https://10.10.124.134/job/AR-build-pipeline/244/) **failed**.

**Comment by AndroidBob** [comment]
Build [245](https://10.10.124.134/job/AR-build-pipeline/245/) **failed**.

**Review by yamilmedina — APPROVED** [review]
Great 🔥 
Also as Kalium, we need this fix in 4.2.1

**Review by tmspzz — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [247](https://10.10.124.134/job/AR-build-pipeline/247/) **failed**.

**Comment by AndroidBob** [comment]
Build [248](https://10.10.124.134/job/AR-build-pipeline/248/) **failed**.

**Comment by AndroidBob** [comment]
Build [249](https://10.10.124.134/job/AR-build-pipeline/249/) **failed**.

**Comment by AndroidBob** [comment]
Build [257](https://10.10.124.134/job/AR-build-pipeline/257/) **failed**.

**Comment by AndroidBob** [comment]
Build [258](https://10.10.124.134/job/AR-build-pipeline/258/) **failed**.

**Comment by AndroidBob** [comment]
Build [306](https://10.10.124.134/job/AR-build-pipeline/306/) **failed**.

**Comment by AndroidBob** [comment]
Build [319](https://10.10.124.134/job/AR-build-pipeline/319/) **failed**.

**Comment by AndroidBob** [comment]
Build [324](https://10.10.124.134/job/AR-build-pipeline/324/) **failed**.

**Comment by AndroidBob** [comment]
Build [342](https://10.10.124.134/job/AR-build-pipeline/342/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7012496)(7012496)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7012496)(7012496)-staging-compat.apk)

**Pull request merged**
