### PR TITLE
fix: missing messages v2 - AN-7154

### PR DESCRIPTION
**Pull request by marcoconti83**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AN-7154" title="AN-7154" target="_blank">BugAN-7154</a>  Android ::: Missing messages
  </td></table>
  <br />
 

# Problem 1: Overwriting events

The app receives events from the backend (such as incoming messages) either via `GET /notifications` or via websocket. Before this pull request, received events were saved in a database table (`PushNotificationEvents`). We will refer to this as **STEP A**. Events were first saved encrypted, for those that are actually encrypted (i.e. messages). The table had a `decrypted` column. All events were initially saved with `decrypted` set to false (whether they are messages and are actually encrypted, or are non-messages and contain no encrypted payload). This was done in the `PushNotificationEventsStorageImpl` class.

Events were then processed in the `PushService.process()` method:
- Encrypted events are loaded from the storage
- Events are decrypted: 
	- either we figure out that they do not contain any encrypted payload (i.e. they are not messages), then we just set the `decrypted` flag in the database row as true, 
	- or we need to decrypt them (i.e. they are events), and `EventDecrypter` will use Cryptobox/Proteus to decrypt them. After decrypting them, we will update the database row with the plaintext version (in the `plain` field) and the `decrypted` flag set to `true`. We will refer to this as **STEP B**.
- Then, all decrypted events are loaded from the database (this allow us to load events that were decrypted in a previous run but maybe not processed because the app crashed in the process). We will refer to this as **STEP C**.
- The loaded events are processed by the app (e.g. messages inserted in conversations, etc.), and then removed from the database

There is a race condition: if events are received again (for example, there is another `GET /notification` request running at the same time, which can happen if we receive multiple FCM pushes in a short time), the received events are saved in the database again as part of **STEP A**. If this happens **while** we are going through the individual messages in **STEP B** to decrypt and save them, it's possible that we already saved some events with `decrypted` set to true. However now **STEP A** will overwrite them, setting them back to `decrypted` set to false. 

When we get to **STEP C**, those events that were set back to `decrypted` `false`, even if previously decrypted, looks like they are still encrypted, and they will not be picked up for processing.

From this point on, those events are considered encrypted. Since Cryptobox will (by design, as a security feature) decrypt the same encrypted payload only once, and throw an error if we tried to decrypt it again, we are not able to decrypt those events any more. When we try to decrypt them, Cryptobox will return an error and in `PushService` we will simply delete those events from the storage. This means that those events are never decrypted again and are lost.

**In short**: the root cause of missing messages is a race condition on reading and writing the `PushNotificationEvents` table at the same time, overwriting previous values and turning already decrypted events back to encrypted.

The above explanation is illustrated in the following sequence diagram:

image

In this diagram, events 1 and 2 are decrypted but later overwritten to be encrypted again.

# Solution to problem 1

We first tried to remove the race condition by making sure that the operations are happening in sequence and inside transactions. 

We tried a couple of different approaches:
- when saving encrypted events, never overwrite existing rows (this did not work due to problem 2, see below)
- use DB transactions around the steps above (**STEP A, B, C**) (this did not work due to problem 2, see below)
- introduce an explicit `ReentrantLock` around those operations (this was later discarded for performance and reliability concerns)

In the end we decided to take a more robust approach based on immutability rather than synchronization.

We split the events table in two separate tables:
- incoming encrypted events are now stored in `EncryptedPushNotificationEvents`
- when the events are decrypted, they are saved to `DecryptedPushNotificationEvents` with the plaintext version, and removed from `EncryptedPushNotificationEvents`

This is done in `PushNotificationEventsStorageImpl`. 

With this approach, even if we write the encrypted events multiple times as result of receiving/fetching it multiple times, we will never overwrite an already decrypted event as those are stored in a separate table. Likewise, even if for some reason we overwrite a decrypted event, we can only overwrite it with a still decrypted version.

The rows in both table are now immutable - they will be added or deleted, but never changed (overwriting an encrypted event with the same event is an idempotent operation - the row content will not change).

# Problem 2: DB transactions with futures are not reliable

Before this pull request, in the code for `PushNotificationStorageImpl`, we used database transactions with the `storage.withTransaction()` method, which accepts a closure. The method essentially starts a transaction, executes the closure, then terminates the transaction.

E.g.:
```
storage.withTransaction { implicit db =>
      val curIndex = PushNotificationEventsDao.maxIndex()
      val nextIndex = if (curIndex == -1) 0 else curIndex+1
      returning(
        eventsToSave.zip(nextIndex.until(nextIndex+eventsToSave.length)).map {
          case ((id, event, transient), index) => PushNotificationEvent(id, index, event = event, transient = transient)
        }
      ) { insertAll }
    }.future
```

If the closure generates a `Future` though, the closure will likely end (and therefore terminate the transaction) before the future body is executed. In the above example, `insertAll`, which is a future, will likely be executed outside of the transaction started with `storage.withTransaction`.

In order to solve Problem 1, we need to introduce more tables. Those tables will have a similar problem with transactions and futures, as they also require transactions similar to the one shown above.

# Solution to problem 2

We tried to make sure that transactions are waiting for futures to be completed, but this approach has a few pitfalls and it's not straight forward if the threading model is not well defined.

We settled on removing the main reason for transactions, and disposing of transactions altogether. In the solution to problem 1 we already demonstrated that writing the same event multiple time is not going to be a problem, therefore we don't need transactions to avoid that.

The other reasons that transactions were used was to generate a unique index for a `PushNotificationEvents` row by taking the highest existing index in the table and increasing it. This is because we did not want to rely on any other property of the row as a "primary key" (note that "primary key" is misleading: the index was treated as a primary key in the code where the table was updated, but the table definition actually defined the push notification ID as the primary key). 

We removed this artificial incremental index and replaced it with a (composite) primary key: push notification ID (generated by the backend) and index of the event inside the push notification payload. A single push notification (which has an UUID-based ID, which are [practically guaranteed](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions) to be unique) might contain multiple events. The combination of UUID and index in the list of event is unique.

This allowed us to remove the need for database transactions.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build Success
ID:2
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3715/2/)

**Comment by AndroidBob** [comment]
Build Failure
ID:3
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3715/3/)

**Comment by AndroidBob** [comment]
Build Success
ID:4
URL:[Link to Buildjob](https://10.10.124.134/job/wire-android/job/PR-3715/4/)

**Review by vitorhugods — APPROVED** [review]
Awesome investigation job and fix! 🚀🚀

**Review by typfel — APPROVED** [review]
🚀

**Review by johnxnguyen — APPROVED** [review]

**Pull request merged**
