### PR TITLE
feat: Delete notification when message deleted (WPB-1669)

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

### Issues

When the sender edits/deletes a message, the notification on receiver side is not updated and displays the old message.

### Causes (Optional)

informing about message changes in notification was not implemented.

### Solutions

1. Update `kalium`
2. Update `MessageNotificationManager` to apply changes into an existed notifications, by getting displayed notifications, finding the specific message in it (by messageId), and applying changes. So if the message is not in the notification, or notification is not displayed - do nothing. 

Needs release with:

- https://github.com/wireapp/kalium/pull/1997

#### How to Test

- as userA send a message to userB
- receive a notification on userB
- as a userA edit a message

expected result: notification for userB is updated

- as userA send a message to userB
- receive a notification on userB
- as a userA delete a message "for everyone"

expected result: notification for userB is removed (Including the summary notification)

- as userA send a few message to userB
- receive a notifications on userB
- as a userA delete 1 message "for everyone"

expected result: notification for userB is updated - deleted message is not displayed.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1207](https://10.10.124.134/job/AR-build-pipeline/1207/) **failed**.

**Comment by AndroidBob** [comment]
Build [1211](https://10.10.124.134/job/AR-build-pipeline/1211/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7365679)(7365679)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7365679)(7365679)-staging-compat.apk)

**Review by Garzas — CHANGES_REQUESTED** [review]
As Codecov says, can we cover classes with tests?

**Comment by borichellow** [comment]
> As Codecov says, can we cover classes with tests?

basically most of new staff is in kalium, and it's tested there. 
On platform side it's just handling of new sealed class. 

I was thinking about tests for the `MessageNotificationManager`, but it requirs mocking `NotificationManager` for getting active notifications, which seems extra hard to do 😓

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1266](https://10.10.124.134/job/AR-build-pipeline/1266/) **failed**.

**Review by alexandreferris — APPROVED** [review]

**Pull request merged**
