### PR TITLE
feat: Display e2ei status of all devices

### PR DESCRIPTION
**Pull request by borichellow**
# What's new in this PR?

Display E2EI statuses of each device in: 

- OtherUserProfile screen
- MyDevices screen

### Solutions

just do it

### Attachments (Optional)

Screenshot 2024-01-16 at 14 19 51

Screenshot 2024-01-16 at 14 20 00

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2558](https://10.10.124.134/job/AR-build-pipeline/2558/) **failed**.

**Comment by AndroidBob** [comment]
Build [2563](https://10.10.124.134/job/AR-build-pipeline/2563/) **failed**.

**Comment by AndroidBob** [comment]
Build [2566](https://10.10.124.134/job/AR-build-pipeline/2566/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8642889)(8642889)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8642889)(8642889)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [2577](https://10.10.124.134/job/AR-build-pipeline/2577/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8643706)(8643706)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8643706)(8643706)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]
🔥

**Pull request merged**
