### PR TITLE
fix: debug screen adjustment (AR-3420)

### PR DESCRIPTION
**Pull request by trOnk12**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-3420" title="AR-3420" target="_blank">TaskAR-3420</a>  Debug settings page improvements
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

 - Adjust the debug settings according to the design decision 
 - Add another screen used only for internal debugging
 - Move debug information from menu to the debug screen

### Attachments (Optional)
image
image
image

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1792/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1792/4/) **failed**.

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1792/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6534711)(6534711)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6534711)(6534711)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]

**Review by MohamadJaara — APPROVED** [review]

**Review by saleniuk — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1792/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.2.0(6580435)(6580435)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.2.0(6580435)(6580435)-staging-compat.apk)

**Pull request merged**
