### PR TITLE
[AN-5692] [AN-5711] clears the cursor text with setText instead of getText.clear

### PR DESCRIPTION
**Pull request by makingthematrix**
#### APK
[Download build #9644](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9644/artifact/build/artifact/wire-dev-PR1201-9644.apk)
[Download build #9645](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9645/artifact/build/artifact/wire-dev-PR1201-9645.apk)
[Download build #9669](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9669/artifact/build/artifact/wire-dev-PR1201-9669.apk)
[Download build #9674](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9674/artifact/build/artifact/wire-dev-PR1201-9674.apk)
[Download build #9682](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9682/artifact/build/artifact/wire-dev-PR1201-9682.apk)
[Download build #9703](http://192.168.10.18:8080/job/Pull%20Request%20Builder/9703/artifact/build/artifact/wire-dev-PR1201-9703.apk)

### CODE REVIEW

**Comment by someoneEsle** [comment]
build again

**Comment by someoneEsle** [comment]
Not fixed on Galaxy S7

**Comment by makingthematrix** [comment]
OK. The code was changed a little bit more in order to prevent keyboard flickering, and to prevent the "Send" button from appearing if all the typed characters are whitespaces (the same behaviour as on iOS).
Tested on four different phones.

**Comment by someoneEsle** [comment]
Bug 1
Set timer to 5 seconds
Write spaces only
Tap hourglass again
Timer seems to be set on OFF instead of 5s

Bug 2
Type spaces only
The suggestion "TYPE A MESSAGE" should go away and not overlap with the cursor (same applies to "TIMED MESSAGE" when in timed mode)

**Pull request merged**
