### PR TITLE
feat: read only profiles lock for avatar and display name (AR-2186)

### PR DESCRIPTION
**Pull request by yamilmedina**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2186" title="AR-2186" target="_blank">TaskAR-2186</a>  [AR] Lock display name of SCIM users (1.6)
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In order to handle checks for read only profiles, namely, users that are provided.
In simple words, users not managed by wire, their profiles are readonly.

### Depends on

The Kalium PR is https://github.com/wireapp/kalium/pull/1540

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1515/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5865477)(5865477)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5865477)(5865477)-staging-compat.apk)

**Review by MohamadJaara — APPROVED** [review]
LGTM

**Review by ohassine — APPROVED** [review]
LGTM 👌

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1515/6/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5870834)(5870834)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5870834)(5870834)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1515/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5878903)(5878903)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5878903)(5878903)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1515/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv4.0.2(5879095)(5879095)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-vv4.0.2(5879095)(5879095)-staging-compat.apk)

**Pull request merged**
