### PR TITLE
chore: timeout call notifications observing on background (AR-2437)

### PR DESCRIPTION
**Pull request by vitorhugods**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2437" title="AR-2437" target="_blank">BugAR-2437</a>  Notifications stop when app is on background
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [X] contains a reference JIRA issue number like `SQPIT-764`
  - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

We're investigating an issue where `fetchAndShowCallNotificationsOnce` is hanging for minutes when receiving a push notification.

### Causes

Still unknown

### Solutions

1. Add more logs to that code area.
2. Add a timeout to `fetchAndShowCallNotificationsOnce`.
3. Update Kalium to add more logs to `GetIncomingCallsUseCase`, which is used by this function.
4. Move the `cancellable` check further up. So we check for cancellation on each emission of the `intervalFlow`, instead of only checking downstream, when emissions are less frequent.

### Dependencies

Needs releases with:

- https://github.com/wireapp/kalium/pull/947

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

 - [X] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1013/1/) **failed**.

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1013/2/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4483807)(4483807)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4483807)(4483807)-dev-release.apk)

**Review by ohassine — APPROVED** [review]
🚀

**Review by trOnk12 — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1013/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4487137)(4487137)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4487137)(4487137)-dev-release.apk)

**Pull request merged**
