### PR TITLE
chore: simplify passing arguments to scoped ViewModels

### PR DESCRIPTION
**Pull request by saleniuk**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Currently we need to pass arguments like key-value pairs into `Bundle` and then retrieve them manually from `SavedStateHandle` in the `ViewModel`, which is also not type-safe.

### Solutions

With the help from the [Bundlizer](https://github.com/AhmedMourad0/bundlizer) library, we can make a `Bundle` out of `kotlinx.serialization Serializable`, so we can create arguments data class for the specific scoped `ViewModel`, and using implemented custom `hiltViewModelScoped` just pass the instance of this arguments class, and then in the `ViewModel` retrieve it type-safely using extension function `SavedStateHandle.scopedArgs()`. There is also a `ScopedArgs` interface with the `key` argument, so building the key for the `hiltScopedViewModel` is moved to the arguments class, to make it even easier.

So it's like this:
- create arguments class:
```
@Serializable
data class ScopedViewModelArgs(val argument: String): ScopedArgs {
    override val key = argument
}
```
- inject scoped `ViewModel`:
```
viewModel: ScopedViewModel = hiltViewModelScoped(ScopedViewModelArgs(argument = "argument"))
```
- get arguments in the `ViewModel`:
```
val scopedArgs: ScopedViewModelArgs = savedStateHandle.scopedArgs()
```
<br />
<br />

For testing purposes, `ScopedArgsTestExtension` is added, which allows for mocking `scopedArgs` like:
`every { savedStateHandle.scopedArgs<CompositeMessageArgs>() } returns CompositeMessageArgs(MESSAGE_ID)`

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [758](https://10.10.124.134/job/AR-build-pipeline/758/) **failed**.

**Comment by AndroidBob** [comment]
Build [759](https://10.10.124.134/job/AR-build-pipeline/759/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7158448)(7158448)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7158448)(7158448)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]
Wow, nice improvement 👏 Can you just add documentation how to use app/src/main/kotlin/com/wire/android/di/ViewModelScoped.kt in composable and in view model? Also we can update documentation ADR https://wearezeta.atlassian.net/wiki/spaces/AR/pages/812449806/24.05.2023+Divide+big+view+models+to+smaller

**Comment by AndroidBob** [comment]
Build [814](https://10.10.124.134/job/AR-build-pipeline/814/) **failed**.

**Comment by AndroidBob** [comment]
Build [849](https://10.10.124.134/job/AR-build-pipeline/849/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7202313)(7202313)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7202313)(7202313)-staging-compat.apk)

**Review by borichellow — APPROVED** [review]
Really cool and useful staff!!!! 
But will we need it after navigation refactoring?

**Review by trOnk12 — APPROVED** [review]
Well done I would suggest to submit a PR or something to the official library

**Comment by AndroidBob** [comment]
Build [867](https://10.10.124.134/job/AR-build-pipeline/867/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.4.0(7208766)(7208766)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.4.0(7208766)(7208766)-staging-compat.apk)

**Pull request merged**
