### PR TITLE
chore: enable standard reactions [APB-826]

### PR DESCRIPTION
**Pull request by vitorhugods**
And remove hacky code from the UI layer now that Kalium handles it properly

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [X] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [X] contains a reference JIRA issue number like `SQPIT-764`
    - [X] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [X] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

When we came up with Reactions, some hacky code was added to keep compatibility between clients.
Now that Web and iOS are implementing reactions too, we can remove it.

### Solutions

| Visual Representation | Unicode Symbols           | Comment                                                                      |
|:---------------------:|:-------------------------:|:----------------------------------------------------------------------------:|
| `❤`                     | Single symbol: \u2764     | Expected by old Android and exchanged between clients during the “Likes” era |
| `❤️`                    | Two symbols: \u2764\uFE0F | Default used by Web, iOS and Android during the “Reactions” era              |

Now in Kalium, all heart reactions are stored as `❤️`. So this means we can remove all hacky code used to display the heart reactions.

When _sending_, we are also sending the `❤️` emoji.

### Testing

N/A

----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [295](https://10.10.124.134/job/AR-build-pipeline/295/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7003259)(7003259)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7003259)(7003259)-staging-compat.apk)

**Review by ohassine — APPROVED** [review]

**Review by Garzas — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [305](https://10.10.124.134/job/AR-build-pipeline/305/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7009513)(7009513)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7009513)(7009513)-staging-compat.apk)

**Comment by vitorhugods** [comment]
Signaling not to merge as merging this will cause weird interactions with the current iOS client.

We can wait a bit until it's closer to next release of the iOS app.

**Comment by AndroidBob** [comment]
Build [481](https://10.10.124.134/job/AR-build-pipeline/481/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.3.0(7072226)(7072226)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.3.0(7072226)(7072226)-staging-compat.apk)

**Pull request merged**
