### PR TITLE
chore: update localization strings via Crowdin

### PR DESCRIPTION
**Pull request by AndroidBob**
This PR pulls in the latest localization translations from Crowdin.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3383](https://10.10.124.134/job/AR-build-pipeline/3383/) **failed**.

**Comment by AndroidBob** [comment]
Build [3390](https://10.10.124.134/job/AR-build-pipeline/3390/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9023657)(9023657)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9023657)(9023657)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3407](https://10.10.124.134/job/AR-build-pipeline/3407/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9025033)(9025033)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9025033)(9025033)-staging-compat.apk)

**Comment by morty303** [comment]
anyone knows why fdroid release is 2 years old and get no update?

**Comment by AndroidBob** [comment]
Build [3452](https://10.10.124.134/job/AR-build-pipeline/3452/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9057643)(9057643)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9057643)(9057643)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3467](https://10.10.124.134/job/AR-build-pipeline/3467/) **failed**.

**Comment by AndroidBob** [comment]
Build [3504](https://10.10.124.134/job/AR-build-pipeline/3504/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9084400)(9084400)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9084400)(9084400)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3543](https://10.10.124.134/job/AR-build-pipeline/3543/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9126611)(9126611)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9126611)(9126611)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [3565](https://10.10.124.134/job/AR-build-pipeline/3565/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9129962)(9129962)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9129962)(9129962)-staging-compat.apk)

**Pull request closed without merging**
