### PR TITLE
[AN-4744] Fixed highlighting error

### PR DESCRIPTION
**Pull request by hakonbo**
#### APK
[Download build #8114](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8114/artifact/build/artifact/wire-dev-PR398-8114.apk)
[Download build #8116](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8116/artifact/build/artifact/wire-dev-PR398-8116.apk)

### CODE REVIEW

**Comment by hakonbo** [comment]
build again

**Comment by hakonbo** [comment]
build again

**Comment by vova-lohika** [comment]
Is it related to https://wearezeta.atlassian.net/browse/AN-4744?

**Comment by hakonbo** [comment]
@vova-lohika yes

**Pull request merged**
