### PR TITLE
refactor: unify and simplify conversation lists [WPB-9433]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-9433" title="WPB-9433" target="_blank">StoryWPB-9433</a>  [Android] Implement Pagination for Conversation Screen Data Retrieval
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Conversation list composables are overly complicated and have many leftovers after bottom tabs and multiple refactors, so in order to implement pagination, it's better to first make a cleanup.

### Solutions

- removed all legacy code related to bottom tabs
- simplified naming and code of conversation-list-related screens and removed complicated “routers” or “bridges”, now `ConversationsScreenContent` is a composable used to create screens with conversation lists
- removed unneeded `ConversationItemType` from `ConversationRouterState`, extracted it into dedicated file and renamed to `ConversationsDialogsState` as from now on it only contains conversation-list-related dialogs states
- combined `conversationSearchResult` and `foldersWithConversations` into single one as having two separate fields is not necessary and actually would complicate it even more when implementing pagination
- removed duplicated and unused code leftover from previous refactors and updated `ConversationListViewModel` to use `AssistedInject` and thanks to that reduced the number of functions and `LaunchedEffects` needed
- created interfaces for `ConversationListViewModel` and `ConversationCallListViewModel` and “_Preview_” versions of them to be able to create previews for screens that show conversation list and use `ConversationsScreenContent`
- added previews for conversation list composable, all conversations screen and archive screen
- extracted empty screens to dedicated files (search, archive and all conversations)
- changed parameter from `Activity` to `Context` for functions that return call intents, to be able to show previews (there is no `Activity` for composable previews)
- updated tests, refactored to have `Arrangement` classes

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution

#### How to Test

Open all conversations list or archive list and make sure everything works as it should.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by MohamadJaara — APPROVED** [review]

**Review by yamilmedina — COMMENTED** [review]
Looks good to me! Before adding the ✅ What about adding ADR? since we are refactoring and removing lots of code (👏 ) and unifying to new ones (🙌 )

**Comment by AndroidBob** [comment]
# New ADR(s) in this PR 📚:
# 5. Conversation list composables refactor

Date: 2024-10-01

## Status

Accepted

## Context

Conversation-list-related composables and screens (all conversations, archive) are overly 
complicated and have many leftovers after bottom tabs and multiple refactors, 
so in order to implement pagination, it's better to make a cleanup first.

## Decision

Simplify and unify composables related to creating screens that show conversation lists.
Remove old, unused code, like things that were implemented in order to make the bottom tabs or code 
leftover from previous refactors, and update to make it more readable, reusable and maintainable.
Make it more similar to what we have in other places - instead of having complicated "routers" or 
"bridges", just create "content" composable that can be used on multiple screens, 
but with the intention that common `ViewModel`s are incorporated into this content composable,
so that they do not have to be added each time, but make it possible to generate previews.
Also, make use of `AssistedInject` to reduce the number of functions and `LaunchedEffect`s needed.

## Consequences

- `ConversationRouterHomeBridge` is now replaced with simpler `ConversationsScreenContent`, 
  which is a single composable to be used to create multiple screens that show conversation lists.
- `ConversationListViewModel` uses `AssistedInject` to provide `ConversationsSource` and a `Flow`
  of search query `String`s directly in constructor instead of doing it using multiple functions.
- `ConversationListViewModel` and `ConversationCallListViewModel` are injected using unique keys,
  so that for each `ConversationsSource` there is a separate `ViewModel`. Thanks to that, together 
  with assisted injection, they are now dedicated to each type which makes it easier to maintain, 
  debug and even use on the same screen if needed.
- Both mentioned `ViewModel`s are now also interfaces that are implemented by the respective
  `ConversationListViewModelImpl` and `ConversationCallListViewModelImpl` and "preview" versions 
  of these interfaces are also created to make it possible to generate composable previews.

**Comment by saleniuk** [comment]
> Looks good to me! Before adding the ✅ What about adding ADR? since we are refactoring and removing lots of code (👏 ) and unifying to new ones (🙌 )

Good idea! I forgot about it, let me know if the ADR that I just added to this PR is fine or needs some improvements. 😄

**Review by yamilmedina — APPROVED** [review]
🚀

**Pull request merged**
