### PR TITLE
refactor: stop using and remove selfDeletionStartDate [WPB-6219]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-6219" title="WPB-6219" target="_blank">TaskWPB-6219</a>  [Android] Self deleting messages - Remove self_deletion_start_date field from the DB
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

`selfDeletionStartDate` is deprecated and should be removed and fully replaced by `selfDeletionEndDate` but it is still used in some places.

### Solutions

Replace `selfDeletionStartDate` by `selfDeletionEndDate` and update the logic accordingly.
Also, use updated kalium version where `self_deletion_start_date` is already removed and not used as well.

### Dependencies (Optional)

Needs releases with:

- https://github.com/wireapp/kalium/pull/2689

#### Test Coverage (Optional)

- [x] I have added automated test to this contribution - `SelfDeletionTimerTest` already covers all cases

#### How to Test

Send some self-deleting messages, update the app to perform DB migration and check if everything is ok with these messages.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [3870](https://10.10.124.134/job/AR-build-pipeline/3870/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9275825)(9275825)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9275825)(9275825)-staging-compat.apk)

**Review by Garzas — APPROVED** [review]

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [3932](https://10.10.124.134/job/AR-build-pipeline/3932/) **failed**.

**Comment by AndroidBob** [comment]
Build [3935](https://10.10.124.134/job/AR-build-pipeline/3935/) **failed**.

**Comment by AndroidBob** [comment]
Build [3944](https://10.10.124.134/job/AR-build-pipeline/3944/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.7.0(9318651)(9318651)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.7.0(9318651)(9318651)-staging-compat.apk)

**Pull request merged**
