### PR TITLE
[AN-5317][AN-5306] Fix teams add members

### PR DESCRIPTION
**Pull request by JPonte**
Tickets:
https://wearezeta.atlassian.net/browse/AN-5306
https://wearezeta.atlassian.net/browse/AN-5317
#### APK
[Download build #8958](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8958/artifact/build/artifact/wire-dev-PR907-8958.apk)
[Download build #8968](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8968/artifact/build/artifact/wire-dev-PR907-8968.apk)
[Download build #8970](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8970/artifact/build/artifact/wire-dev-PR907-8970.apk)
[Download build #8976](http://192.168.10.18:8080/job/Pull%20Request%20Builder/8976/artifact/build/artifact/wire-dev-PR907-8976.apk)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Removed QA label since the build is not ready to be reviewed yet

**Comment by JPonte** [comment]
build again

**Comment by mykola-mokhnach** [comment]
1. Open group conversation details.
2. Tap Add People
3. Type something in the search field
4. Delete the typed text

AR:
ADD button is visible there, however no users are selected

ER:
ADD button should be only visible if there are selected users to be added to the group

**Comment by mykola-mokhnach** [comment]
LGTM

**Pull request merged**
