### PR TITLE
chore: update some used dependencies

### PR DESCRIPTION
**Pull request by ohassine**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [ ] contains a reference JIRA issue number like `SQPIT-764`
    - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

Some of our used libraries are not up to date

### Solutions

Updating some of them to benefit from released fixes

Some release notes of updated libs:
- [Coil 2.2.2](https://github.com/coil-kt/coil/blob/main/CHANGELOG.md#222---october-1-2022)
- [Exifinterface 1.3.5](https://developer.android.com/jetpack/androidx/releases/exifinterface#1.3.5)
- [Splashscreen](https://developer.android.com/jetpack/androidx/releases/core#core-splashscreen-1.0.0)
- [Paging3Compose](https://developer.android.com/jetpack/androidx/releases/paging#1.0.0-alpha17)
- [ Lifecycle 2.5.1](https://developer.android.com/jetpack/androidx/releases/lifecycle#2.5.1)
- [Hilt 2.44.2](https://github.com/google/dagger/releases/tag/dagger-2.44.2)
- [Accompanist 0.27.1](https://github.com/google/accompanist/releases/tag/v0.27.1)
- [Fragment 1.5.5](https://developer.android.com/jetpack/androidx/releases/fragment#1.5.5)
- [kotlin 1.7.21](https://github.com/JetBrains/kotlin/releases/tag/v1.7.21)

Needs releases with:

- [ ] GitHub link to other pull request

### Notes (Optional)

This is an update for the the build numbe, it will not contain major changes

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1](https://10.10.124.134/job/wire-android-reloaded/job/PR-1364/1/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(5551219)(5551219)-dev-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/compat/com.wire.android-vv0.0.1(5551219)(5551219)-dev-compat.apk)

**Comment by vitorhugods** [comment]
Do we really want to do these for the RC?

Shouldn't we do it for develop only?

**Comment by tmspzz** [comment]
I don't think we can afford updating dependencies on RC. This should be on develop only.

**Review by tmspzz — CHANGES_REQUESTED** [review]
See my other comment. Updates to libraries only on develop at this point.

**Comment by ohassine** [comment]
Closing it as it's not needed for RC

**Pull request closed without merging**
