### PR TITLE
feat: Use enroll mls use case (WPB-5756)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-5756" title="WPB-5756" target="_blank">Sub-taskWPB-5756</a>  Connect E2EI Renewal Dialog to E2EI Enrollment Usecase
  </td></table>
  <br />
 

# What's new in this PR?

### Issues

In Device settings AND E2EIRequired dialog: when user clicks on "Get Certificate" button nothing happens

### Causes (Optional)

The getting certificate it self wasn't implemented yet.

### Solutions

- use `GetE2EICertificateUseCase` in these cases.
- implement error handling for getting the certificate.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2228](https://10.10.124.134/job/AR-build-pipeline/2228/) **failed**.

**Comment by AndroidBob** [comment]
Build [2229](https://10.10.124.134/job/AR-build-pipeline/2229/) **failed**.

**Comment by AndroidBob** [comment]
Build [2234](https://10.10.124.134/job/AR-build-pipeline/2234/) **failed**.

**Comment by AndroidBob** [comment]
Build [2238](https://10.10.124.134/job/AR-build-pipeline/2238/) **failed**.

**Comment by AndroidBob** [comment]
Build [2245](https://10.10.124.134/job/AR-build-pipeline/2245/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8341105)(8341105)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8341105)(8341105)-staging-compat.apk)

**Review by mchenani — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2258](https://10.10.124.134/job/AR-build-pipeline/2258/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8349080)(8349080)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8349080)(8349080)-staging-compat.apk)

**Review by alexandreferris — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [2271](https://10.10.124.134/job/AR-build-pipeline/2271/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.6.0(8350362)(8350362)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.6.0(8350362)(8350362)-staging-compat.apk)

**Pull request merged**
