### PR TITLE
feat: User verification status Proteus (WPB-1775)

### PR DESCRIPTION
**Pull request by borichellow**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/WPB-1775" title="WPB-1775" target="_blank">StoryWPB-1775</a>  [Proteus] show that a user is verified
  </td></table>
  <br />
 

# What's new in this PR?

If all the users clients are verified (in Proteus protocol), then this user is Verified and should be displayed in the corresponding way (blue shield icon, see the screenshots).

----
#### Waiting [the kalium PR](https://github.com/wireapp/kalium/pull/2111)

----

### Attachments (Optional)

Screenshot 2023-10-04 at 14 42 37
Screenshot 2023-10-04 at 14 42 24
Screenshot 2023-10-04 at 14 42 15

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [1141](https://10.10.124.134/job/AR-build-pipeline/1141/) **failed**.

**Comment by AndroidBob** [comment]
Build [1142](https://10.10.124.134/job/AR-build-pipeline/1142/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7745517)(7745517)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7745517)(7745517)-staging-compat.apk)

**Review by gongracr — APPROVED** [review]
Great stuff soldier 🫡🛡️

**Review by mchenani — APPROVED** [review]

**Comment by AndroidBob** [comment]
Build [1165](https://10.10.124.134/job/AR-build-pipeline/1165/) **failed**.

**Comment by AndroidBob** [comment]
Build [1180](https://10.10.124.134/job/AR-build-pipeline/1180/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7762640)(7762640)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7762640)(7762640)-staging-compat.apk)

**Comment by AndroidBob** [comment]
Build [1265](https://10.10.124.134/job/AR-build-pipeline/1265/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-v4.5.0(7814942)(7814942)-staging-compat.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/staging/compat/com.wire.android-v4.5.0(7814942)(7814942)-staging-compat.apk)

**Pull request merged**
