### PR TITLE
feat: messages scala migration [AR-2626]

### PR DESCRIPTION
**Pull request by saleniuk**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/AR-2626" title="AR-2626" target="_blank">SubtaskAR-2626</a>  Migrate messages data
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
    - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
    - [x] contains a reference JIRA issue number like `SQPIT-764`
    - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
    - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In order to perform a full migration from the scala app, we need to persist all messages that haven't been stored during the sync.

### Solutions

- `ScalaMessageDAO` to fetch all messages from the scala DB
- `ScalaUserDAO` to fetch user data - required to get the user's domain which isn't stored in message data
- `MigrateMessagesUseCase` which performs this step of migration and passes mapped data to proper use case in kalium

### Dependencies (Optional)

https://github.com/wireapp/kalium/tree/feat/migration-messages

Needs releases with:

- https://github.com/wireapp/kalium/pull/1114

#### How to Test

Install and log in to the scala app and update to the AR version, the app should perform the migration and be already logged in and able to send and receive messages.

----
#### PR Post Submission Checklist for internal contributors (Optional)

- [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

- [x] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by AndroidBob** [comment]
Build [2](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/2/) **failed**.

**Comment by AndroidBob** [comment]
Build [3](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/3/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4861053)(4861053)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4861053)(4861053)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [4](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/4/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4861392)(4861392)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4861392)(4861392)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [5](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/5/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4886862)(4886862)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4886862)(4886862)-dev-release.apk)

**Comment by AndroidBob** [comment]
Build [6](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/6/) **failed**.

**Comment by AndroidBob** [comment]
Build [7](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/7/) **failed**.

**Comment by AndroidBob** [comment]
Build [8](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/8/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4895608)(4895608)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4895608)(4895608)-dev-release.apk)

**Review by yamilmedina — APPROVED** [review]
Awesome job🪁

**Comment by AndroidBob** [comment]
Build [9](https://10.10.124.134/job/wire-android-reloaded/job/PR-1141/9/) **succeeded**.

The build produced the following APK's:
- [com.wire.android-vv0.0.1(4903854)(4903854)-dev-release.apk](https://z-lohika.s3-eu-west-1.amazonaws.com/megazord/android/reloaded/dev/release/com.wire.android-vv0.0.1(4903854)(4903854)-dev-release.apk)

**Pull request merged**
